### ISSUE TITLE
migrate conda package from bioconda to conda-forge

### ISSUE THREAD

**Issue by luizirber** [dib-lab/sourmash#1004]
During the 3.3.1 release I discovered that sourmash was [blacklisted](https://github.com/bioconda/bioconda-recipes/pull/22361) in bioconda, apparently due to ["the migration to R 4.0 (and other pinning changes)"](https://github.com/bioconda/bioconda-recipes/issues/22146).

Bioconda is based on conda-forge, but with different ways to work with recipes. Bioconda keeps all recipes in the same repo. conda-forge has the [`staged-recipes`](https://github.com/conda-forge/staged-recipes) repo for initial submission, and when it's approved it generates a `feedstock`, a separate repo under conda-forge just for that recipe. [Example adding `rclone`](https://github.com/conda-forge/staged-recipes/pull/10145) and the [generated feedstock repo](https://github.com/conda-forge/rclone-feedstock).

conda-forge supports more architectures (`arm64`, `ppc`) and operating systems (windows). 

conda-forge has very good automation and organization-wide migrations. They also seem to have more active members (with bioconda being a subset, since most bioconda devs are also conda-forge devs). Oh, and [governance](https://conda-forge.org/docs/orga/00_intro.html).

Blockers for migration:
- all dependencies need to be in conda-forge. This is already the case for most our deps, except `screed` (easy to migrate) and `bam2fasta` (harder, because it depends on other bioconda recipes, namely `pysam`, which brings `bcftools`, `htslib` and `samtools`).
  * possible solution: define `sourmash-minimal` in conda-forge, and `sourmash` in bioconda. snakemake has a similar solution, where `snakemake-minimal` has only the minimal dependencies required to run, and `snakemake` depends on it and brings all the other deps (like AWS and GCP support).
- conda-forge doesn't have the equivalent of [biocontainers](https://quay.io/repository/biocontainers/sourmash?tab=tags).
  * the `sourmash-minimal`/`sourmash` split above would keep the `sourmash` biocontainers working, tho.

**Comment by ctb** [comment]
+1 sourmash-minimal.

Very surprised that bioconda blacklisted sourmash without letting us know. You _are_ listed as a maintainer!

**Comment by luizirber** [comment]
Migrated. [sourmash-minimal](https://github.com/conda-forge/sourmash-minimal-feedstock/) builds in Linux, MacOS, Windows for Python 3.6, 3.7, 3.8 and PyPy (still need to figure out 2.7, which is not supported officially anymore in conda-forge).

[screed](https://github.com/conda-forge/screed-feedstock/) and [`sourmash` in bioconda](https://github.com/bioconda/bioconda-recipes/blob/101fb3e6dc005a76c27b11170983acd304ea819d/recipes/sourmash/meta.yaml) are pure Python packages now, and work with any OS/Arch where the other deps are available (any dependency coming from bioconda implies Linux and MacOS only).

The `sourmash` biocontainers [continues to work](https://quay.io/repository/biocontainers/sourmash?tab=tags), using Python 3.7 (the default in bioconda).

PR removing screed and adapting sourmash in bioconda: https://github.com/bioconda/bioconda-recipes/pull/22364

**Comment by ctb** [comment]
thanks, Luiz!
