### ISSUE TITLE
Dealing with scaled=1

### ISSUE THREAD

**Issue by luizirber** [dib-lab/sourmash#1010]
Sometimes we recommend `--scaled 1` for exploration, but that can be dangerous. Internally the MinHash sketch is implemented as a sorted vector. They are good when operating on already calculated MinHash sketches (comparing, search, gather), but not so much for `compute`.  Since `scaled=1` keeps all hashes, any time a new one is inserted it will potentially force the reallocation of the whole vector, and it is really easy to get stuck with a very long running time (even for small bacterial genomes).

Possible solution: "Frozen" MH. In Python there is usually a "frozen" variant for some structures (`set` and `dict` come to mind) that don't allow insertion/removal but are optimize for indexing/access. We could do something like that, and use frozen versions for `compare`, `search` and `gather`. The current implementation would pretty much be the frozen version, and for efficient insertion we can use a `BTreeSet` or `BTreeMap` (for abundances) in Rust. On the Rust side the API can use `.into_mut()` or other `Into`-like methods to go from one representation to the other.

**Comment by ctb** [comment]
yes! https://github.com/dib-lab/sourmash/issues/90
