### ISSUE TITLE
Difficulty in matching dendrogram & heatmap names to filenames

### ISSUE THREAD

**Issue by terrycojones** [dib-lab/sourmash#1023]
Hi all - firstly, thanks for `sourmash`! I was going to implement my own minhash and was very happy to find `sourmash`.

When following the instructions on using `sourmash` (running `compute`, `compare` and `plot`), I end up with `.png` files of a heatmap and a dendrogram. However the labels of the files involved are almost unreadable (see attached, and that's when I'm zoomed in) and (in the dendrogram are truncated to identical suffixes).

Before going to look at the code to see if it's easy to do something about this, I'm wondering if the order of the filenames in the `.labels.txt` file will match the 0-based numbering in the heatmap labels? If so I can try harder to make out the numbers in the heatmap.

Thanks for any suggestions / help!

![Screenshot from 2020-06-15 10-59-50](https://user-images.githubusercontent.com/132978/84638510-656cb680-aef7-11ea-9cee-71909aef14bd.png)
![Screenshot from 2020-06-15 11-00-48](https://user-images.githubusercontent.com/132978/84638612-833a1b80-aef7-11ea-9425-c7ea830111e3.png)

**Comment by ctb** [comment]
ugh, this has been a persistent frustration for me, too! and I have spent what feels like multiple lifetimes tracking it down and resolving it! 😂

I _think_ this issue was raised in https://github.com/dib-lab/sourmash/issues/220 and will be resolved by https://github.com/dib-lab/sourmash/pull/859. I can move forward with that work if it would solve your problem, lmk!

**Comment by ctb** [comment]
code & examples now integrated in #859!

**Comment by terrycojones** [comment]
@ctb Thank you! Sorry for the lack of replies, this went off my radar.  I think we met or nearly met at some point many years ago - were you involved in alife stuff at all? SFI?  Thanks again, Terry

**Comment by ctb** [comment]
hi terry, welcome! no worries, and as you might tell from the pull request, it was an oft-requested thing that is very useful to have :)

yes! back in the '90s, alife & digital life!
