### ISSUE TITLE
Query routines should identify and extract single signatures w/o requiring parameters

### ISSUE THREAD

**Issue by ctb** [dib-lab/sourmash#105]
so if there's a single k=21 protein signature, it will "understand" and go with -k 21 --protein; needs to be tested, of course.

Needs to be done/checked/tested for:
- [ ] search
- [ ] compare
- [ ] watch
- [ ] gather

#108 does this for
- [x] sbt_index
- [x] sbt_search
- [x] categorize

**Comment by betatim** [comment]
Started looking at this for search/compare/etc

**Comment by ctb** [comment]
Note addition of `load_one_signature` in #155.

**Comment by ctb** [comment]
Verify fixed in #119.

**Comment by betatim** [comment]
Fixed in #224
