### ISSUE TITLE
fix sourmash split docs

### ISSUE THREAD

**Issue by ctb** [dib-lab/sourmash#1091]
the [`sourmash signature split` docs](https://sourmash.readthedocs.io/en/latest/command-line.html#sourmash-signature-split) incorrectly state that it is the only command that supports loading signatures from LCA and SBTs.

The fix here is to remove the following text from `doc/command-line.md` in the sourmash repo:

> Note: unlike the rest of the sourmash sig commands, split can load signatures from LCA and SBT databases as well.

**Comment by keyabarve** [comment]
@ctb Can I work on this issue?

**Comment by ctb** [comment]
go for it!
