### ISSUE TITLE
Recommend declaring matplotlib and scipy as optional "figures" dependency

### ISSUE THREAD

**Issue by jkahn** [dib-lab/sourmash#11]
figure generation in both the interior library and in the commandline require that scipy and matplotlib be installed.  I recommend an [optional dependency](https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies) named `fig` or `figures`.

**Comment by ctb** [comment]
done; I actually made them default since the tests need 'em
