### ISSUE TITLE
define a canonical way to check compatibility of MinHash objects in Python

### ISSUE THREAD

**Issue by ctb** [dib-lab/sourmash#1107]
I'm running into a bug in `sourmash sig intersect` where it doesn't check the compatibility of the MinHash objects (ksize, moltype, etc.) before doing the intersection. What's the canonical way to do this?

The Rust API defines a `check_compatible` function - @luizirber is this an appropriate function to expose via the Python API?

**Comment by ctb** [comment]
(for now, I'm using `count_common` to check)

**Comment by luizirber** [comment]
> I'm running into a bug in `sourmash sig intersect` where it doesn't check the compatibility of the MinHash objects (ksize, moltype, etc.) before doing the intersection. What's the canonical way to do this?
> 
> The Rust API defines a `check_compatible` function - @luizirber is this an appropriate function to expose via the Python API?

I think so. There is a `ksize` check commented out because something was breaking when it was activated, but I think it was fixed.

**Comment by erikyoung85** [comment]
is there any reason to not use the minhash function `is_compatible(self, other_minhash)`? From what I can understand, it calls the rust `check_compatible` function you mentioned earlier. I'll push the line I added to the `intersect(...)` function.

**Comment by ctb** [comment]
I ...somehow missed it. Thank you!

best,
--titus

On Mon, Jul 20, 2020 at 02:56:40PM -0700, Erik Young wrote:
> is there any reason to not use the minhash function `is_compatible(self, other_minhash)`? From what I can understand, it calls the rust `check_compatible` function you mentioned earlier. I'll push the line I added to the `intersect(...)` function.
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/dib-lab/sourmash/issues/1107#issuecomment-661356523
-- 
C. Titus Brown, ctbrown@ucdavis.edu

**Comment by luizirber** [comment]
> is there any reason to not use the minhash function `is_compatible(self, other_minhash)`? From what I can understand, it calls the rust `check_compatible` function you mentioned earlier. I'll push the line I added to the `intersect(...)` function.

Great catch! `check_compatible` throws an exception, `is_compatible` returns a bool. (and I forgot it was exposed already :rofl: )
