### ISSUE TITLE
add / resolve issues with release process documentation

### ISSUE THREAD

**Issue by ctb** [dib-lab/sourmash#1109]
(this extracts still-relevant issues from the meandering discussion in #955)

the sourmash releases page has weird releases show up, e.g. https://github.com/dib-lab/sourmash/releases/tag/r0.9.0. I think they're from the release candidates? Or maybe the rust builds? What should we do about them, if anything?

I note on https://pypi.org/project/sourmash/3.2.3/ that the first line of the README shows up, `<meta charset="utf-8"/>`. Should we fix/remove?

**Comment by luizirber** [comment]
> the sourmash releases page has weird releases show up, e.g. https://github.com/dib-lab/sourmash/releases/tag/r0.9.0. I think they're from the release candidates? Or maybe the rust builds? What should we do about them, if anything?

They are the `core` rust versions, which are versioned differently than `sourmash`. These tags are the versions published in https://crates.io/crates/sourmash.

I'll try to find if there is a way to hide them in releases...

> I note on https://pypi.org/project/sourmash/3.2.3/ that the first line of the README shows up, `<meta charset="utf-8"/>`. Should we fix/remove?

Yes, remove. This is something for `crates.io` display, but now the README for it comes from `src/core/README.md`, so no good reason to mess the PyPI display.

**Comment by ctb** [comment]
between them, #1124 and #1125 will close this issue.
