### ISSUE TITLE
sbt tests use not-installed demo sigs

### ISSUE THREAD

**Issue by ctb** [dib-lab/sourmash#116]
`test_binary_nary_tree` and `test_tree_save_load` fail for a non-obvious reason when running the tests in installed mode: `py.test --pyargs sourmash_lib`.

This turns out to be because they use glob to retrieve `demo/*.sig`. The glob returns an empty list and the test fails later on because the tree is empty.

**Comment by luizirber** [comment]
Would it be OK to put some signatures on `test-data` (about 10-15)?

**Comment by ctb** [comment]
of course!

**Comment by luizirber** [comment]
fixed in #142
