### ISSUE TITLE
sbt_index fails (me)

### ISSUE THREAD

**Issue by viehwegerlib** [dib-lab/sourmash#122]
Dear all,

I am trying to use the SBT with some minhash sigs.

I am using Python3.5 and installed the sourmash masterbranch using pip in a virtualenv.

```
pip install git+https://github.com/dib-lab/sourmash
```

I then downloaded some precomputed signatures linked in TCB's latest [blog post](http://ivory.idyll.org/blog/2017-sourmash-sra-microbial-wgs.html).

```
wget http://spacegraphcats.ucdavis.edu.s3.amazonaws.com/2017-01-18-microbial-wgs-sigs.tar.gz
tar xzf 2017-01-18-microbial-wgs-sigs.tar.gz
```

I selected a couple of them (subset, contains about 10 sigs) and ran sourmash sbt_index, which fails with

```
ls subset
# DRR000001.sig
# DRR000002.sig
# DRR000149.sig
# DRR000183.sig
# DRR000184.sig
# DRR000185.sig
# DRR000186.sig
# DRR000189.sig
# DRR000467.sig
# DRR000564.sig

sourmash sbt_index bacteria --traverse-directory subset/

loading 10 files into SBT
Traceback (most recent call last):
  File "/Users/pi/.virtualenvs/lab3/bin/sourmash", line 11, in <module>
    load_entry_point('sourmash==1.1', 'console_scripts', 'sourmash')()
  File "/Users/pi/.virtualenvs/lab3/lib/python3.5/site-packages/sourmash_lib/__main__.py", line 1009, in main
    SourmashCommands()
  File "/Users/pi/.virtualenvs/lab3/lib/python3.5/site-packages/sourmash_lib/__main__.py", line 63, in __init__
    cmd(sys.argv[2:])
  File "/Users/pi/.virtualenvs/lab3/lib/python3.5/site-packages/sourmash_lib/__main__.py", line 569, in sbt_index
    tree.add_node(leaf)
  File "/Users/pi/.virtualenvs/lab3/lib/python3.5/site-packages/sourmash_lib/sbt.py", line 135, in add_node
    node.update(p.node)
  File "/Users/pi/.virtualenvs/lab3/lib/python3.5/site-packages/sourmash_lib/sbtmh.py", line 21, in update
    parent.data.count(v)
TypeError: must be str, not int
``` 

I feel I am using it wrongly, but fail to see my mistake. Help is greatly appreciated.

**Comment by viehwegerlib** [comment]
Yeah, it was me. Browsing the issue tracker, this fixed my problem:

```
pip install git+https://github.com/dib-lab/sourmash.git@master
pip install git+https://github.com/dib-lab/khmer.git@master
```

**Comment by ctb** [comment]
excellent!

On Fri, Jan 20, 2017 at 03:20:42AM -0800, viehwegerlib wrote:
> Yeah, it was me. Browsing the issue tracker, this fixed my problem:
> 
> ```
> pip install git+https://github.com/dib-lab/sourmash.git@master
> pip install git+https://github.com/dib-lab/khmer.git@master
> ```
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/dib-lab/sourmash/issues/122#issuecomment-274049561
-- 
C. Titus Brown, ctbrown@ucdavis.edu
