### ISSUE TITLE
signature name multifasta input

### ISSUE THREAD

**Issue by phiweger** [dib-lab/sourmash#132]
When using multifasta, the `--singleton` option  of `sourmash compute` is really useful. However, when one later queries each signature against an SBT, e.g. with `sourmash categorize`, the output format is:

```
filename, some_hit_id, similarity
filename, another_hit_id, similarity
...
```

Is there an option to carry the fasta header, so that it appears instead of the same filename againandagainandagain? I tried `--name-from-first`, but I think it was not meant for this purpose right?

Thx!

**Comment by viehwegerlib** [comment]
To make this more clear perhaps:

It would be nice given a multifasta

```
>foo
ACTGATAC
>bar
TTTAGAAT
```

after `sourmash compute --singleton` to get `sourmash categorize` to output something like 

```
loaded query: foo ... (k=16, DNA)
for foo, found: 0.24 someotherid
```

Currently the command prints only the filename of the multifasta instead of "foo".

**Comment by ctb** [comment]
@phiweger could you take a look at #421 and see if it fixes this? Apologies to take so long!
