### ISSUE TITLE
test.sh mentions missing `sourmash clean` subcommand

### ISSUE THREAD

**Issue by jkahn** [dib-lab/sourmash#14]
(possible duplicate ticket? I am having connectivity problems).
`test.sh` file mentions `sourmash clean`; this subcommand doesn't exist.
choices are (as I can see):
- remove invocation
- implement `clean` subcommand
- change to `make clean` (?)

**Comment by ctb** [comment]
I think 'remove test.sh' is the right approach here; it's old.  Thx!

**Comment by jkahn** [comment]
works for me. Less to understand as a reviewer!

**Comment by ctb** [comment]
Done!
