### ISSUE TITLE
correct way to use sourmash_lib (interactive Python) to create and search SBT

### ISSUE THREAD

**Issue by phiweger** [dib-lab/sourmash#147]
Is this the "correct" way (@luizirber?) to populate an SBT using the sourmash_lib from within Python (i.e. not the CLI):

```
# https://github.com/luizirber/2016-sbt-minhash/blob/master/notebooks/SBT%20with%20MinHash%20leaves.ipynb
from sourmash_lib import Estimators
from sourmash_lib.sbt import SBT, GraphFactory
from sourmash_lib.sbtmh import SigLeaf
from sourmash_lib.signature import SourmashSignature

seq = db.ref.find_one()['sequence']  # some sequence, 'ACTG...'
K = 16
e = Estimators(ksize=K, n=200)
e.add_sequence(seq)  # e.get_hashes()
s = SourmashSignature('', e, name='')
factory = GraphFactory(ksize=K, starting_size=1e5, n_tables=4)
# 4 .. nt?
tree = SBT(factory)
leaf = SigLeaf(metadata='', data=s)
# SigLeaf(metadata, data, name=None)

tree.add_node(node=leaf)
```

Thanks a lot.

**Comment by luizirber** [comment]
Yup! (sorry for taking so long to reply...)

**Comment by viehwegerlib** [comment]
no worries, i ran some tests and convinced myself of the above being largely correct, but its always good to have confirmation that i did not overlook some trap/ weird behaviour etc., thanks!

**Comment by viehwegerlib** [comment]
How can I query a sequence using the API?

Thanks.

**Comment by claczny** [comment]
Any update on that note? Would love to know the answer too :)

Best,

Cedric

**Comment by ctb** [comment]
see https://gist.github.com/ctb/40da5a63a173dfdf4b109ffde7b76874 and specifically [build-and-search.py](https://gist.github.com/ctb/40da5a63a173dfdf4b109ffde7b76874#file-build-and-search-py) - hope that helps!

and clearly we need to clean up the API. There's a lot of unnecessary stuff in there.

**Comment by ctb** [comment]
Added in #436.
