### ISSUE TITLE
Figures in `command-line` docs are missing

### ISSUE THREAD

**Issue by jkahn** [dib-lab/sourmash#15]
Figures in [command line docs](http://sourmash.readthedocs.io/en/latest/command-line.html) are not found. I can't find the .png in the source code either.

This is still true after running `make`; is there some other process that needs to be run on readthedocs so -- or my own Ubuntu machine -- so that the figures look better?

**Comment by ctb** [comment]
Fixed; ignored by my global .gitignore.

**Comment by ctb** [comment]
(Present now! http://sourmash.readthedocs.io/en/latest/command-line.html)
