### ISSUE TITLE
--dna flag

### ISSUE THREAD

**Issue by taylorreiter** [dib-lab/sourmash#151]
Can we discuss the merit of changing `--dna` flag to `--nucleotide` or something that does not discriminate against RNA? :)

**Comment by ctb** [comment]
I don't think we handle U properly, do we?

**Comment by taylorreiter** [comment]
No, likely not...but the actual point was it has generated confusion for at least three users as to where RNA fits in to this.

**Comment by ctb** [comment]
or we could add a flag --rna that behaves exactly the same as --dna.

**Comment by taylorreiter** [comment]
+1
