### ISSUE TITLE
Renaming sourmash_lib module to sourmash

### ISSUE THREAD

**Issue by luizirber** [dib-lab/sourmash#162]
The `sourmash_lib` name seems to come from the project early days, when the entry point was the [`sourmash`][1] 'executable' in the project root (for dev purposes).

If we use `python setup.py develop` we don't need the 'executable', and then we can use the name instead of `sourmash_lib`

[1]: https://github.com/dib-lab/sourmash/blob/564f89d319e899fe5220c9644d7984e1b1f9053f/sourmash

**Comment by ctb** [comment]
-0 on this, at least for the way I work; I like to reference the sourmash script directly while I'm working on pythonland stuff, and having to run 'make' or 'python setup.py develop' seems like an added inconvenience.

**Comment by luizirber** [comment]
you already have to run `python setup.py build_ext -i` for it to work; `python setup.py develop` just need to be run once (during initial setup), if you working on pythonland.

**Comment by ctb** [comment]
I've been thinking about this for a while and (serendipitously) came across this:

https://pip.pypa.io/en/stable/reference/pip_install/#editable-installs

and this:

https://setuptools.readthedocs.io/en/latest/setuptools.html#development-mode

which I didn't really understand before :).  I will try it out and see what happens.

Is there a simple way to support both `import sourmash_lib` and `import sourmash` for the near future? The `select_ksize` debacle wrt `load_signature` was unpleasantly time wasting...
