### ISSUE TITLE
sourmash commandline tool should probably be an entry_point

### ISSUE THREAD

**Issue by jkahn** [dib-lab/sourmash#17]
The commandline util `sourmash` causes some structural grief in the git repo, since it has a name collision with the package directory.  Conventional approaches would be to include it instead as `sourmash_cli.py` somewhere and include it [as an entry point](https://chriswarrick.com/blog/2014/09/15/python-apps-the-right-way-entry_points-and-scripts/) in `setup.py`.

Moving the commandline tool to a different name might also allow you to rename `$repo/sourmash_lib` to `$repo/sourmash` which is (at least for the pure python modules I'm familiar with) the usual approach.

**Comment by ctb** [comment]
Hmm, interesting. I'm not worried about the `sourmash_lib/` name, as I expect this to be mostly used from the command line. Making the `sourmash` command an entry point is a good idea; I'll see if it's easy to do while still keeping the setup good for the way I develop (which is to do a 'python setup.py build_ext -i' in the repo directory). Thx!

**Comment by ctb** [comment]
done! as of 2d0f95c5c2
