### ISSUE TITLE
what version of setuptools do we require?

### ISSUE THREAD

**Issue by ctb** [dib-lab/sourmash#173]
just had to upgrade setuptools on my MSU HPC venv to get sourmash to compile b/c of the .pyx file needing to be automatically recognized as cython.

I went from setuptools-12.0.5 to setuptools-35.0.0.

might add something to requirements.txt...

**Comment by betatim** [comment]
I have 33.1.1 which seems to work as well.

**Comment by luizirber** [comment]
I think it needs to be >25 for the cython integration, will check.

**Comment by ctb** [comment]
is there any reason not to simply ask for a recent setuptools?
