### ISSUE TITLE
developer/testing doc needed

### ISSUE THREAD

**Issue by jkahn** [dib-lab/sourmash#18]
@ctb is on it, but I think there needs to be a few pieces of better documentation for how developers can get access to the test environment:
https://github.com/openjournals/joss-reviews/issues/27

For example, #12 and #10 both suggest that there are a few additional steps to take to work as an active developer (rather than a client) of the C bindings.

**Comment by jkahn** [comment]
Also, whatever is going on with the `SOURMASH_COVERAGE` environment variable belongs in that doc.

**Comment by ctb** [comment]
Mostly done, at https://github.com/dib-lab/sourmash/blob/master/doc/developer.rst

**Comment by ctb** [comment]
Finished, in 52cc1bf
