### ISSUE TITLE
make it easy to merge multiple signature files

### ISSUE THREAD

**Issue by ctb** [dib-lab/sourmash#196]
'cat *.sig > combined.sig' doesn't work b/c it doesn't produce valid JSON.

@luizirber recommended looking at: https://stackoverflow.com/questions/19529688/how-to-merge-2-json-file-using-jq

**Comment by betatim** [comment]
Should sourmash learn how to do this? In which case I think using python would be better than adding a new dependency. Or should we point it out in the docs and spread the word about `jq`?

**Comment by ctb** [comment]
I was thinking 'sourmash cat' might be an appropriate command.

and/or (for my particular use case) 'sbt extract-all' - I really wanted
to go from the SBT storage back to a single file of signatures.

**Comment by ctb** [comment]
It appears `jq add -s * > new-sigs.json` does the right thing but with the caveat that the md5sum of the signatures change for some reason. Looks to me like it might be a string encoding or numerical precision/bits problem - will look into it.

**Comment by ctb** [comment]
huh, OK, I don't see the problem any more.  So I will simply add this to the docs when I get the chance.

```
jq add -s ../GCF*.sig > combined.json
../sourmash compare combined.json
```

works fine.

**Comment by ctb** [comment]
see #587.
