### ISSUE TITLE
2017-metagenome branch odd sbt_gather behavior. 

### ISSUE THREAD

**Issue by taylorreiter** [dib-lab/sourmash#197]
I ran 
```
sourmash sbt_gather -k 21 ~/sourmash_SBTs/microbes.k31.sbt.json Oe6.scaffolds.fa.sig --threshold=0.01 -o microbes_k21_Oe6.scaffolds.fa.txt
```
I stopped this prematurely because I wanted to fiddle with something and it was taking hours to run, however this was posted to the command line output before I stopped the process:
```
loaded query: Oe6.scaffolds.fa.gz... (k=21, DNA)
query signature has max_hash: 36893488147419104
found: 0.09 0.00 NC_008513.1 Buchnera aphidicola BCc, complete genome
```
I was using sourmash installed from:
```
pip install https://github.com/dib-lab/sourmash/archive/master.zip
```
installed on 4/19/17.

I then installed a branch of sourmash with the following commands:
```
source sourmashEnv2/bin/activate
pip uninstall sourmash
pip install https://github.com/dib-lab/sourmash/archive/2017-metagenome.zip
```
and reran the command from up top with timing added in for other reasons:
```
/usr/bin/time -v -o time_microbes_k21.txt sourmash sbt_gather -k 21 ~/sourmash_SBTs/microbes.sbt.json Oe6.scaffolds.fa.sig --threshold=0.01 -o microbes_k21_Oe6.scaffolds.fa.txt
```

and received no matches. 

This behavior strikes me as odd/not right. 

The output of the timed file is as follows:
```
cat time_microbes_k21.txt 
	Command being timed: "sourmash sbt_gather -k 21 /home/ubuntu/sourmash_SBTs/microbes.sbt.json Oe6.scaffolds.fa.sig --threshold=0.01 -o microbes_k21_Oe6.scaffolds.fa.txt"
	User time (seconds): 24742.62
	System time (seconds): 44.86
	Percent of CPU this job got: 49%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 13:46:47
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 1533604
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 1
	Minor (reclaiming a frame) page faults: 20966136
	Voluntary context switches: 18226
	Involuntary context switches: 3195854
	Swaps: 0
	File system inputs: 959832
	File system outputs: 2408
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 0
```

**Comment by ctb** [comment]
Hi Taylor, how can we reproduce this? thx.

**Comment by taylorreiter** [comment]
The signature file is too large to post here, so please find it at this link: https://www.dropbox.com/s/tg86be5qkcn7f3b/Oe6.scaffolds.fa.sig?dl=0

Details about the software on the machine I was using can be found here:
https://github.com/taylorreiter/olive_public_seq/blob/master/RNA-seq/many_fruit/sourmash/0.installation.md

Details on how I obtained the SBT can be found here. The relevant portion is the first code block:
https://github.com/taylorreiter/olive_public_seq/blob/master/RNA-seq/many_fruit/sourmash/1.indexing.md

And details about how I created the linked signature file and each of the sbt runs I have subsequently run can be found here:
https://github.com/taylorreiter/olive_public_seq/blob/master/RNA-seq/many_fruit/sourmash/2.ref_genome_contamination_sourmash.md

Please let me know if I provided enough documentation about software versions etc. to reproduce this error, or if more information is required.

**Comment by ctb** [comment]
thanks, we'll take a look!

**Comment by luizirber** [comment]
A quick guess: the SBT search isn't really prepared for scaled yet, so searching for a signature with a scaled=500 will check MANY hashes at each internal node. I think we need to downscale the signature to match the SBT scaled value before searching.

(Having too many hashes to search will not stop until it is very close to the leaf level, which defeats the purpose of using the tree in the first place)

**Comment by taylorreiter** [comment]
Ah I was under the impression that the signature was downscaled to match the SBT scaled value before searching...I will start producing signatures that are the same scaled value as that of the SBT before I run it.

**Comment by ctb** [comment]
I don't think that's it - gather downsamples. My guess is that you're
falling victim to a new approach that limits output not by number of
shared hashes but rather by estimated number of bp of match.  Try
setting --threshold-bp=0.

--t

On Wed, Apr 26, 2017 at 09:10:46AM -0700, Taylor Reiter wrote:
> Ah I was under the impression that the signature was downscaled to match the SBT scaled value before searching...I will start producing signatures that are the same scaled value as that of the SBT before I run it.
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/dib-lab/sourmash/issues/197#issuecomment-297461758
-- 
C. Titus Brown, ctbrown@ucdavis.edu

**Comment by ctb** [comment]
@taylorreiter should I follow up on this more or can we close?

**Comment by taylorreiter** [comment]
I think it can be closed. I would note though, searching things at a threshold bp = 0 is not a great idea -- I would recommend 10kbp as the lower limit for eukaryotic genomes.
