### ISSUE TITLE
sourmash compute becomes very slow when -n > 100K

### ISSUE THREAD

**Issue by jiarong** [dib-lab/sourmash#209]
I was trying to get the shared minhash among many samples, so larger subsample was needed.

I tried 1K, 10K, 100K. The speed was almost constant. But 500K became very slow.

**Comment by ctb** [comment]
Hi @jiarong,

we will look into it. But you should not simply increase 'n' but rather
use '--scaled'.

--titus

**Comment by ctb** [comment]
This advice should be included in documentation for #238.

**Comment by ctb** [comment]
Closed by #419.
