### ISSUE TITLE
Recommend using argparse.add_subparser commands

### ISSUE THREAD

**Issue by jkahn** [dib-lab/sourmash#21]
https://docs.python.org/3/library/argparse.html#sub-commands

... rather than rolling your own in the `sourmash` CLI utility. 

Not a blocking concern, but a site for future improvement (and transferring maintenance debt to the core Python library!).

**Comment by luizirber** [comment]
Working on this as part of #245

**Comment by luizirber** [comment]
Hey look, this was fixed in #785!
