### ISSUE TITLE
inconsistency in output location

### ISSUE THREAD

**Issue by ctb** [dib-lab/sourmash#215]
`sourmash search` prints results to stdout.

`sourmash sbt_gather` prints results to stderr, but supplies a -o flag to save to a file.

we should make this consistent...

**Comment by mw55309** [comment]
Yes!  Was very confused that "results" are printed to STDERR

sbt_search and sbt_gather go to STDERR

**Comment by ctb** [comment]
This should now be fixed by #240 and others!
