### ISSUE TITLE
What defaults do we want?

### ISSUE THREAD

**Issue by luizirber** [dib-lab/sourmash#219]
Right now users need to provide quite a lot of parameters: what are good defaults so people can just run 
`$ sourmash compute input.fastq` and have useful results?

**Comment by ctb** [comment]
`--scaled 2000 --dna -k 31`

seems good to me.

**Comment by ctb** [comment]
I think maybe `-k 21,31,51` should be the default, to match our genbank databases.

note that at the moment I don't think there's a way to turn *off* `--scaled` so we'd have to add that.

**Comment by ctb** [comment]
we're discussing default parameters with respect to protein/dayhoff/hp signatures, where we may want different defaults. See https://github.com/dib-lab/sourmash/issues/999#issuecomment-646301552

**Comment by ctb** [comment]
I think #1159 closes this! yay!

**Comment by ctb** [comment]
Since I had trouble finding this, I wanted to highlight it here:


## default parameters as of #1159 [per code](https://github.com/dib-lab/sourmash/blob/latest/sourmash/command_sketch.py#L12) 

```
    dna='k=31,scaled=1000,noabund',
    protein='k=10,scaled=200,noabund',
    dayhoff='k=16,scaled=200,noabund',
    hp='k=42,scaled=200,noabund'
```

**Comment by ctb** [comment]
argh. looks like they're different in the code. editing.
