### ISSUE TITLE
sourmash plot slices

### ISSUE THREAD

**Issue by taylorreiter** [dib-lab/sourmash#221]
Plot a subset of a sourmash compare matrix. I'm not sure if it would be best for the user to specify which subset to plot, either by name or by similarity, or if a random subset should be plotted, or both.

**Comment by ctb** [comment]
I think the Right Way to do this is random subsampling, while #220 can deal with clusters and dendrograms and the like.

**Comment by ctb** [comment]
(There is no good way to specify a subset to plot other than specifying the samples, and then you might as well just `compare` the samples you're interested in!)

**Comment by ctb** [comment]
Addressed in #343; comments welcome.
