### ISSUE TITLE
reorder sbt gather/search arguments?

### ISSUE THREAD

**Issue by ctb** [dib-lab/sourmash#231]
I've never been happy with the order of the sbt_search and sbt_gather arguments; currently, they take SBT first, query signature second:

`sourmash sbt_search genbank.sbt.json query.sig`

and my fingers always want the arguments to be the other way around.

In thinking about #229, I'm wondering if we should just change the order like so:

`sourmash sbt_search query.sig genbank.sbt.json`

which would then support multiple SBTs more naturally:

`sourmash sbt_search query.sig genbank.sbt.json foo.sbt.json bar.sbt.json`

any thoughts @luizirber @taylorreiter @brooksph?

Hmm, we could even combine `search` and `sbt_search` by allowing search to take both SBTs and individual signatures. Whaddya think? Too confusing?

**Comment by luizirber** [comment]
Did anyone ever try to use `sbt_search` (or `search`) with more than one query sig? I think inverting is a good idea.

I also like the idea of combining `search` and `sbt_search`!

**Comment by brooksph** [comment]
I agree that the following order is more natural: 

```sourmash sbt_search query.sig genbank.sbt.json
```

I often type it that way at first. Searching multiple SBTs is useful but should probably be accompanied by multiple outputs or an output format that identifies the sbt where the match was found.

**Comment by ctb** [comment]
Closed by #240.
