### ISSUE TITLE
Warnings in Python 3

### ISSUE THREAD

**Issue by luizirber** [dib-lab/sourmash#251]
We are getting a bunch of `ResourceWarning: unclosed file` in the tests

https://travis-ci.org/dib-lab/sourmash/jobs/235499948#L397

**Comment by luizirber** [comment]
Also  `DeprecationWarning: generator 'load_signatureset_json_iter' raised StopIteration`
https://travis-ci.org/dib-lab/sourmash/jobs/235499948#L421

**Comment by ctb** [comment]
frickin' py.test updates

**Comment by luizirber** [comment]
Fixed by #546
