### ISSUE TITLE
Unexpectedly finding more results

### ISSUE THREAD

**Issue by mw55309** [dib-lab/sourmash#266]
An interesting thing happened.  Perhaps I misunderstand.

I ran

```sh
sourmash gather -k 31 brown_metagenome.sig /vol_b/public_data/sourmash_dbs/genbank-k31.sbt.json
```

And got

```
loaded query: /vol_b/public_data/minion_brow... (k=31, DNA)
loaded SBT /vol_b/public_data/sourmash_dbs/genbank-k31.sbt.json

overlap     p_query p_match
---------   ------- --------
320.0 kbp     3.6%    6.7%      AFVX01000096.1 Escherichia coli XH140...
found less than 10.0 kbp in common. => exiting

found 1 matches total;
the recovered matches hit 3.7% of the query
```

So far so good.

Then I relaxed the threshold to see more results

```sh
sourmash gather -k 31 
                --threshold-bp 100 brown_metagenome.sig /vol_b/public_data/sourmash_dbs/genbank-k31.sbt.json
```

Now I get more results, BUT ALSO MORE E COLI:

```
loaded query: /vol_b/public_data/minion_brow... (k=31, DNA)
loaded SBT /vol_b/public_data/sourmash_dbs/genbank-k31.sbt.json

overlap     p_query p_match
---------   ------- --------
320.0 kbp     3.6%    6.7%      AFVX01000096.1 Escherichia coli XH140...
10.0 kbp      0.1%    0.2%      LEEW01000001.1 Pseudomonas aeruginosa...
10.0 kbp      0.1%    0.6%      FLOK01000001.1 Helicobacter pylori is...
10.0 kbp      0.1%    0.5%      AHTB01000001.1 Streptococcus mutans B...
220.0 kbp     2.5%    0.2%      CDLB01000001.1 Escherichia coli O26:H...
10.0 kbp      0.1%    0.2%      AKVW01000001.1 Rhodobacter sphaeroide...
160.0 kbp     1.8%    0.2%      ABHR01000186.1 Escherichia coli O157:...
300.0 kbp     3.3%    0.2%      JWSO01000004.1 Escherichia coli strai...

found 8 matches total;
the recovered matches hit 4.3% of the query
```

Why weren't those additional E colis in my first set of results?

**Comment by ctb** [comment]
you do not misunderstand :). I can think of only one way for this to happen -
it is related to downsampling (but that may or may not be what is happening).

Could you tell me a few things/try a few things?

* what --scaled did you calculate your query signature with?

* what happens if you run the gather with `--scaled 10000` in both of the situations below?

thanks for reporting... food for thought :). clearly a bug of some sort
(although hopefully only in reporting)

**Comment by mw55309** [comment]
I ran compute with --scaled 10000 to generate the .sig and then ran gather without any scaled argument.

I'll try giving --scaled 10000 to gather....

**Comment by ctb** [comment]
ok well that shoots my hypothesis in the foot - no point in rerunning
gather with --scaled 10000, either.

would you mind sharing the signature? send to titus@idyll.org; I'll keep
it confidential.

thx,
--titus

**Comment by ctb** [comment]
Ahh! I understand it now - this is something that we have not done a good
job explaining and I am now convinced we should change it...

the search and thresholding is done on the bits of the metagenome that
haven't matched to anything yet.

the display, however, is of the entire match to the metagenome (including
the bits that match elsewhere).

so there's only a tiny bit that matches uniquely to the later E. coli that
show up, but when you take the whole match back to the full metagenome you
see that it also (redundantly with the first match) contains much of the
rest of the E. coli genome.

I have to think about how to do this properly but basically you should
disregard the later matches for now.  I will fix the output so that it is less
misleading...  somehow...

**Comment by ctb** [comment]
here is the CSV output -- let's see if I can make sense of it.

```
intersect_bp,f_orig_query,f_match,f_unique_to_query,name,filename,md5
320000.0,0.03567447045707915,0.06722689075630252,0.03567447045707915,"AFVX01000096.1 Escherichia coli XH140A plasmid pTHR, whole genome shotgun sequence",genbank/genbank-k31.sbt.json,3930dcbd8169727c07dd346c55303eb5
10000.0,0.0011148272017837235,0.001579778830963665,0.0011148272017837235,"LEEW01000001.1 Pseudomonas aeruginosa strain Pae_CF67.05s CF67.05s_contig_1, whole genome shotgun sequence",genbank/genbank-k31.sbt.json,a3b932549b8f76ca781843032c407479
10000.0,0.0011148272017837235,0.005847953216374269,0.0011148272017837235,"FLOK01000001.1 Helicobacter pylori isolate TC-2_8 genome assembly, contig: TC-2_8_001, whole genome shotgun sequence",genbank/genbank-k31.sbt.json,2a329e156bb5cac057a77599b6499a57
10000.0,0.0011148272017837235,0.005208333333333333,0.0011148272017837235,"AHTB01000001.1 Streptococcus mutans B contig1, whole genome shotgun sequence",genbank/genbank-k31.sbt.json,a068abdf294a54d2c75934413d34d8a5
220000.0,0.024526198439241916,0.0017793594306049821,0.0011148272017837235,"CDLB01000001.1 Escherichia coli O26:H11 genome assembly Escherichia coli O26:H11 21765, contig ECO26H_Contig_1, whole genome shotgun sequence",genbank/genbank-k31.sbt.json,6541294d23f67f40cd5b3c9aed407105
10000.0,0.0011148272017837235,0.00234192037470726,0.0011148272017837235,"AKVW01000001.1 Rhodobacter sphaeroides 2.4.1 chromosome 1, complete sequence, whole genome shotgun sequence",genbank/genbank-k31.sbt.json,0bcfadc5be5070d833f69523eeec465b
160000.0,0.017837235228539576,0.0019230769230769232,0.0011148272017837235,"ABHR01000186.1 Escherichia coli O157:H7 str. EC4401 gcontig_1107724394223, whole genome shotgun sequence",genbank/genbank-k31.sbt.json,1aa39353369d4ae351a7bb058661b077
300000.0,0.033444816053511704,0.001838235294117647,0.0011148272017837235,"JWSO01000004.1 Escherichia coli strain E16 deg7180000000028_quiver, whole genome shotgun sequence",genbank/genbank-k31.sbt.json,bd38767b2489e9adb7443755ba7b032c
```

**Comment by ctb** [comment]
Yes, that formatting is ok :). The `f_unique_to_query` is the bit that's *only* in the displayed match, while the `f_orig_query` is the overlap between *everything* in displayed match and the query metagenome. Clearly I need to work on our output... but hopefully you can see that `f_unique_to_query` is quite low for those later matches.

Apologies for crappy and confusing output, we'll fix!

**Comment by mw55309** [comment]
Great - how do I get CSV?

**Comment by ctb** [comment]
-o / --output should do that. Let me know if it doesn't :)

--
Titus Brown, ctbrown@ucdavis.edu
