### ISSUE TITLE
precomputed SBT indices

### ISSUE THREAD

**Issue by viehwegerlib** [dib-lab/sourmash#277]
Do you have precomputed SBT indices one could use out of the box? For example, is the index you computed for the 400k bacterial genomes still viable with the 2.x changes of sourmash?

**Comment by ctb** [comment]
Yes, the 400k SRA ones were done in JSON and should still work.

Also see:

https://sourmash.readthedocs.io/en/latest/databases.html

for Genbank and Refseq.

**Comment by viehwegerlib** [comment]
awesome, thanks a lot
