### ISSUE TITLE
Makefile install needs to specify test extras

### ISSUE THREAD

**Issue by jkahn** [dib-lab/sourmash#28]
The following pattern should work, but draws errors:

```
git checkout v0.9.4
mkvirtualenv --python=/usr/bin/python2.7 sourmash-py27
make clean install test
```
But if the `install` target was using `pip install .[test]` this *would* work. I've not quite got the PR formatted, but I'll just file the ticket here, as part of my second-pass review for [JOSS](https://github.com/openjournals/joss-reviews/issues/27).

**Comment by ctb** [comment]
`make test` now does `pip install '.[test]'`, as of 64597b.

Note that having the install target install the test extras would defeat the purpose of having them be extras - might as well just have them be default :). Admittedly, pretty much anyone using the Makefile is probably going to be a developer, so it probably doesn't matter.
