### ISSUE TITLE
Use iterators instead of directly accessing `mins` and `abunds` from C++ classes

### ISSUE THREAD

**Issue by luizirber** [dib-lab/sourmash#284]
Punted from #282:

- stop using `mins` directly. Since virtual inheritance only works for methods (and not members), this was creating a lot of weird boilerplate in Cython. 
  - The stopgap measure is to call `abunds` when using `KmerMinAbundance`, but this is still kinda ugly.
  - In the future, use iterators to access `hashes`, `abundances`, or pairs of `(hash, abundance)`. `count_common` doesn't need to be implemented in `KmerMinAbundance` if we do this, since the base `KmeMinHash::count_common` can iterate over the hashes only.
  - Expose iterators for Cython, and avoid accessing `mins` and `abunds` directly.

**Comment by ctb** [comment]
#896 seems relevant
