### ISSUE TITLE
scaled parameter for read sets

### ISSUE THREAD

**Issue by phiweger** [dib-lab/sourmash#298]
Am I doing it right if I put  a set of reads into `sourmash compute ... --scaled 2000 ...`, directly? I ask because I want to use the resulting signature with `sourmash gather`, but since it has like 600k hash values, this query takes forever. 

Do I have to assemble first or is there something I am missing to constrain the size of the signature?

I downloaded the premade SBT from [here](https://sourmash.readthedocs.io/en/latest/databases.html).

**Comment by viehwegerlib** [comment]
Just read issue #295 :)

But doesn't the minhash algo remove duplicate/ "redundant" sequences as well? I.e. what does digital normalization add?

**Comment by ctb** [comment]
short version: removal of erroneous k-mers (caused by sequencing error).

just getting back after a month away, expect more responses over the next week!

**Comment by ctb** [comment]
This was addressed in documentation updates - see https://sourmash.readthedocs.io/en/latest/using-sourmash-a-guide.html
