### ISSUE TITLE
Developer Makefile incomplete WRT sphinx, pip install

### ISSUE THREAD

**Issue by jkahn** [dib-lab/sourmash#30]
I did:
```
mkvirtualenv sourmash-py27
pip install -r requirements.txt # implied but not specified in docs
make clean all test
```
this drew a failure because `sphinx` wasn't installed.

Starting fresh:
```
pip install -r requirements.txt sphinx
make clean all test
```
succeeds (if you don't have a `.tox` directory lying around messing things up).

I might add that `all` is a funny name for a build target that builds the C++ library.

Minor concerns but still needs to be addressed for [ease of developer entree](https://github.com/openjournals/joss-reviews/issues/27).

**Comment by ctb** [comment]
The commands:

```
mkvirtualenv tst
make clean test
```

work fine as of #28 fix. In 3f0e49a, I've updated the developer documentation to remove the 'all' target since it's unnecessary with 'test'.

I've always seen & used `all` as the name of the default target in a Makefile. I'm not sure why it's odd in this contest?

**Comment by ctb** [comment]
(thanks for the bug report!)
