### ISSUE TITLE
Version number reported in PyPI, master disagrees with tag

### ISSUE THREAD

**Issue by jkahn** [dib-lab/sourmash#31]
Looks like tag `v0.9.4` actually installs `sourmash` `0.9.4rc1`, same as `master`.

Usual approach for prereleases is to have them on a branch (possibly 'master') and tag the *exact* release that sets the version number to `v0.9.4`. Subsequent branches should update the release number to `v0.9.5rc1` etc.

**Comment by ctb** [comment]
This has now been fixed with v0.9.6.

**Comment by ctb** [comment]
(and updated in the release docs)
