### ISSUE TITLE
Sourmash plot - colour of the dendrogram?

### ISSUE THREAD

**Issue by mw55309** [dib-lab/sourmash#311]
Hey

I have a sourmash plot after running sourmash compare, and the dendrogram just looks like some random colours.  Just cycles through black, yellow, pink, blue, red, green.  The dendrogram higher up is just blue.

How do I change/control this?  The dendrogram in your tutorial looks much smarter

Cheers
Mick

**Comment by ctb** [comment]
Hi Mick,

odd - the dendrogram in the tutorial is using a default matplotlib AFAIK!
Can you drop me the dendrogram you got in e-mail (or send me a screenshot
of a bit of it) so I can see what you're seeing?

A different fix would be to use `sourmash compare --csv` to output the
similarity matrix in CSV format, and then use R -- see

https://github.com/dib-lab/sourmash/pull/217

best,
--titus

On Mon, Aug 28, 2017 at 03:37:24PM +0000, Mick Watson wrote:
> Hey
> 
> I have a sourmash plot after running sourmash compare, and the dendrogram just looks like some random colours.  Just cycles through black, yellow, pink, blue, red, green.  The dendrogram higher up is just blue.
> 
> How do I change/control this?  The dendrogram in your tutorial looks much smarter
> 
> Cheers
> Mick
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/dib-lab/sourmash/issues/311
-- 
C. Titus Brown, ctbrown@ucdavis.edu

**Comment by mw55309** [comment]
Here you go 😊

**Comment by ctb** [comment]
no attachment?

**Comment by ctb** [comment]
closing for lack of response / reproducibility - will re-open if needed!

**Comment by susheelbhanu** [comment]
Hey Titus, 

I have the same questions. Here's the plot attached. Sorry for reopening the ticket. 

Cheers,
Susheel 
[LAO_sourmash_comp.matrix.pdf](https://github.com/dib-lab/sourmash/files/4469948/LAO_sourmash_comp.matrix.pdf)

**Comment by ctb** [comment]
no problem at all - thx for asking!

**Comment by ctb** [comment]
I'll take a look and see if we can adjust the default plotting to use a better color palette or something. @taylorreiter may have some ready to go R code that could help, too.

**Comment by susheelbhanu** [comment]
Yes, I saw that and am going to test it out. I also found it here: [Sourmash output in R](https://sourmash.readthedocs.io/en/latest/other-languages.htm)

Thanks for that. I was curious though if the colors meant something such as a similarity%, cluster maybe or is it random?

**Comment by ctb** [comment]
maybe useful links --

* search for 'color' [in the dendrogram library that we use](https://docs.scipy.org/doc/scipy/reference/generated/scipy.cluster.hierarchy.dendrogram.html)

* [custom coloring](https://stackoverflow.com/questions/38153829/custom-cluster-colors-of-scipy-dendrogram-in-python-link-color-func)

it's not hard to change the code to do something different, but I'd like to identify something that is a general improvement :)

**Comment by taylorreiter** [comment]
I do not have default R code laying around to color a dendogram, but ggtree is pretty nice for this type of thing: https://yulab-smu.github.io/treedata-book/chapter9.html#dendrogram

**Comment by susheelbhanu** [comment]
Thank you @taylorreiter 
@ctb please feel free to close the issue (I guess). Thanks again for the help.

**Comment by ctb** [comment]
(I'm planning to summarize the information ...somewhere... so will leave it
open :)

**Comment by ctb** [comment]
code & examples now integrated in #859!
