### ISSUE TITLE
installation fails

### ISSUE THREAD

**Issue by taylorreiter** [dib-lab/sourmash#314]
Both 
`pip install https://github.com/dib-lab/sourmash/archive/master.zip` and 
`git clone https://github.com/dib-lab/sourmash.git
cd sourmash
make`

fail with:
```
python setup.py build_ext -i
Unable to find pgen, not compiling formal grammar.
warning: no files found matching 'Doc/*'
warning: no files found matching '*.pyx' under directory 'Cython/Debugger/Tests'
warning: no files found matching '*.pxd' under directory 'Cython/Debugger/Tests'
warning: no files found matching '*.pxd' under directory 'Cython/Utility'
/var/folders/g7/vc0fd1nx27b43w436k06swzw0000gn/T/easy_install-5g6_8qwe/Cython-0.26.1/Cython/Compiler/Code.c:94306:93: warning: 
      code will never be executed [-Wunreachable-code]
        module = PyImport_ImportModule((PY_VERSION_HEX >= 0x03030000) ? "collections.abc" : "collections");
                                                                                            ^~~~~~~~~~~~~
/var/folders/g7/vc0fd1nx27b43w436k06swzw0000gn/T/easy_install-5g6_8qwe/Cython-0.26.1/Cython/Compiler/Code.c:94306:59: note: 
      silence by adding parentheses to mark code as explicitly dead
        module = PyImport_ImportModule((PY_VERSION_HEX >= 0x03030000) ? "collections.abc" : "collections");
                                                          ^
                                                          /* DISABLES CODE */ ( )
1 warning generated.

Installed /Users/taylorreiter/github/sourmash/.eggs/Cython-0.26.1-py3.6-macosx-10.12-x86_64.egg
error in sourmash setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Expected ',' or end-of-list in khmer>2.0<3.0 at <3.0
make: *** [all] Error 1
```

Other packages installed:
```
bz2file (0.98)
khmer (2.1)
pip (7.1.2)
screed (1.0)
setuptools (18.2)
wheel (0.24.0)
```

I can't figure out if I'm doing something wrong or if this is an actual error.

**Comment by ctb** [comment]
Try 'pip install -U setuptools' first -- does that work?

**Comment by taylorreiter** [comment]
No, approx same error:
```
pip install https://github.com/dib-lab/sourmash/archive/master.zip
Collecting https://github.com/dib-lab/sourmash/archive/master.zip
  Downloading https://github.com/dib-lab/sourmash/archive/master.zip (9.6MB)
    100% |████████████████████████████████| 9.6MB 50kB/s 
Exception:
Traceback (most recent call last):
  File "/Users/taylorreiter/Envs/sourmash-8-23-17/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2577, in _dep_map
    return self.__dep_map
  File "/Users/taylorreiter/Envs/sourmash-8-23-17/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2652, in __getattr__
    raise AttributeError(attr)
AttributeError: _Distribution__dep_map

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/taylorreiter/Envs/sourmash-8-23-17/lib/python3.6/site-packages/pip/basecommand.py", line 211, in main
    status = self.run(options, args)
  File "/Users/taylorreiter/Envs/sourmash-8-23-17/lib/python3.6/site-packages/pip/commands/install.py", line 305, in run
    wb.build(autobuilding=True)
  File "/Users/taylorreiter/Envs/sourmash-8-23-17/lib/python3.6/site-packages/pip/wheel.py", line 705, in build
    self.requirement_set.prepare_files(self.finder)
  File "/Users/taylorreiter/Envs/sourmash-8-23-17/lib/python3.6/site-packages/pip/req/req_set.py", line 334, in prepare_files
    functools.partial(self._prepare_file, finder))
  File "/Users/taylorreiter/Envs/sourmash-8-23-17/lib/python3.6/site-packages/pip/req/req_set.py", line 321, in _walk_req_to_install
    more_reqs = handler(req_to_install)
  File "/Users/taylorreiter/Envs/sourmash-8-23-17/lib/python3.6/site-packages/pip/req/req_set.py", line 561, in _prepare_file
    set(req_to_install.extras) - set(dist.extras)
  File "/Users/taylorreiter/Envs/sourmash-8-23-17/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2774, in extras
    return [dep for dep in self._dep_map if dep]
  File "/Users/taylorreiter/Envs/sourmash-8-23-17/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2591, in _dep_map
    dm.setdefault(extra,[]).extend(parse_requirements(reqs))
  File "/Users/taylorreiter/Envs/sourmash-8-23-17/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2924, in parse_requirements
    "version spec")
  File "/Users/taylorreiter/Envs/sourmash-8-23-17/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2900, in scan_list
    raise RequirementParseError(msg, line, "at", line[p:])
pip._vendor.pkg_resources.RequirementParseError: Expected ',' or end-of-list in khmer>2.0<3.0 at <3.0
```

**Comment by ctb** [comment]
ok, last try :) - can you try these intructions from
https://sourmash.readthedocs.io/en/latest/tutorials.html?

----

pip install -U pip
pip install -U Cython
pip install -U jupyter jupyter_client ipython pandas matplotlib scipy scikit-learn khmer

pip install https://github.com/dib-lab/sourmash/archive/master.zip

----


On Tue, Sep 05, 2017 at 05:45:58PM +0000, Taylor Reiter wrote:
> No, approx same error:
> ```
> pip install https://github.com/dib-lab/sourmash/archive/master.zip
> Collecting https://github.com/dib-lab/sourmash/archive/master.zip
>   Downloading https://github.com/dib-lab/sourmash/archive/master.zip (9.6MB)
>     100% |????????????????????????????????????????????????????????????????????????????????????????????????| 9.6MB 50kB/s 
> Exception:
> Traceback (most recent call last):
>   File "/Users/taylorreiter/Envs/sourmash-8-23-17/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2577, in _dep_map
>     return self.__dep_map
>   File "/Users/taylorreiter/Envs/sourmash-8-23-17/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2652, in __getattr__
>     raise AttributeError(attr)
> AttributeError: _Distribution__dep_map
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/Users/taylorreiter/Envs/sourmash-8-23-17/lib/python3.6/site-packages/pip/basecommand.py", line 211, in main
>     status = self.run(options, args)
>   File "/Users/taylorreiter/Envs/sourmash-8-23-17/lib/python3.6/site-packages/pip/commands/install.py", line 305, in run
>     wb.build(autobuilding=True)
>   File "/Users/taylorreiter/Envs/sourmash-8-23-17/lib/python3.6/site-packages/pip/wheel.py", line 705, in build
>     self.requirement_set.prepare_files(self.finder)
>   File "/Users/taylorreiter/Envs/sourmash-8-23-17/lib/python3.6/site-packages/pip/req/req_set.py", line 334, in prepare_files
>     functools.partial(self._prepare_file, finder))
>   File "/Users/taylorreiter/Envs/sourmash-8-23-17/lib/python3.6/site-packages/pip/req/req_set.py", line 321, in _walk_req_to_install
>     more_reqs = handler(req_to_install)
>   File "/Users/taylorreiter/Envs/sourmash-8-23-17/lib/python3.6/site-packages/pip/req/req_set.py", line 561, in _prepare_file
>     set(req_to_install.extras) - set(dist.extras)
>   File "/Users/taylorreiter/Envs/sourmash-8-23-17/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2774, in extras
>     return [dep for dep in self._dep_map if dep]
>   File "/Users/taylorreiter/Envs/sourmash-8-23-17/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2591, in _dep_map
>     dm.setdefault(extra,[]).extend(parse_requirements(reqs))
>   File "/Users/taylorreiter/Envs/sourmash-8-23-17/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2924, in parse_requirements
>     "version spec")
>   File "/Users/taylorreiter/Envs/sourmash-8-23-17/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2900, in scan_list
>     raise RequirementParseError(msg, line, "at", line[p:])
> pip._vendor.pkg_resources.RequirementParseError: Expected ',' or end-of-list in khmer>2.0<3.0 at <3.0
> ```
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/dib-lab/sourmash/issues/314#issuecomment-327252280
-- 
C. Titus Brown, ctbrown@ucdavis.edu

**Comment by taylorreiter** [comment]
Well. I should have harkened back to grade school when the cardinal rule was "follow the instructions" -- now successfully installed...thank you!

**Comment by ctb** [comment]
no, no, I still want to know what the problem was! Maybe an old version of
pip? Or Cython?

**Comment by taylorreiter** [comment]
I think not having Cython was the issue
