### ISSUE TITLE
need exactly one. Specify --ksize or --dna/--protein.

### ISSUE THREAD

**Issue by mw55309** [dib-lab/sourmash#317]
Hi

I am not sure exactly what this means.

I created a sig from reads using --scaled 10000 and -k 31

I then downloaded the k31 genbank database.

Now when I run:

```sh
 sourmash sbt_search genbank-k31.sbt.json AF-H4_S10_L001.sig -k 31
```

I get:

```sh
# running sourmash subcommand: sbt_search
When loading query from "AF-H4_S10_L001.sig"
2 signatures matching ksize and molecule type;
need exactly one. Specify --ksize or --dna/--protein.
```

What's happening?  Same thing with sbt_gather

Perhaps as importantly, what command *should* I be running to compare reads from a metagenome against GenBank?

Cheers
Mick

**Comment by ctb** [comment]
Hi Mick, this looks like an old version of sourmash, so I'm not sure what
bugs might be lurking. It looks correct to me, though.

In the new version:

sourmash search AF-H4_S10_L001.sig genbank-k31.sbt.json

should work.

It's possible that you are using an old version of sourmash with a new
version of the SBT, for example.

If you send me the .sig I can take a look at it to see if anything looks
weird.

best,
--titus

**Comment by ctb** [comment]
(if you just want to get it to work without doing anything else, the
only suggestion I have is to try adding '--dna' to the command)

**Comment by mw55309** [comment]
Hey Titus

Yeah we tried --dna and it didn't work

For the record, which installation instructions should we follow to get the latest stable version?  

Cheers
Mick

**Comment by ctb** [comment]
This tutorial:

https://sourmash.readthedocs.io/en/latest/tutorials.html

will install the latest master branch, which should be as stable as it gets
until we do a 2.0 release.

best,
--titus

**Comment by ctb** [comment]
Closing: I think the issue here was a version issue and should be resolved by installing the latest version.  Will be addressed by doing "unstable" releases (see #324), also.

**Comment by nick-youngblut** [comment]
I seem to be getting this same error with with `sourmash v2.0.0a2`:

Command:
```
sourmash gather -k 31 -o tests/output_amy/sourmash/bins_DASTool_sourmash.csv tests/output_amy/sourmash/bins_DASTool.sig  /ebio/abt3_projects/databases/sourmash/genbank-k31.sbt.json > tests/output_amy/sourmash/bins_DASTool_sourmash.txt 	
```

Output:
```
...sig loading 5
When loading query from "tests/output_amy/sourmash/bins_DASTool.sig"
6 signatures matching ksize and molecule type;
need exactly one. Specify --ksize or --dna/--protein.
```

Adding `--dna` doesn't help. If I run `sourmash compute` on individual metagenome bins, then everything seems to work, but with the 6 metagenome bins used for input with `sourmash compute`  in the example above, I get this error. 

Any ideas on what's going wrong?

**Comment by nick-youngblut** [comment]
Thanks for the quick response! I computed bins_DASTool.sig with the following:

```
sourmash compute --scaled 10000 -k 31 -o tests/output_amy/sourmash/bins_DASTool.sig tests/output_amy/bin_DASTool_bins/*.fa 
```

The input was 6 fasta-formated metagenome bins.

**Comment by ctb** [comment]
On Sat, Feb 10, 2018 at 02:52:03PM +0000, Nick Youngblut wrote:
> Thanks for the quick response! I computed bins_DASTool.sig with the following:
> 
> ```
> sourmash compute --scaled 10000 -k 31 -o tests/output_amy/sourmash/bins_DASTool.sig tests/output_amy/bin_DASTool_bins/*.fa 
> ```
> 
> The input was 6 fasta-formated metagenome bins.

OK! For now, I'd suggest just omitting the -o and it will produce 6 .fa.sig
files in the current directory; then run gather on each of those.

If you want to combine all six into one, you can either do

cat *.fa | sourmash compute - -o output.sig -k 31 --scaled 10000

or (I think)

sourmash compute *.fa --merged=someNameHere -o output.sig -k 31 --scaled 10000

-- I can check on that if you're interested but I'm on a loaner laptop right
now :)

**Comment by nick-youngblut** [comment]
Great! Yeah, I'm trying to avoid multiple input, multiple output commands, which complicates `snakemake` pipelines. 

I'll give the bin-file merging options a try. Will I still be able to differentiate the bins after merging, or will I just get a full list of taxonomic classifications for the entire merged set of bins?

**Comment by sapuizait** [comment]
hi - i m having the exact same problem when trying to classify multiple contigs all in a single file
commands;
$ sourmash sketch dna -p scaled=1000,k=31 ~/tmp/shitflies/W22_Bacteria.filtered.fasta --singleton
$ sourmash search W22_Bacteria.filtered.fasta.sig gtdb-rs207.genomic.k31.lca.json.gz 
$ sourmash search W22_Bacteria.filtered.fasta.sig gtdb-rs207.genomic.k31.lca.json.gz --dna

Output:
== This is sourmash version 4.7.0. ==
== Please cite Brown and Irber (2016), doi:10.21105/joss.00027. ==

select query k=31 automatically.
When loading query from 'W22_Bacteria.filtered.fasta.sig'
2311 signatures matching ksize and molecule type;
need exactly one. Specify --ksize or --dna, --rna, or --protein.

Is the solution to split in individual files and use gather? like mentioned above?
Thanks

**Comment by ctb** [comment]
yep! you can now use `sourmash sig split` to split many sketches into a directory full of files, or `sourmash sig cat <input> -o somedir.d/` as well.
