### ISSUE TITLE
Drop Python 2 once khmer 3.0 is released.

### ISSUE THREAD

**Issue by luizirber** [dib-lab/sourmash#318]
Since khmer is [dropping Python 2][0], no reason to support it here.

[0]: https://github.com/dib-lab/khmer/issues/1769

**Comment by luizirber** [comment]
(although we should restrict sourmash 2.0 to khmer 2.1.1, and only drop Py2 once khmer 3.0 is released).

**Comment by ctb** [comment]
ref #1033
