### ISSUE TITLE
segfault computing minhash sketches 

### ISSUE THREAD

**Issue by grgmncr** [dib-lab/sourmash#319]
Hello,

I've successfully generated signatures from a set of (filtered) RNA-seq samples. However, when I turn on  --track-abundance to sourmash compute I get the following error:

> setting num_hashes to 0 because --scaled is set
> computing signatures for files: ./0hpf.trimnoV.fq.gz
> Computing signature for ksizes: [31]
> Computing only DNA (and not protein) signatures.
> Computing a total of 1 signatures.
> Tracking abundance of input k-mers.
> ... reading sequences from ./0hpf.trimnoV.fq.gz
> ..../0hpf.trimnoV.fq.gz 2110000*** Error in `/home/ubuntu/py3/bin/python3.5': malloc(): memory corruption: 0x0000000001ffb140 ***
> Segmentation fault (core dumped)

I'm running on an m4.large AWS instance, Ubuntu Xenial (16.04.2)

**Comment by ctb** [comment]
I've been able to replicate this using a test data set  that's part of khmer --

```
% sourmash compute --track-abundance ~/dev/khmer/data/100k-filtered.fa  --scaled 1000 -f
setting num_hashes to 0 because --scaled is set
computing signatures for files: /Users/t/dev/khmer/data/100k-filtered.fa
Computing signature for ksizes: [21, 31, 51]
Computing only DNA (and not protein) signatures.
Computing a total of 3 signatures.
Tracking abundance of input k-mers.
... reading sequences from /Users/t/dev/khmer/data/100k-filtered.fa
.../Users/t/dev/khmer/data/100k-filtered.fa 70000python(17888,0x7fffcbb8f3c0) malloc: *** error for object 0x1031650a0: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
Abort trap: 6
```

**Comment by ctb** [comment]
@grgmncr thanks for reporting - this has now been fixed in the latest master! Let me know if you need help updating - should be:

```
pip install -U https://github.com/dib-lab/sourmash/archive/master.zip
```
