### ISSUE TITLE
Publish a pre-release on PyPI

### ISSUE THREAD

**Issue by luizirber** [dib-lab/sourmash#324]
The version we have on PyPI is 1.0, which lacks a lot of what is described in the docs in readthedocs. As a stopgap measure would be to publish an alpha release on PyPI, and change docs to use `pip install --pre sourmash` instead of the github URL.

**Comment by ctb** [comment]
Agreed. Let's get #390 and #393 merged, and then go for it. Maybe we can update version to 2.0b1 at that point?

**Comment by luizirber** [comment]
We are publishing pre-releases to PyPI since #504, so I'll say this is fixed.
