### ISSUE TITLE
We should convert some or all of the documentation over to markdown!

### ISSUE THREAD

**Issue by ctb** [dib-lab/sourmash#340]
ReStructuredText is increasingly painful to edit :)

**Comment by ctb** [comment]
note that markdown is supported within the docs already, so it's just a matter of renaming `.rst` files to `.md` and editing the headers and links.  And `index` needs to remain a `.rst` file so that the site is built properly.

**Comment by recursive-deletion** [comment]
I noticed that Markdown doesn't have a way to make toctrees, and some of the documents like `developer.rst` and `release.rst` aren't in `index.rst`, and rely on the toctree inside `more-info.rst` to be accessed on readthedocs.io. There is, however, a docutils bridge called `recommonmark` that can be used inside Sphinx, that would enable the use of reStructured text toctrees inside of a markdown document. Alternatively, i guess we could add the hidden files to the `index.rst` file (and get rid of toctrees in the documents), or keep the documentation as `.rst`. Let me know what you think I should try.

**Comment by ctb** [comment]
What we've done in other repos is:

* create a toc.rst that has all the files;
* make index.md be a front page without a toctree.

that seems to work ok.

**Comment by ctb** [comment]
Fixed in #356.
