### ISSUE TITLE
AssertionError when running sourmash-lca

### ISSUE THREAD

**Issue by mherold1** [dib-lab/sourmash#368]
When running `sourmash lca classify` based on this [tutorial](https://github.com/dib-lab/sourmash/blob/add/lca/doc/tutorials-lca.md) I get an AssertionError from the following line:

https://github.com/dib-lab/sourmash/blob/5e5f59ca1bfdbfc780ea19187ef96d84bf4bc5b4/sourmash_lib/lca/command_classify.py#L214
```
...
File ".../lib/python3.5/site-packages/sourmash_lib/lca/command_classify.py", line 214, in classify
    assert taxrank == rank, (taxrank, rank)
AssertionError: ('superkingdom', '')
```
When I change the assert statement to a "print error message", I get multiple of these error messages per genome that I want to classify, but overall it runs through. In some cases I see empty entries in the summary-results when using the `-d`option, but I think this is not related. 

output from running with `-d` option:
```
...
classifying mybin.fa
[((('superkingdom', 'Bacteria'),), 6),
 ((('superkingdom', 'Bacteria'), ('phylum', 'Bacteroidetes')), 5),
 ((), 3),
 ((('superkingdom', 'Bacteria'),
   ('phylum', 'Bacteroidetes'),
...
```

Overall I see many of my genomes (bins from metagenome samples) without a match, could this have something to do with the error?  
Also I am not quite sure how to select kmer size and threshold, but that is another issue.

**Comment by ctb** [comment]
ref #367. Thanks for reporting this! Do you have the exact command line you are using, perchance? I have some ideas but it'd be good to have that info.

**Comment by mherold1** [comment]
sure these are the commands that I ran: 
```
pyenv activate sourmashlca_venv

#from sigs_all/
sourmash compute -k 21,31,51 --scaled 1000 .../dereplicated_genomes/*.fa

THRESHOLD=5
KMER=31
sourmash lca classify -d --db ../db/genbank-k${KMER}.lca.json.gz \
        --threshold $THRESHOLD\
        --query ../sigs_all/*sig \
        -o classified_all.k${KMER}.${THRESHOLD}.csv \
        > classified_all.k${KMER}.${THRESHOLD}.debug_info
```

**Comment by ctb** [comment]
OK - thanks!

**Comment by ctb** [comment]
This *should* be fixed by d23fd676, which is in the latest add/lca branch of #367. Reinstalling sourmash with `pip install -U https://github.com/dib-lab/sourmash/archive/add/lca.zip` will get you the new version if you get a chance to try it out. Again, appreciate the report and please let us know about this or any further problems!

**Comment by ctb** [comment]
While I'm here, you asked about k-mer size guidance. I wrote something in #369 about that - please ask questions there!

**Comment by mherold1** [comment]
Tried it with the new version and the error does not show. I noticed in the output there are 2 kinds of empty items in the lists now:
```
[((), 1)]
[(' ', ' ')]
```
so I guess it had something to do with unassigned sequences?

thank you very much for the quick feedback and fixing the issue.

**Comment by ctb** [comment]
Yes, it had to do with empty taxonomic names. Thanks for reporting back!
