### ISSUE TITLE
latest premade database

### ISSUE THREAD

**Issue by phiweger** [dib-lab/sourmash#379]
when I download the database ` microbe-sbt-k21-2016-11-27.tar.gz` from Titus' [blog post](http://ivory.idyll.org/blog/2016-sourmash-sbt-more.html) it fails with the as-of-yesterday master branch of sourmash:

```bash
sourmash search --threshold 0.00001 --containment \
test.sig.json sbt/microbe-sbt-k21-2016-11-27/microbes.sbt.json

select query k=21 automatically.
loaded query: e6d891fc... (k=21, DNA)
Error in parsing signature; quitting.
Exception: Unexpected symbol 'class' at 0
Error in parsing signature; quitting.
Exception: local variable 'signatures' referenced before assignment
loaded 0 signatures and 0 databases total.
```

searching an SBT works if I construct the SBT index from scratch, so I guess there are new changes in sourmash that render the example databases incompatible?

1.

if so, are there "new" precomputed ones available?

2.

do you have a script that illustrates how you aggregated all those reference genomes? would love to learn how one can do this and stay sane :)

as always, thank you very much

**Comment by ctb** [comment]
Hi Adrian, try:

https://sourmash.readthedocs.io/en/latest/databases.html

best,
--titus

**Comment by phiweger** [comment]
that was instant, thanks!

**Comment by ctb** [comment]
:)

more in a bit on this issue - don't close!

**Comment by phiweger** [comment]
I tried

```bash
sourmash search --best-only --threshold 0.01 test_k21.sig.json sbt2/microbe-refseq-sbt-k21-2017.05.09/refseq-k21.sbt.json
```

but got

```python
sourmash_lib/sbtmh.py", line 127, in search
    raise Exception('cannot do similarity search on this SBT; need to rebuild.')
Exception: cannot do similarity search on this SBT; need to rebuild.
```

**Comment by phiweger** [comment]
```bash
sourmash gather --scaled 1000 test_k21.sig.json sbt2/microbe-refseq-sbt-k21-2017.05.09/refseq-k21.sbt.json
select query k=21 automatically.
loaded query: e6d891fc... (k=21, DNA)
downsampling query from scaled=50 to 1000
loaded 0 signatures and 1 databases total.


overlap     p_query p_match
---------   ------- --------
74.0 kbp      3.6%    1.4%      NZ_CCHY01000001.1 Klebsiella pneumoni...
```

yay, but wait ...

```
...
, line 146, in gather_databases
    notify('found less than {} in common. => exiting',
NameError: name 'notify' is not defined
```

**Comment by ctb** [comment]
<sob>

we do test this software. I promise. really. :)

**Comment by phiweger** [comment]
;) no problem

**Comment by ctb** [comment]
yep, this is in master branch all right.  gotta put in a test.

**Comment by cedwardson4** [comment]
Also got this error on the following command:
sourmash gather --k 31 --dna --scaled 2000 LH-1209-R1_reads.sig refseq-k31.sbt.json 

loaded query: LH-1209_S5_L001_R1_001_trimmed... (k=31, DNA)
downsampling query from scaled=2000 to 2000
loaded 0 signatures and 1 databases total.                                     


overlap     p_query p_match 
---------   ------- --------
120.0 kbp     0.1%    6.6%      NZ_CP011070.1 Candidatus Nitrosopumil...
70.0 kbp      0.0%    2.3%      NZ_MAKX01000001.1 Tenacibaculum solea...
58.0 kbp      0.0%    0.9%      NZ_KE387185.1 Aquimarina latercula DS...
56.0 kbp      0.0%    1.1%      NZ_BBZB01000001.1 Pseudoalteromonas s...
60.0 kbp      0.0%    1.2%      NZ_BDCW01000001.1 Tenacibaculum ovoly...
Traceback (most recent call last):
  File "/home/christian/py3/bin/sourmash", line 11, in <module>
    load_entry_point('sourmash==2.0.0a2', 'console_scripts', 'sourmash')()
  File "/home/christian/py3/lib/python3.5/site-packages/sourmash_lib/__main__.py", line 63, in main
    cmd(sys.argv[2:])
  File "/home/christian/py3/lib/python3.5/site-packages/sourmash_lib/commands.py", line 927, in gather
    args.threshold_bp):
  File "/home/christian/py3/lib/python3.5/site-packages/sourmash_lib/search.py", line 146, in gather_databases
    notify('found less than {} in common. => exiting',
NameError: name 'notify' is not defined

**Comment by standage** [comment]
@cedwardson4 This is a known issue (discussed in the last couple of days be @luizirber and @taylorreiter). Hopefully it should be a quick and straightforward fix. Stay tuned!

**Comment by standage** [comment]
The inimitable @luizirber just implemented a fix for the `notify` bug. If you update to the latest version of sourmash on Github this message should go away.

**Comment by luizirber** [comment]
😊

**Comment by brooksph** [comment]
I can confirm that the "notify" error is resolved but a new error popped up. 

Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/sourmash", line 9, in <module>
    load_entry_point('sourmash==2.0.0a2', 'console_scripts', 'sourmash')()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/sourmash_lib/__main__.py", line 63, in main
    cmd(sys.argv[2:])
  File "/home/ubuntu/.local/lib/python2.7/site-packages/sourmash_lib/commands.py", line 927, in gather
    args.threshold_bp):
  File "/home/ubuntu/.local/lib/python2.7/site-packages/sourmash_lib/search.py", line 147, in gather_databases
    format_bp(intersect_bp))
NameError: global name 'format_bp' is not defined

**Comment by nick-youngblut** [comment]
I just got this `notify` error when using the version available on `bioconda` (v2.0.0a2). I'm guessing that `bioconda` hasn't updated `sourmash` yet. Any idea on when this will happen?

**Comment by matrs** [comment]
Hey, I'm getting this error with the latest  `refseq-d2-k21.tar.gz` and `refseq-d2-k31.tar.gz`
I don't have other databases to try yet (my downloads are relatively slow).
- RefSeq k=21, 2018.03.29 - 7 GB
- RefSeq k=31, 2018.03.29 - 7 GB

`sourmash search Pseudomonas_mandelii_J2.fasta.sig ../Sourmash_dabases/refseq-d2-k31.tar.gz`

```
selecting default query k=31.
loaded query: pseudomonas_mandelii_12/Pseudo... (k=31, DNA)
Error in parsing signature; quitting.
Exception: Unexpected symbol 'refseq-d2-k21.sbt.json' at 0

Cannot open file '../Sourmash_dabases/refseq-d2-k21.tar.gz'
```
The above was in a en environment using python 3.6.6

I tried with a new environment following the documentation but still I get the same error
`conda create -n sourmash_env sourmash python=3.6.4`

Any hints?

**Comment by ctb** [comment]
Hi @matrs you need to unpack the database! We have approximate instructions in
the tutorial --

https://sourmash.readthedocs.io/en/latest/tutorials.html

best,
--titus

**Comment by matrs** [comment]
I just realized that (before seeing your answer) and I deleted my post, sorry !

**Comment by ctb** [comment]
no worries at all!
