### ISSUE TITLE
Output/extract signatures for matches 

### ISSUE THREAD

**Issue by brooksph** [dib-lab/sourmash#381]
It would be useful to write the matching hashes to a new file/signature. The hashes could be useful if the user wants to go from hashes to k-mers or reads. Also, hashes from gather matches could be used as a bin for input to sourmash LCA or other programs that aren't rank specific.

**Comment by ctb** [comment]
`--save-matches`  saves the matching signatures for both `search` and `gather`. But it seems you want the hashes. Perhaps rather than adding a command line option to search or gather, this could be postprocessing after you get the matching signatures with `--save-matches`.

**Comment by ctb** [comment]
Closing until we add some specific use cases that need a new command-line option.
