### ISSUE TITLE
sourmash/doc/tutorials-lca.md downloads lca db to odd location

### ISSUE THREAD

**Issue by taylorreiter** [dib-lab/sourmash#386]
Currently the [lca tutorial](https://github.com/dib-lab/sourmash/blob/47e2c31b2ab56ac5cf433f310a64828408000062/doc/tutorials-lca.md) downloads the lca db to `/tmp/genbank-k31.lca.json.gz`. This puts it in an unintuitive location, and is not congruent with what is referenced in the rest of the tutorial. Can if be downloaded to `genbank-k31.lca.json.gz` instead?

**Comment by luizirber** [comment]
Fixed by #388
