### ISSUE TITLE
update SBT and LCA databases for 2.0 compatibility

### ISSUE THREAD

**Issue by ctb** [dib-lab/sourmash#402]
'nuff said (?)

**Comment by phiweger** [comment]
any update on this issue? the precomputed indices are quite useful :)

**Comment by luizirber** [comment]
Hi @phiweger! I posted some updated indices, but I didn't test them properly yet. These are the links:
https://s3-us-west-2.amazonaws.com/sourmash-databases/genbank-d2-k21.tar.gz
https://s3-us-west-2.amazonaws.com/sourmash-databases/genbank-d2-k31.tar.gz
https://s3-us-west-2.amazonaws.com/sourmash-databases/genbank-d2-k51.tar.gz
https://s3-us-west-2.amazonaws.com/sourmash-databases/refseq-d2-k21.tar.gz
https://s3-us-west-2.amazonaws.com/sourmash-databases/refseq-d2-k31.tar.gz
https://s3-us-west-2.amazonaws.com/sourmash-databases/refseq-d2-k51.tar.gz

(and a longer discussion in this issue: https://github.com/dib-lab/sourmash/issues/464#issuecomment-384076867 )

**Comment by phiweger** [comment]
thank you! are they `--scaled 2000` as were the databases linked in the docs?

**Comment by luizirber** [comment]
yes, same config as the docs databases (and this is the snakemake workflow that generated them: https://github.com/luizirber/sourmash_databases/blob/master/Snakefile )

**Comment by ctb** [comment]
Done for LCA DBs as part of #537.
