### ISSUE TITLE
Precomputed SBT indices corrupted?

### ISSUE THREAD

**Issue by phiweger** [dib-lab/sourmash#411]
Hi,

I installed the master branch of sourmash yesterday, v2.0.0a3

I downloaded an index from [here](http://sourmash.readthedocs.io/en/latest/databases.html) and ran 

```
sourmash compute -f --scaled 2000 -k 31 assembly.fa -o assembly.sig
sourmash search assembly.sig 2017-05-09_sbt-refseq-k31/refseq-k31.sbt.json
```

sourmash then errs out with

```
    raise Exception('cannot do similarity search on this SBT; need to rebuild.')
Exception: cannot do similarity search on this SBT; need to rebuild.
```

Am I doing something wrong or it the SBT index not compatible w/ the current sourmash version?

Thanks!

**Comment by ctb** [comment]
You are correct - we need to rebuild the SBTs, after the merge of #244 and for the release of 2.0. (Briefly, 'sbt search' was always mildly buggy on those SBTs with a corner case of potentially missing certain matches; but now we know that :) Note. #405 also needs to be merged before we rebuild.  

#402 is the issue for rebuilding.

Sorry about this! Gather still works just fine... and `search --containment`...

**Comment by phiweger** [comment]
Ok, looking forward to 2.0, thanks.
