### ISSUE TITLE
Compilation/Installation

### ISSUE THREAD

**Issue by dnbaker** [dib-lab/sourmash#422]
Hi,

I'm attempting to use your tool to compare methods for genomic set operations. I've attempted installation two different ways:

1. Via conda, as recommended.
Using this method, the executable fails with `ImportError: /home-1/dbaker49@jhu.edu/work/db/env/anaconda3/lib/python3.5/site-packages/sourmash-2.0.0a2-py3.5-linux-x86_64.egg/sourmash_lib/_minhash.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _ZTINSt8ios_base7failureB5cxx11E`.

2. Via manual python setup.py install
Using this, the executable fails with `Traceback (most recent call last):
  File "sourmash/sourmash", line 4, in <module>
    from sourmash_lib.__main__ import main
  File "/scratch/groups/blangme2/db/code/sourmash/sourmash_lib/__init__.py", line 10, in <module>
    from ._minhash import (MinHash, get_minhash_default_seed, get_minhash_max_hash)
ImportError: No module named 'sourmash_lib._minhash'`.

I've recently stayed away from Cython-based tools for portability reasons myself (I would heartily recommend pybind11 for future projects, but that's not an easy port and I would hesitate to recommend it for this project.). Might you be able to point me in some directions? I'm working with `python -c 'import sys;print(sys.version_info)'` yielding `sys.version_info(major=3, minor=5, micro=3, releaselevel='final', serial=0)`, and gcc 7.1.0 for my compiler.

`uname -a` emits `Linux langmead-bigmem02 2.6.32-573.22.1.el6.x86_64 #1 SMP Wed Mar 23 03:35:39 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`.

**Comment by luizirber** [comment]
- The conda error seems to be related to C++ ABI differences (but I'm surprised they happen, because conda shouldn't be trying to load the system one, and should be trying to use it's own copy).
For reference, this is what I ran here to install sourmash with conda:
```bash
$ export PATH=~/miniconda3/bin:$PATH
$ conda create -n sourmash_env sourmash=2.0.0a3 python=3.6.4
$ source activate sourmash_env
$ sourmash compute -h
```
and we had someone reporting this before in #288 , so maybe one solution is to `conda install libgcc` in the conda env?

- Despite having a new GCC, seems like the kernel in this machine is very old? I wonder if this is related to similar issues we had in khmer:
https://github.com/dib-lab/khmer/issues/1580
https://github.com/dib-lab/khmer/issues/1368
https://github.com/dib-lab/khmer/issues/1387
(this was the solution... https://github.com/dib-lab/khmer/pull/1489)

- About the manual install, can you post the commands you ran? I'm surprised it is not finding the right dylib...

P.S: I tried to find where in the docs we recommend using conda and missed it, while I do use conda to deploy 'in production' I think it was never officially stated =P

**Comment by dnbaker** [comment]
Thanks for your quick response!

Sorry, it was pip you recommended. I ended up trying conda after that failed. (That time, it was an undefined out_of_range error. My mistake!)

But hooray! The virtualenv version works. I won't complain and I'll be happy to run with it as is. (To be honest, I would personally have appreciated that as an alternate installation method in the README.md, in case you might consider adding it as a fallback.)

Thanks!

**Comment by ctb** [comment]
hi @dnbaker, started a pull request in #423! When you say "the virtualenv version works" what do you mean? something like this?

```
python -m venv sourmash_env
source sourmash_env/bin/activate
pip install sourmash
```
?

**Comment by dnbaker** [comment]
I mean that I did, as above:
(After adding defaults/bioconda/linux distro channels, all of which were required to install)
```
conda create -n sourmash_env sourmash=2.0.0a3 python=3.6.4
source activate sourmash_env
```

By the way, while I'm at it, is there a way to get your distance matrix into a human-readable format? I've been able to produce pngs, but I tried unpickling the file and decompressing it and can't seem to figure out how to access it.

**Comment by ctb** [comment]
On Mon, Feb 26, 2018 at 05:24:09AM -0800, Daniel Baker wrote:
> I mean that I did, as above:
> (After adding defaults/bioconda/linux distro channels, all of which were required to install)
> ```
> conda create -n sourmash_env sourmash=2.0.0a3 python=3.6.4
> source activate sourmash_env
> ```

thanks!

> By the way, while I'm at it, is there a way to get your distance matrix into a human-readable format? I've been able to produce pngs, but I tried unpickling the file and decompressing it and can't seem to figure out how to access it.

it's a numpy matrix; try numpy.load?

--csv should output it in CSV format.

**Comment by dnbaker** [comment]
Great, thank you! I'll do so from the office once I get in. (As an aside, that matrix can get to be quite big when you submit tens of thousands of genomes. It's not much, but I've been using an upper-triangular matrix with implicit access functions to cut the memory requirement in half for comparing large numbers of genomes. I don't know if numpy supports this, but an array with custom accessors would work.)

**Comment by ctb** [comment]
On Mon, Feb 26, 2018 at 05:30:42AM -0800, Daniel Baker wrote:
> Great, thank you! I'll do so from the office once I get in. (As an aside, that matrix can get to be quite big when you submit tens of thousands of genomes. It's not much, but I've been using an upper-triangular matrix with implicit access functions to cut the memory requirement in half for comparing large numbers of genomes. I don't know if numpy supports this, but an array with custom accessors would work.)

I think numpy or scipy has support for various kind of sparse matrices.
It's "only" a linear factor of 1/2 tho so unless we specify some kind of
similarity cutoff below which we just specify similarities are left blank,
I don't expect too many savings.
