### ISSUE TITLE
revisit jupyter demo notebooks / binder stuff before 2.0 release

### ISSUE THREAD

**Issue by ctb** [dib-lab/sourmash#430]
haven't run 'em in a while

**Comment by ctb** [comment]
* run them
* list them somewhere
* think about what notebooks make sense to have
* binderize them

**Comment by standage** [comment]
I see a notebook in `demo/`. I assume there's more? Where might a new contributor find these? :-)

**Comment by standage** [comment]
Note that `index.ipynb` is simply a link to `demo/00-demo.ipynb`. :-)
