### ISSUE TITLE
Demo notebook: issue parsing signatures

### ISSUE THREAD

**Issue by standage** [dib-lab/sourmash#438]
I'm getting a bunch of errors like the following when I execute cell 3 of `demo/00-demo.ipynb`.

```
loading SRR2060939_1.fastq.gz.sig
Error in parsing signature; quitting.
Exception: Unexpected symbol 'class' at 0

warning: no signatures loaded at given ksize/molecule type from SRR2060939_1.fastq.gz.sig
```

Probably these signature files were produced with an older version of sourmash and are now incompatible with the current parsing code?

**Comment by ctb** [comment]
`demo/` directory removed in https://github.com/dib-lab/sourmash/pull/631.
