### ISSUE TITLE
error in gather

### ISSUE THREAD

**Issue by taylorreiter** [dib-lab/sourmash#442]
I keep getting an error when I try and run `sourmash gather`:

```
Error in parsing signature; quitting.
Exception: 

Cannot open file 'fungi-k21.sbt.json'
```

I have tried many different sbts, and the error happens when the sbt was indexed using sourmash 2.0.0a4, but not 2.0.0a2 (installed from conda). 

The sbt is there, as well as the hidden folder.

**Comment by ctb** [comment]
might be #312. Can you send me the `fungi-k21.sbt.json` file?

**Comment by taylorreiter** [comment]
https://drive.google.com/file/d/1XbpfJkO0Xtw6cRtgHK1WtuHO7TwZOPgG/view?usp=sharing

**Comment by ctb** [comment]
just the .sbt.json file, please

**Comment by taylorreiter** [comment]
[fungi-k21.sbt.json.txt](https://github.com/dib-lab/sourmash/files/1799541/fungi-k21.sbt.json.txt)

**Comment by ctb** [comment]
Running `jq . < fungi-k21.sbt.json.txt` I see,

```
  "storage": {
    "backend": "FSStorage",
    "args": {
      "path": "/home/euk_sbts/euk_sbts/trees/fungi/.sbt.fungi-k21"
    }
  },
```

which makes me think that perhaps it is caused by #312. For now, you might need to rebuild the SBT in each place where you want to use it...

**Comment by taylorreiter** [comment]
Oih. Okey dokey can do thank you!
