### ISSUE TITLE
update authors in setup.py etc.

### ISSUE THREAD

**Issue by ctb** [dib-lab/sourmash#444]
right now it's just me!

**Comment by luizirber** [comment]
Related: #674

**Comment by ctb** [comment]
related: #622

**Comment by ctb** [comment]
#622 ref

**Comment by ctb** [comment]
a thought and question -

- do we put just the maintainers in the authors section for pypi, or do we limit it to core maintainers, and if so, who? I could go either way; main operational question is, what downsides are there for large numbers of authors in pypi?
- we should do a JOSS update for 4.0. I'm thinking that submission can wait until 4.0 is officially released, and then we can do what we did for 2.0 and release a 2.0.x with updates from the JOSS review.

**Comment by ctb** [comment]
as of today, rev 47a294b9c9
```
git shortlog --summary --numbered v3.0.0..
    87  C. Titus Brown
    57  Luiz Irber
     6  Erik Young
     3  dependabot-preview[bot]
     3  Tessa Pierce
     2  Daniel Standage
     1  Fabian Klötzl
     1  Olga Botvinnik
     1  Ivan Ogasawara
```

**Comment by ctb** [comment]
I think this accurately reflects the idea that the maintainers are me and luiz. So the question is, do we want to list everyone, or just the maintainers, in setup.cfg/pypi?

**Comment by ctb** [comment]
Hot take, since pypi has separate authors and maintainers, we should provide opt-in so that any code base contributor can choose to be listed as an author, while keeping luiz and myself as the maintainers.

we would then make the blanket offer to all contributors and add them into setup.py as they respond positively.
