### ISSUE TITLE
recommonmark issue with testing in fresh install

### ISSUE THREAD

**Issue by halexand** [dib-lab/sourmash#450]
I installed a branch locally with `make install` inside of a clean environment. I then got the following error when I ran `make test`: 

> ImportError while importing test module '/Users/halexand/Projects/sourmash/doc/conf.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
doc/conf.py:297: in <module>
    from recommonmark.parser import CommonMarkParser
E   ModuleNotFoundError: No module named 'recommonmark'

It would appear that `recommonmark` is listed as a dependency in `requirements.txt` but not in `setup.py`.

**Comment by ctb** [comment]
Fixed in #452.
