### ISSUE TITLE
Sourmash databases with k=4,5

### ISSUE THREAD

**Issue by domenico-simone** [dib-lab/sourmash#457]
Hello,

I am interested in using sourmash to analyze kmer content in microbial genomes. I understand from [here](http://sourmash.readthedocs.io/en/latest/databases.html) that there are available databases for k=21,31,51. I also see the command line for k=4,5 though. Are these dbs actually available?

Thanks!

Domenico

**Comment by ctb** [comment]
A few responses, over two years later -- sorry :(

We don't provide pre-baked ksize 4,5 databases for genbank currently, and I don't expect this to change. I haven't built them in a while...

We do provide scripts to compute them, here: https://github.com/dib-lab/sourmash_databases.
