### ISSUE TITLE
Create multi-k signatures within python

### ISSUE THREAD

**Issue by domenico-simone** [dib-lab/sourmash#466]
Hello,

I am following [this guide](http://sourmash.readthedocs.io/en/latest/api-example.html) to create signatures within python, rather than running the scripts. Since I understand I can't feed the `sourmash.MinHash` command with multiple kmer sizes, what is the best way to create multi-k signatures, ie recreate this command?

```
sourmash compute \
    -k 1,2,3,4,5 \
    -n 2000 \
    --track-abundance \
    --name-from-first \
    -o genome.sig \
    genome
```

Thanks,

Domenico

**Comment by ctb** [comment]
Hey Domenico, good question --

the key info is in sourmash/signature_json.py, save_signature_json, where
it aggregates SourmashSignature records based on (name, filename).

So, create multiple SourmashSignature objects like so:

name='foo'
filename='bar'

siglist = []
siglist.append(SourmashSignature(minhash1, name=name, filename=bar))
siglist.append(SourmashSignature(minhash2, name=name, filename=bar))
siglist.append(SourmashSignature(minhash3, name=name, filename=bar))

and then do

with open('output.sig', 'wt') as outfp:
   signature.save_siglist(siglist, outfp)

-- haven't had a chance to test it, but report back if it doesn't work
and I will dig!

**Comment by domenico-simone** [comment]
Hi Titus,

many thanks for your suggestion!!! It worked fine, except for the `signature.save_siglist` function, which actually is `signature.save_signature`. Should it be useful, here's the whole code snippet I used:

```python
import sourmash, glob, os, screed
from sourmash import signature, SourmashSignature

# iterate over MAG files
MAGfiles = glob.glob("*.fa")

# create output dir
try:
    os.mkdir("data/genome_signatures_MAG/")
except:
    pass

MAG_minhashes = []
for MAGfile in MAGfiles:
    name = os.path.splitext(MAGfile)[0]
    print name
    MAG_minhashes = []
    # generate signature for each MAG
    E1 = sourmash.MinHash(n=2000, ksize=1, track_abundance=True)
    E2 = sourmash.MinHash(n=2000, ksize=2, track_abundance=True)
    E3 = sourmash.MinHash(n=2000, ksize=3, track_abundance=True)
    E4 = sourmash.MinHash(n=2000, ksize=4, track_abundance=True)
    E5 = sourmash.MinHash(n=2000, ksize=5, track_abundance=True)
    MAGseqhandle = screed.open(MAGfile)
    for contig in MAGseqhandle:
        sampleName = MAGfile.split('/')[-2]
        # generate signature for each contig
        E1.add_sequence(contig.sequence, True)
        E2.add_sequence(contig.sequence, True)
        E3.add_sequence(contig.sequence, True)
        E4.add_sequence(contig.sequence, True)
        E5.add_sequence(contig.sequence, True)
    MAG_minhashes.append(SourmashSignature(E1, name=name, filename=name))
    MAG_minhashes.append(SourmashSignature(E2, name=name, filename=name))
    MAG_minhashes.append(SourmashSignature(E3, name=name, filename=name))
    MAG_minhashes.append(SourmashSignature(E4, name=name, filename=name))
    MAG_minhashes.append(SourmashSignature(E5, name=name, filename=name))
    with open('data/genome_signatures_MAG/%s.sig' % name, 'wt') as outfp:
        signature.save_signatures(MAG_minhashes, outfp)
```

Best,

Domenico

**Comment by ctb** [comment]
thank you! I will add this to our API docs.

Apologies for mistake, I should know better than to free-type python code
without running it :)

**Comment by domenico-simone** [comment]
Awesome! I'm happy to contribute!
