### ISSUE TITLE
To plot with the "sourmash lca gather" output-file

### ISSUE THREAD

**Issue by superhu0** [dib-lab/sourmash#470]
Hi
I used sourmash lca gather command to get a **.csv file, is there any software to plot with this csv file?
for instance if want to get the heatmap of bacteria in phylum, what should I do?
thanks
HU

**Comment by ctb** [comment]
Hi HU,

see

http://ivory.idyll.org/blog/2017-taxonomy-of-tara-ocean-genomes.html

http://ivory.idyll.org/blog/2017-classify-genome-bins-with-custom-db-part-1.html

- I personally like metacodeR, but there are lots of other taxonomic display
packages out there.

**Comment by superhu0** [comment]
Thanks for your reply, I am going to learn it.
