### ISSUE TITLE
Add outdir flag to compute? 

### ISSUE THREAD

**Issue by halexand** [dib-lab/sourmash#472]
While working on getting sourmash working in the Qiime 2 environment @jiarong and I discovered that it would be useful to have a flag (e.g. `--outdir`) to direct the output signatures to a directory separate from the input fasta files without putting them all into the same file (like `--output`). 

It is possible we just missed the flag.

**Comment by ctb** [comment]
I was going to take this on, but I'll wait for the refactoring in #845 :)

**Comment by ctb** [comment]
Working on this in #935
