### ISSUE TITLE
`--track-abundance` & gather 

### ISSUE THREAD

**Issue by taylorreiter** [dib-lab/sourmash#476]
As I understand it, `gather` allows `--track-abundance`, however because the SBT is not calculated with `--track-abundance`, this may lead to unexpected results in a metagenome context. 

For example, if a 31-mer `A` occurs 10 times in genome 1, and a 31-mer 'A' occurs 1 time in genome 2, this would obscure genome abundance information. 

CC @luizirber; bloom filter's don't support `--track-abundance`. Count graph in khmer supports this, but unclear what to save from sigs (sum abundance as progressing to root doesn't make sense). 

Just wanted to keep track of these thoughts!

**Comment by ctb** [comment]
On Thu, May 24, 2018 at 03:28:15PM -0700, Taylor Reiter wrote:
> As I understand it, `gather` allows `--track-abundance`, however because the SBT is not calculated with `--track-abundance`, this may lead to unexpected results in a metagenome context. 
> 
> For example, if a 31-mer `A` occurs 10 times in genome 1, and a 31-mer 'A' occurs 1 time in genome 2, this would obscure genome abundance information. 
> 
> CC @luizirber; bloom filter's don't support `--track-abundance`. Count graph in khmer supports this, but unclear what to save from sigs (sum abundance as progressing to root doesn't make sense). 
> 
> Just wanted to keep track of these thoughts! 

Yep. I put some thought into this back when, and concluded:

* there's relatively little in the way of repetitive sequence in bacterial genomes;
* SBT search would be much more complicated with track-abundance;
* gather would be much more complicated if we had to deal with abundance in database we were searching;

so I decided not to implement.
