### ISSUE TITLE
unable to load python API

### ISSUE THREAD

**Issue by phiweger** [dib-lab/sourmash#481]
With the sourmash conda install, within the `sourmash_env` environment, I cannot access the sourmash Python API:

```python
import sourmash
ModuleNotFoundError: No module named 'sourmash'
import sourmash_lib  # deprecated?
ModuleNotFoundError: No module named 'sourmash_lib'
```

The command line tool works, but I need the API.

So I turn to the `master.zip`:

```bash
wget https://github.com/dib-lab/sourmash/archive/master.zip
# unzip
cd sourmash-master
ipython
```

```python
import sourmash
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-3cf8786de47c> in <module>()
----> 1 import sourmash

.../src/sourmash-master/sourmash/__init__.py in <module>()
      8 import os
      9
---> 10 from ._minhash import (MinHash, get_minhash_default_seed, get_minhash_max_hash)
     11 DEFAULT_SEED = get_minhash_default_seed()
     12 MAX_HASH = get_minhash_max_hash()
```

Indeed, ` ._minhash` is missing.

What is currently the recommended way to install sourmash to gain access to its Python API? 

Thanks!

**Comment by luizirber** [comment]
How did you install your conda environment? I did
```
$ conda create -n sourmash_env sourmash=2.0.0a6
$ source activate sourmash_env
$ python  
Python 3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:14:56) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sourmash  # works
>>> import sourmash_lib  # works too, but don't use it =]
```

Since sourmash is not pure-python, you can't unzip and try to import it. You need to compile the `_minhash` extension (it's the Cython/C++ code). `pip` will do that for you:
```
$ wget https://github.com/dib-lab/sourmash/archive/master.zip
$ pip install master.zip
# you can also do it in one step: 
$ pip install https://github.com/dib-lab/sourmash/archive/master.zip
```

**Comment by phiweger** [comment]
I installed sourmash using the instructions in the github README.

```bash
conda create -n sourmash_env sourmash python=3.6.4
```

Removing `sourmash_env` and trying what you suggested:

```bash
conda create -n sourmash_env sourmash=2.0.0a6
conda activate sourmash_env && ipython
```

```python
import sourmash
# ModuleNotFoundError: No module named 'ijson'
# exit ipython, pip install ijson, enter python

import sourmash
# ModuleNotFoundError: No module named 'sourmash'
```

**Comment by phiweger** [comment]
Solved: using ipython, because it was not installed in the conda env, the fallback is the root ipython, which does not know about the env installation and paths of sourmash. pip installing ipython in the env solves the problem. Sorry to bother. 

Still, I would like to install sourmash w/o conda, i.e. compile the binaries locally, but #474 prevents this somehow.

Anyway, thank you for your quick response!

**Comment by ctb** [comment]
hi @phiweger so something like `conda create -n sourmash_env sourmash=2.0.0a6 ipython` would probably have worked?
