### ISSUE TITLE
Create migrations from older index versions

### ISSUE THREAD

**Issue by luizirber** [dib-lab/sourmash#488]
Create a migrate command (ou use convert?), and only load the latest DB version available (right now it tries to be clever and load any older version, which might take a long time depending on what needs to be set)

**Comment by ctb** [comment]
I like migrate

**Comment by luizirber** [comment]
For migrating from old to new versions we don't need to rebuild the tree structure, mostly it's about fixing the JSON.

For converting from one storage to another we might need to touch the data (hidden dirs to TarStorage, for example)

Right now the tree structure is not terribly important, but at some point it might (thinking about clustering similar leaves under the same internal node, for example). Another issue with the 'iterating over all the leaves' is rebuilding all the internal nodes when it's not really necessary to do it.

**Comment by luizirber** [comment]
Fixed by #494
