### ISSUE TITLE
What are the right cmd line option for computing both protein and DNA?

### ISSUE THREAD

**Issue by ctb** [dib-lab/sourmash#51]
Right now, --protein switches 'sourmash compute' over to computing only protein MinHashes. It would be nice to read the sequence *once*, and compute both protein and DNA signatures at the same time.

The functionality to store the protein/DNA signatures in a single .sig file is there, although it's a bit untested.

First thought -- provide a '--dna' boolean flag, and change the '--protein' flag to be bool as well.
Then change '--protein' to no longer "turn off" DNA sketch computation.

One other thought, in the command line tool we should be really clear about how many signatures we're computing!

**Comment by ctb** [comment]
This has been resolved by some PR that got merged in the last month :)

**Comment by lgautier** [comment]
Crashing the comment party (too) late.

An interface that is a comma-separated list of what to compute is sometimes observed (as is done for the k-mer size here). A command-line call could then look like:

```python

sourmash compute --what=protein,dna,rna

```
