### ISSUE TITLE
sourmash search does not downsample to match query 

### ISSUE THREAD

**Issue by brooksph** [dib-lab/sourmash#510]
I'm using sourmash verion 2.0.0a8 installed with anaconda. I ran the following commands to calculate a signature and and create a database from a set of signatures: 
```
sourmash compute --scaled 10000 -k 31 ~/data/ecoliMG1655.fa.gz -o ecoli-genome.sig
sourmash search ecoli-genome.sig ecolidb.sbt.json -n 20
```
The scaled value for the ecoli.sbt.json is 2000 and sourmash search returns: 
```
select query k=31 automatically.
loaded query: /home/diblions/data/ecoliMG165... (k=31, DNA)
for tree 'ecolidb.sbt.json', scaled value is smaller than query.
tree scaled: 2000; query scaled: 10000. Cannot do similarity search.
```
Calculating the signatures with a scaled of 2000 resolves the issue.

**Comment by ctb** [comment]
Yes, unfortunately it is impossible to downsample SBTs. See: https://github.com/dib-lab/sourmash/issues/407
