### ISSUE TITLE
is there a bug in sourmash lca gather's `p_match` output?

### ISSUE THREAD

**Issue by ctb** [dib-lab/sourmash#512]
this is an issue for @ctb to fix, because he wrote that code.

**Comment by charlesreid1** [comment]
"Percent match" is printed here: https://github.com/dib-lab/sourmash/blob/41ad6b9a32e6fe49527ffc90b3ab281c36c14d57/sourmash/lca/command_gather.py#L227

This prints the quantity `result.f_match`

`f_match` is defined here: https://github.com/dib-lab/sourmash/blob/c5791ccd9ae5b0ad4ec48bfca91ea2d23eada09c/sourmash/search.py#L186

```
f_match = len(intersect_mins) / float(genome_n_mins)
```

`genome_n_mins` is number of minhashes (I think that's what "mins" means?) in the genome, so I would infer this is the ratio of k-mers that were in the query to k-mers that were in the genome.

**Comment by ctb** [comment]
the results for the ecoli genome in https://angus.readthedocs.io/en/2018/sourmash.html make it seem like there is a bug in the value being output.

**Comment by ctb** [comment]
this is fixed with v2 LCAs (https://osf.io/4f8n3) and sourmash 3.x.

**Comment by ctb** [comment]
```$ sourmash lca gather ecoli-genome.sig genbank-k31.lca.json.gz

== This is sourmash version 3.1.0. ==
== Please cite Brown and Irber (2016), doi:10.21105/joss.00027. ==

loaded 1 LCA databases. ksize=31, scaled=10000
selecting specified query k=31
loaded query: ecoliMG1655.fa.gz... (k=31)

overlap     p_query p_match 
---------   ------- --------
4.9 Mbp     100.0%  100.0%      Escherichia coli (** 9 equal matches)

Query is completely assigned.
```
