### ISSUE TITLE
Am I using/ interpreting gather correctly?

### ISSUE THREAD

**Issue by phiweger** [dib-lab/sourmash#524]
Dear all,

I analysed an isolate and suspect a contamination, i.e. I suspect that besides my "intended" strain Klebsiella pneumoniae ST258 there is another one present (ST101).

So I ran `sourmash gather -k 51 --scaled 100 ...` on (1) the isolate assembly (w/ `MEGAHIT`) and (2) the raw reads.

My results:

(1) assembly

```
overlap     p_query p_match
---------   ------- -------
5.2 Mbp       80.0%   95.2%    ST101.fasta
4.7 Mbp       17.1%   19.6%    ST258.fasta
```

Question 1: Is it correct to state that covering about 5.2 Mbp of ST101, 80% of the query's k-mers match 95.2% of the ST101 k-mers? 

Also, when I modify the analysis -- this time hashing the raw reads w/o assembly -- I get very different results:

(2) raw reads (after `trim-low-abund.py -C5 ...` -- w/o abundance trimming the order stays the same)

```
overlap     p_query p_match
---------   ------- -------
5.5 Mbp       74.5%   98.2%    ST258.fasta
5.3 Mbp       22.6%   30.9%    ST101.fasta
```

Question 2: Does this mean the assembly mainly recovers strain ST101 in a chimeric assembly (somewhat as described in [Awad et al.](https://www.biorxiv.org/content/early/2017/07/03/155358)) but the raw reads indicate that there is actually more ST258 than ST101?

Thank you very much.

**Comment by ctb** [comment]
hi @phiweger apologies for ignoring this for so long.

answer to q1: yes.

answer to q2: I am puzzled by the results at first glance :) :(. Rather than trying to figure it out based on the information above, I would probably use 'sourmash signature overlap' to analyze this further. Happy to help out if you still have any of these files around...?
