### ISSUE TITLE
Sourmash gather returns results whereas search returns nothing

### ISSUE THREAD

**Issue by mw55309** [dib-lab/sourmash#526]
Sorry if this is a dumb question, maybe I am mis-interpreting the functions.

I have a genome (not reads, the genome).  For the purposes of this test, I am using ecoli, so I have ecoli.fa and ecoli.sig.  I am using the signature to search against the genbank database you offer for download.

I am back on version 2.0.0a6 because if I upgrade to 2.0.0a9 I have to migrate the index ;-)

sourmash gather produces results:

```
sourmash gather sourmash/ecoli.sig ../genbank-d2-k31.sbt.json --scaled 1000 -o ecoli.gather 

overlap     p_query p_match
---------   ------- --------
4.5 Mbp     100.0%  100.0%      CP011320.1 Escherichia coli strain SQ...

found 1 matches total;
the recovered matches hit 100.0% of the query

```

And sourmash search does not:

```
sourmash search sourmash/ecoli.sig ../genbank-d2-k31.sbt.json --scaled 1000 -o ecoli.search

0 matches:
similarity   match
----------   -----

```

Is this expected?  If so, why?  What am I mis-understanding?

Cheers
Mick

**Comment by ctb** [comment]
Sorry for delay in response - this is hopefully the bug we fixed in #484. If you get a chance to test, please do!
