### ISSUE TITLE
update docs to conda install?

### ISSUE THREAD

**Issue by taylorreiter** [dib-lab/sourmash#552]
Should we update the sourmash tutorial documentation to use conda? Currently recommended install can be found here: https://github.com/dib-lab/sourmash/blob/master/doc/tutorials.md

**Comment by luizirber** [comment]
I think `pip` is fine, but we should recommend using `pip install --pre sourmash` instead of pointing to the master branch (`pip install -U https://github.com/dib-lab/sourmash/archive/master.zip`)

**Comment by taylorreiter** [comment]
I like how conda takes care of dependencies though, esp if someone isn't using a blank ubuntu image. Maybe we could have both?

**Comment by ctb** [comment]
Changed in #631. It's just easier to use conda on a blank system!

**Comment by ctb** [comment]
This should be done now, with #631 & #592.
