### ISSUE TITLE
updating the sbt database

### ISSUE THREAD

**Issue by mytluo** [dib-lab/sourmash#555]
hello again,

apologies if this has been written somewhere, but may I ask what the proper steps are to update the sbt (and lca) databases? this is what I did, which may be completely wrong -- 

- download new prokaryotic genome sequences from RefSeq as a .fasta file (as one file)
- run `sourmash compute` with the parameters stated in the `Prepared search databases` section of the documentation
- run `sourmash index` on the resultant signature file
- run `sourmash sbt_combine` with the refseq.sbt.json file and the sbt.json file created from the previous step

last step gave me this error:
```
Traceback (most recent call last):
  File "/home/ubuntu/py3/bin/sourmash", line 9, in <module>
    load_entry_point('sourmash==2.0.0a9', 'console_scripts', 'sourmash')()
  File "/home/ubuntu/py3/lib/python3.5/site-packages/sourmash/__main__.py", line 77, in main
    cmd(sys.argv[2:])
  File "/home/ubuntu/py3/lib/python3.5/site-packages/sourmash/commands.py", line 621, in sbt_combine
    tree.combine(new_tree)
  File "/home/ubuntu/py3/lib/python3.5/site-packages/sourmash/sbt.py", line 725, in combine
    smaller.nodes[0].update(n)
  File "/home/ubuntu/py3/lib/python3.5/site-packages/sourmash/sbt.py", line 810, in update
    parent.data.update(self.data)
ValueError: both nodegraphs must have same table sizes
```
I'm sure I'm doing something wrong, but I'm not sure what :(

**Comment by luizirber** [comment]
Hi @mytluo!

> apologies if this has been written somewhere, but may I ask what the proper steps are to update the sbt (and lca) databases? this is what I did, which may be completely wrong --

Not your fault, it's not well documented... I will open a PR with the results of this issue, but I would recommend:

 
>     * download new prokaryotic genome sequences from RefSeq as a .fasta file (as one file)
> 
>     * run `sourmash compute` with the parameters stated in the `Prepared search databases` section of the documentation

On top of using the same parameters, you also need `--singleton` since you only have one file and each sequence is a full genome. If there is more than one sequence per genome, then downloading everything as one file is not going to work wel...

>     * run `sourmash index` on the resultant signature file

`sourmash index` has an ` --append` flag, where instead of creating a new index you can add new signatures to an existing index. I think it's more appropriate for this use case.
 
>     * run `sourmash sbt_combine` with the refseq.sbt.json file and the sbt.json file created from the previous step
>
> last step gave me this error:
> 
> ```
> Traceback (most recent call last):
>   File "/home/ubuntu/py3/bin/sourmash", line 9, in <module>
>     load_entry_point('sourmash==2.0.0a9', 'console_scripts', 'sourmash')()
>   File "/home/ubuntu/py3/lib/python3.5/site-packages/sourmash/__main__.py", line 77, in main
>     cmd(sys.argv[2:])
>   File "/home/ubuntu/py3/lib/python3.5/site-packages/sourmash/commands.py", line 621, in sbt_combine
>     tree.combine(new_tree)
>   File "/home/ubuntu/py3/lib/python3.5/site-packages/sourmash/sbt.py", line 725, in combine
>     smaller.nodes[0].update(n)
>   File "/home/ubuntu/py3/lib/python3.5/site-packages/sourmash/sbt.py", line 810, in update
>     parent.data.update(self.data)
> ValueError: both nodegraphs must have same table sizes
> ```

This one happens because the new index you build with `sourmash index` in the previous step probably have a different internal node size (the default is `-x 1e5`, but we use `-x 1e6` for the GenBank/RefSeq databases we provide).
 
That said, I'm going to test if what I recommend works, especially the `sourmash compute` suggestion...

**Comment by mytluo** [comment]
Hi @luizirber! Thank you for the reply! I did mess up downloading the new genomes (they were proteins rather than complete genomes), so I redownloaded some new (archaea) genomes (14 total) and generated 14 separate signature files and tried running `sourmash index` with the `--append` flag, which then generates this error:

```loading 1 files into SBT
Traceback (most recent call last):
  File "/home/ubuntu/py3/bin/sourmash", line 9, in <module>
    load_entry_point('sourmash==2.0.0a9', 'console_scripts', 'sourmash')()
  File "/home/ubuntu/py3/lib/python3.5/site-packages/sourmash/__main__.py", line 77, in main
    cmd(sys.argv[2:])
  File "/home/ubuntu/py3/lib/python3.5/site-packages/sourmash/commands.py", line 693, in index
    tree.add_node(leaf)
  File "/home/ubuntu/py3/lib/python3.5/site-packages/sourmash/sbt.py", line 164, in add_node
    child.update(n)
  File "/home/ubuntu/py3/lib/python3.5/site-packages/sourmash/sbtmh.py", line 57, in update
    for v in self.data.minhash.get_mins():
  File "/home/ubuntu/py3/lib/python3.5/site-packages/sourmash/sbtmh.py", line 71, in data
    buf = BytesIO(self.storage.load(self._path))
  File "/home/ubuntu/py3/lib/python3.5/site-packages/sourmash/sbt_storage.py", line 53, in load
    with open(os.path.join(self.location, self.subdir, path), 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/sbt/.sbt.refseq-d2-k51/9fed447daa6cf4a5da91f66868c600ab'```

my commands:
```$ sourmash compute -k 51 --scaled 2000 --track-abundance --name-from-first ~/ncbi-genomes-2018-10-08/*.fna.gz
$ sourmash index -k 51 --append refseq-d2-k51.sbt.json -x 1e6 archaea_oct2018 archaea/*.sig
$ sourmash index -k 51 -x 1e6 --append refseq-d2-k51.sbt.json archaea/*.sig```
I also tried:
`sourmash compute -k 51 --scaled 2000 --track-abundance --name-from-first --merge ~/ncbi-genomes-2018-10-08/*.fna.gz -o archaea_oct2018.sig`
to get just one .sig file, but same `FileNotFoundError`. 

then I tried running `sourmash index` without `--append` --
```$ sourmash index -k 51 -x 1e6 --traverse-directory archaea/ archaea_oct2018 archaea/*.sig
$ sourmash sbt_combine -x 1e6 testupdate refseq-d2-k51.sbt.json archaea/.sbt.json ```

and that seems to work! I must be using the `--append` flag incorrectly... could you show me the accurate syntax?

**Comment by mytluo** [comment]
@luizirber -- just tried the `sourmash index` again with the `--append` flag and it seems to work! not sure what I did differently ^^;; but thank you!! I would like to test the updated database later but it looks pretty good so far :)

**Comment by mytluo** [comment]
@luizirber thank you so much!! `sourmash index -x 1e6 --append` works perfectly 👍may I ask if there is a similar method for the `LCA` database as well? I'm reading through https://github.com/dib-lab/2018-ncbi-lineages and it seems to be mainly building LCA databases from scratch.

**Comment by luizirber** [comment]
@mytluo there isn't a `--append` flag for LCA databases, but it's doable. Right now you need to regenerate the database from scratch =/

**Comment by ctb** [comment]
Extracted remaining issue into to #849.
