### ISSUE TITLE
ValueError: invalid DNA character in sequence: N

### ISSUE THREAD

**Issue by dchandran** [dib-lab/sourmash#558]
Many genomic fasta files in genbank have N in the sequences, and for these sequences, I am getting the "ValueError: invalid DNA character in sequence: N" error when using "sourmash compute". We would like to build signature files automatically from genbank genomes; since sourmash does not allow N in the sequence, this is somewhat of a blocking issue.

**Comment by luizirber** [comment]
Hello @dchandran,

what sourmash version are you using? It seems you're using `sourmash 1`, did you install it with `pip`? If this is the case, can you run
`pip install --pre sourmash` instead (and then you get the latest version, `2.0.0a10`).

This example uses a small viral genome that has `N` bases (and using `sourmash==2.0.0a4`). Can you reproduce the error with this command?
```
curl https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/001/857/745/GCA_001857745.1_ASM185774v1/GCA_001857745.1_ASM185774v1_genomic.fna.gz | zcat - | sourmash compute - -o
```

**Comment by ctb** [comment]
Closing for now.
