### ISSUE TITLE
Python API does not allow one to set names of sigs

### ISSUE THREAD

**Issue by taylorreiter** [dib-lab/sourmash#566]
Using the following code, I was trying to iterate over a set of samples and change the names in the signatures. Although this method successfully set the name in python land, when I wrote the signature back out, there was no name in the new signature. 

Talking with @luizirber, we think this should be the default behavior of the API. He thinks the rust implementation solves this.

```
from sourmash import signature

for i, row in mini.iterrows():
    file = row['SampleName'] + '.trinity_out_2.2.0.Trinity.fasta.renamed.fasta.sig'
    new_name  = row['ScientificName'] + " " + row['Strain'] + " " + row['SampleName']
    print(new_name)
    sigfp = open(file, 'rb')
    siglist = list(signature.load_signatures(sigfp))
    sig21 = siglist[0]
    sig21.name = new_name
    print(sig21.name)
    with open(('tmp/' + row['SampleName'] + '.sig'), 'wt') as fp:
        signature.save_signatures([sig21], fp)
```

**Comment by luizirber** [comment]
The main issue is that `name()` is a method, so setting `sig21.name` is
replacing the method...

We need to transform `name` into a property, with the getter being the current
`name()` method and a proper setter that saves the new `name` properly (in the
internal dict)

**Comment by ctb** [comment]
I can confirm that this is still behaving badly --

```
>>> import sourmash
>>> x = sourmash.load_one_signature('/tmp/xxx.sig', ksize=31)
>>> x
SourmashSignature('podar-ref/1.fa', c11126d0)
>>> x.name = 'foo'
>>> x
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/t/dev/sourmash/sourmash/signature.py", line 52, in __str__
    name = self.name()
TypeError: 'str' object is not callable
```

**Comment by ctb** [comment]
of course, this changes the Python API. sigh. So will have to wait for 4.0.
