### ISSUE TITLE
Using single signature for paired end reads

### ISSUE THREAD

**Issue by aditi9783** [dib-lab/sourmash#567]
Hello,

I generated signature for paired-end data (two fastq files: test_1.fastq.gz and test_2.fastq.gz) using the following:
`sourmash compute --scaled 10000 test_*.fastq.gz -o test_pe.sig -k 31`

However, when I use gather with this signature, I get the message:
'When loading query from "signatures/test_pe.sig"
2 signatures matching ksize and molecule type;
need exactly one. Specify --ksize or --dna/--protein.'

When I run gather with a signature created from only one of the fastq files, the command runs fine.

Is there a way to use a single signature for the paired-end reads?

Thanks.

**Comment by ctb** [comment]
Either catenate the two files into sourmash compute -, or use —merged <name> to calc a single signature from all inputs!

--
Titus Brown, ctbrown@ucdavis.edu<mailto:ctbrown@ucdavis.edu>

On Nov 20, 2018, at 4:31 PM, aditi9783 <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello,

I generated signature for paired-end data (two fastq files: test_1.fastq.gz and test_2.fastq.gz) using the following:
sourmash compute --scaled 10000 test_*.fastq.gz -o test_pe.sig -k 31

However, when I use gather with this signature, I get the message:
'When loading query from "signatures/test_pe.sig"
2 signatures matching ksize and molecule type;
need exactly one. Specify --ksize or --dna/--protein.'

When I run gather with a signature created from only one of the fastq files, the command runs fine.

Is there a way to use a single signature for the paired-end reads?

Thanks.

**Comment by aditi9783** [comment]
Thank you, Titus.

I wasn't sure what name to give after '--merge', so I gave the same name as output file and it worked:
`sourmash compute --scaled 10000 ../data/ERR1063836_*.gz --merge ERR1063836.sig -o ERR1063836.sig -k 31`

Thanks!

**Comment by ctb** [comment]
excellent!

**Comment by FerJmnzCc** [comment]
> Either catenate the two files into sourmash compute -, or use —merged <name> to calc a single signature from all inputs!
> […](#)
> -- Titus Brown, ctbrown@ucdavis.edu<mailto:ctbrown@ucdavis.edu> On Nov 20, 2018, at 4:31 

When you say "all imputs" you mean for a pair of fasq? One run of sourmash  compute per couple?
Thanks

**Comment by ctb** [comment]
yep!

On Mon, Mar 09, 2020 at 02:57:31AM -0700, FerJmnzCc wrote:
> > Either catenate the two files into sourmash compute -, or use ???merged <name> to calc a single signature from all inputs!
> > [???](#)
> > -- Titus Brown, ctbrown@ucdavis.edu<mailto:ctbrown@ucdavis.edu> On Nov 20, 2018, at 4:31 
> 
> When you say "all imputs" you mean for a pair of fasq? One run of sourmash  compute per couple?
> Thanks
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/dib-lab/sourmash/issues/567#issuecomment-596433563
-- 
C. Titus Brown, ctbrown@ucdavis.edu

**Comment by peterjc** [comment]
Oh good, I stumbled over this too today using the successor command ``sourmash sketch``, and guessed the cat workaround. In my case based on one of your examples I used:

``zcat example_R1.fastq.gz  example_R2.fastq.gz | sourmash sketch dna -p scaled=10000,k=31 /dev/stdin -o example-reads.sig``

I think this could be more explicit, either in the command line help, or the web-based docs?

**Comment by ctb** [comment]
Fixing in https://github.com/sourmash-bio/sourmash/pull/2563.
