### ISSUE TITLE
Add a remove method to minhashes

### ISSUE THREAD

**Issue by luizirber** [dib-lab/sourmash#573]
During a gather run @taylorreiter and I noticed the `build_new_signature` taking a long time, and when I checked the implementation I saw it is creating a new minhash and adding all the hashes again.

https://github.com/dib-lab/sourmash/blob/4aab62f65fb08044e9a43ec49331b65be8b5ae15/sourmash/search.py#L135-L140

Another alternative is adding a `remove` method to the minhashes. This makes a lot of sense for gather because the query tends to be a big metagenomic minhash and we remove a small amount of hashes at each hit.

(and https://github.com/benfred/py-spy is great for finding these things! I didn't see this before because it didn't show up clearly on profiling runs, since other functions would dominate the runtime... But with py-spy you can take a snapshot while the program is running. Thanks @benfred!)

**Comment by luizirber** [comment]
(also: move it outside `gather_databases` so it is (test|benchmark)-able)

**Comment by ctb** [comment]
relevant to #431

**Comment by ctb** [comment]
Closed by #615.
