### ISSUE TITLE
Allow all ksizes for protein signature calculation if input is protein

### ISSUE THREAD

**Issue by bluegenes** [dib-lab/sourmash#575]
https://github.com/dib-lab/sourmash/blob/4aab62f65fb08044e9a43ec49331b65be8b5ae15/sourmash/commands.py#L161

Here, we check ksize and only allow ksize divisible by 3 when computing protein signatures, which is necessary when we need to translate nucleotide seq to  protein seq, but not if the input is protein (`--input-is-protein` flag is set).

**Comment by ctb** [comment]
Fixed in #576.
