### ISSUE TITLE
signature of type `"mrnaseq"` ?

### ISSUE THREAD

**Issue by lgautier** [dib-lab/sourmash#58]
Why does a `.sig` signature file declares itself of type `"mrnaseq"` (while the input could well be genomic DNA) ?

https://github.com/dib-lab/sourmash/blob/master/sourmash_lib/signature.py#L36

**Comment by ctb** [comment]
Legacy, could be removed.  I've been saving it for a metadata refactor,
that's all.

**Comment by lgautier** [comment]
OK. I won't propose to touch it if going to be removed. If it is going to stay I'd propose to:
- make the type a parameter when creating instances of class `SourmashSignature`
- add a parameter to the command type (e.g., `--signature-type`) to specify that type. The default would be `"unspecified"`.

**Comment by ctb** [comment]
something like it will stay & I agree with your suggestions :)

On Sat, Dec 03, 2016 at 07:04:18AM -0800, Laurent Gautier wrote:
> OK. I won't propose to touch it if going to be removed. If it is going to stay I'd propose to:
> - make the type a parameter when creating instances of class `SourmashSignature`
> - add a parameter to the command type (e.g., `--signature-type`) to specify that type. The default would be `"unspecified"`.
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/dib-lab/sourmash/issues/58#issuecomment-264644329
-- 
C. Titus Brown, ctbrown@ucdavis.edu

**Comment by ctb** [comment]
Removed in #335.
