### ISSUE TITLE
Layer phylogenetic options on to sourmash lca gather?

### ISSUE THREAD

**Issue by ctb** [dib-lab/sourmash#583]
With the merge of #533, the LCA databases have been updated to be complete and work with regular gather. This means that sourmash lca gather is now kind of redundant. BUT IS IT REALLY?? Well, currently, yes. But the LCA commands explicitly work with taxonomic information that is unavailable to the general public.

We could update lca gather to allow "collapsing" output to a given phylogenetic resolution, e.g. `sourmash lca gather -p family ...`. Right now it defaults to "lowest level available" which means strain or species generally.

**Comment by taylorreiter** [comment]
+1 collapsing to phylogenetic resolution!

**Comment by ctb** [comment]
relevant #817

**Comment by ctb** [comment]
I wrote a simple script [here](https://github.com/dib-lab/sourmash/issues/1011#issuecomment-639537026) to do taxonomy things to regular `gather` output; I think #969 is where we will be taking this since lca gather is itself slated for removal in 4.0.

**Comment by ctb** [comment]
Imma gonna close this b/c the other issues handle this well and sourmash lca gather is going away...
