### ISSUE TITLE
New pull request template for easier 'squash and merge'

### ISSUE THREAD

**Issue by luizirber** [dib-lab/sourmash#590]
Background: https://robots.thoughtbot.com/don-t-forget-the-silent-step-when-you-squash-and-merge

We are doing "squash and merge" on PRs, which means all commits from a PR will be squashed into one and then merged to master. While GitHub defaults keep the PR number in the commit message, it would be nice to have better commit message bodies.

At the moment it's up to whoever is merging to write the commit message, so I suggest we keep the PR template in the right format and ask the person who opened the PR to fill it in and keep it updated, so the person merging doesn't have to come up with the reasoning.

(We can try it on #424, which is massive, would benefit from more context in the commit message, and it's super annoying to summarize by anyone except me...)

**Comment by ctb** [comment]
still relevant, yes?

**Comment by luizirber** [comment]
Yup, also connects to #834 and #655

**Comment by ctb** [comment]
I'm going to argue that #1424 fixed this :)
