### ISSUE TITLE
AssertionError when running sourmash-lca

### ISSUE THREAD

**Issue by JiaZhong28** [dib-lab/sourmash#597]
When I was running sourmash lca classify,I got this problem:

`Traceback (most recent call last):ca.json.gz
  File "/home/lizongjun/miniconda3/bin/sourmash", line 11, in <module>
    sys.exit(main())
  File "/home/lizongjun/miniconda3/lib/python2.7/site-packages/sourmash/__main__.py", line 77, in main
    cmd(sys.argv[2:])
  File "/home/lizongjun/miniconda3/lib/python2.7/site-packages/sourmash/lca/__main__.py", line 54, in main
    cmd(sysv_args[1:])
  File "/home/lizongjun/miniconda3/lib/python2.7/site-packages/sourmash/lca/command_summarize.py", line 99, in summarize_main
    dblist, ksize, scaled = lca_utils.load_databases(args.db, args.scaled)
  File "/home/lizongjun/miniconda3/lib/python2.7/site-packages/sourmash/lca/lca_utils.py", line 282, in load_databases
    lca_db.load(db_name)
  File "/home/lizongjun/miniconda3/lib/python2.7/site-packages/sourmash/lca/lca_utils.py", line 162, in load
    assert version == '1.0'
AssertionError
`
This is my command:
`sourmash lca summarize --db genbank-k51.lca.json.gz  --query SB5.bin.9.orig.b.fa.sig`

Can you help me solve this problem?

Thank you very much!

**Comment by JiaZhong28** [comment]
I install again this software used conda,and the same problem appear:


Traceback (most recent call last):ca.json.gz
  File "/home/lizongjun/miniconda3/bin/sourmash", line 11, in <module>
    sys.exit(main())
  File "/home/lizongjun/miniconda3/lib/python3.6/site-packages/sourmash/__main__.py", line 77, in main
    cmd(sys.argv[2:])
  File "/home/lizongjun/miniconda3/lib/python3.6/site-packages/sourmash/lca/__main__.py", line 54, in main
    cmd(sysv_args[1:])
  File "/home/lizongjun/miniconda3/lib/python3.6/site-packages/sourmash/lca/command_summarize.py", line 99, in summarize_main
    dblist, ksize, scaled = lca_utils.load_databases(args.db, args.scaled)
  File "/home/lizongjun/miniconda3/lib/python3.6/site-packages/sourmash/lca/lca_utils.py", line 282, in load_databases
    lca_db.load(db_name)
  File "/home/lizongjun/miniconda3/lib/python3.6/site-packages/sourmash/lca/lca_utils.py", line 162, in load
    assert version == '1.0'
AssertionError

**Comment by ctb** [comment]
aiee you are running into a problem where we have implemented new functionality
for LCA databases, but not officially released the new code that uses them --
it's on the master branch on github, but not yet in bioconda or on pypi!
my apologies.

may I ask where you are downloading the databases from?

best,
--titus

p.s. the error message in the new version of sourmash is much clearer! oops.

**Comment by JiaZhong28** [comment]
Thank you very much!Jsut now I use the rigrt databases by the command `curl -L -o genbank-k31.lca.json.gz https://osf.io/zskb9/download` and the results of most of mine bins are "nomatch".
Because I want to use the the latest updated database to do taxonomic classification,I downloaded these  database at `https://osf.io/vk4fa/files/`.sourmash-lca-mark3

So if I want to use the latest updated database,I must download the new version of sourmash on github?
And how to solve the problem of "nomatch"?

**Comment by ctb** [comment]
yes, that's the right database!

The new database will not change your matches in this case.

if you get a lot of 'nomatch' that should mean that most of your bins are unknown at the species/genus level. You can try using a k-mer size of 21, but your best bet is probably to switch to something that does tax classification at the protein level, such as CheckM.

**Comment by JiaZhong28** [comment]
I am so grateful that you replied to my message.Thank you very much!

Best wishes to you .

**Comment by ctb** [comment]
thank YOU for touching base over this problem! I'm sure others are having it too.

**Comment by ctb** [comment]
(I will close this when we have dealt with the database issue :)

**Comment by Brian-No** [comment]
So I am having the same issue originally posted (assertion error). The software was installed with conda and can generate signatures but all of the commands to classify the signatures throws an assertion error. It doesn't seem to work for either database. Do I need to install a different version of sourmash? 

Thank you.

**Comment by ctb** [comment]
Hi Brian, apologies again. I should have waited to update the databases :)

Try the LCA databases here,

https://osf.io/zskb9

_or_ update from the latest github master to use the databases you've already
downloaded.

(In our (limited) defense we're getting ready for an actual 2.0 release and
wanted to avoid releasing 2.0.0a11.)

best,
--titus

On Fri, Jan 04, 2019 at 07:52:45AM -0800, Brian-No wrote:
> So I am having the same issue originally posted (assertion error). The software was installed with conda and can generate signatures but all of the commands to classify the signatures throws an assertion error. It doesn't seem to work for either database. Do I need to install a different version of sourmash? 
> 
> Thank you.
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/dib-lab/sourmash/issues/597#issuecomment-451482851
-- 
C. Titus Brown, ctbrown@ucdavis.edu

**Comment by luizirber** [comment]
I'll release 2.0.0a12 today, with the latest master. We did merge a bunch of PRs since a11...

On January 4, 2019 3:52:45 PM UTC, Brian-No <notifications@github.com> wrote:
>So I am having the same issue originally posted (assertion error). The
>software was installed with conda and can generate signatures but all
>of the commands to classify the signatures throws an assertion error.
>It doesn't seem to work for either database. Do I need to install a
>different version of sourmash? 
>
>Thank you.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/dib-lab/sourmash/issues/597#issuecomment-451482851

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by luizirber** [comment]
PR submitted to bioconda https://github.com/bioconda/bioconda-recipes/pull/12919
should be available tomorrow (maybe even today, let's see =] )

**Comment by luizirber** [comment]
`2.0.0a11` available on PyPI and bioconda:
```
pip install --pre sourmash==2.0.0a11
```
or
```
conda install sourmash==2.0.0a11
```

**Comment by JiaZhong28** [comment]
> `2.0.0a11` available on PyPI and bioconda:
> 
> ```
> pip install --pre sourmash==2.0.0a11
> ```
> or
> 
> ```
> conda install sourmash==2.0.0a11
> ```

Thank you !

**Comment by ctb** [comment]
thx @luizirber !
