### ISSUE TITLE
error: _minhash.hh: No such file or directory

### ISSUE THREAD

**Issue by sjackman** [dib-lab/sourmash#6]
```
❯❯❯ pip3 install sourmash
…
    running build_ext
    building 'sourmash_lib._minhash' extension
    creating build/temp.linux-x86_64-3.5
    creating build/temp.linux-x86_64-3.5/sourmash_lib
    creating build/temp.linux-x86_64-3.5/third-party
    creating build/temp.linux-x86_64-3.5/third-party/smhasher
    /gsc/btl/linuxbrew/bin/gcc-5 -pthread -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -Os -w -pipe -march=core2 -fPIC -I/gsc/btl/linuxbrew/include -I/gsc/btl/linuxbrew/opt/openssl/include -I/gsc/btl/linuxbrew/opt/sqlite/include -I/gsc/btl/linuxbrew/opt/python3/include/python3.5m -c sourmash_lib/_minhash.cc -o build/temp.linux-x86_64-3.5/sourmash_lib/_minhash.o -std=c++11 -pedantic -O3
    cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
    sourmash_lib/_minhash.cc:66:23: fatal error: _minhash.hh: No such file or directory
    compilation terminated.
    error: command '/gsc/btl/linuxbrew/bin/gcc-5' failed with exit status 1
```

**Comment by ctb** [comment]
Iiiiinteresting.  This works on my Mac and on Linux (Debian) with gcc 4.
Wonder what's different?

I think the fix will be to include the sourmash_lib directory in includes
in setup.py, but generally I would expect a

```
#include "xxx.hh"
```

to look in the same directory, no?

**Comment by ctb** [comment]
See #7. Let me know if it works for you!

**Comment by sjackman** [comment]
I'm not able to reproduce this error outside of `pip install sourmash`. Running `cd sourmash && python setup.py install` works as expected. Also, `cd sourmash && pip install .` works as expected. Running `pip install sourmash` gives the error message as above. Any thoughts on how I can reproduce this error and test this PR?

**Comment by ctb** [comment]
Try cloning and doing pip install ./sourmash - I will test also.

--
Titus Brown, ctbrown@ucdavis.edu

**Comment by sjackman** [comment]
`pip install ./sourmash` succeeds as well.

**Comment by sjackman** [comment]
```sh
curl -L https://github.com/dib-lab/sourmash/archive/v0.3.tar.gz | tar xz && pip install sourmash-0.3/
```
succeeds as well.

**Comment by ctb** [comment]
could you try

```
pip install git+https://github.com/dib-lab/sourmash.git@master
```

at your leisure?

thx!

**Comment by sjackman** [comment]
Success.
```
$ pip install git+https://github.com/dib-lab/sourmash.git@master
Collecting git+https://github.com/dib-lab/sourmash.git@master
  Cloning https://github.com/dib-lab/sourmash.git (to master) to /tmp/pip-Ehq8V7-build
Requirement already satisfied (use --upgrade to upgrade): screed>=0.9 in /gsc/btl/linuxbrew/lib/python2.7/site-packages (from sourmash==0.3)
Requirement already satisfied (use --upgrade to upgrade): PyYAML>=3.11 in /gsc/btl/linuxbrew/lib/python2.7/site-packages (from sourmash==0.3)
Requirement already satisfied (use --upgrade to upgrade): bz2file in /gsc/btl/linuxbrew/lib/python2.7/site-packages (from screed>=0.9->sourmash==0.3)
Installing collected packages: sourmash
  Running setup.py install for sourmash ... done
Successfully installed sourmash-0.3
```

**Comment by ctb** [comment]
great, thank you!

**Comment by sjackman** [comment]
Any idea why `curl -L https://github.com/dib-lab/sourmash/archive/v0.3.tar.gz | tar xz && pip install sourmash-0.3/` worked but `pip install sourmash` did not?

**Comment by sjackman** [comment]
In any case, thanks for the help troubleshooting.

**Comment by ctb** [comment]
On Wed, Jun 08, 2016 at 02:37:18PM -0700, Shaun Jackman wrote:
> Any idea why `curl -L https://github.com/dib-lab/sourmash/archive/v0.3.tar.gz | tar xz && pip install sourmash-0.3/` worked but `pip install sourmash` did not?

nope :).  my guess is that the cwd was set differently.

**Comment by ctb** [comment]
For future reference, this was actually caused by a failure to include the .hh files in the MANIFEST.in file.

**Comment by ctb** [comment]
See https://stackoverflow.com/questions/1612733/including-non-python-files-with-setup-py for general info.
