### ISSUE TITLE
Should downsample_* methods be inplace (instead of returning a new copy)?

### ISSUE THREAD

**Issue by luizirber** [dib-lab/sourmash#618]
https://github.com/dib-lab/sourmash/blob/314bd8e06025d0fd22c37fced0fa5f22aa832a4f/sourmash/_minhash.pyx#L248-L291

It's better to make a explicit copy if needed than do a new copy by default.

@ctb comment: " got a little bit wary of modifying minhashes in place a while back after running into some problems with md5sums changing"

**Comment by ctb** [comment]
yes, I think the answer to the top level issue here is "no", but want to leave this open until I review MinHash API per #885
