### ISSUE TITLE
importerror _minhash.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _ZSt24__throw_out_of_range_fmtPKcz

### ISSUE THREAD

**Issue by dgg32** [dib-lab/sourmash#62]
Hello, dev teams.

I have tried to install the package under Linux Mint 18 Sarah, both via pip and all the instruction from [here](http://ivory.idyll.org/blog/2016-sourmash-sbt.html). The installation finished without error, but if I run it, I got the following error:

from ._minhash import MinHash
ImportError: /home/username/sourmash/sourmash_lib/_minhash.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _ZSt24__throw_out_of_range_fmtPKcz

It seems a solution is needed. Thanks.

Thank you very much.

**Comment by ctb** [comment]
hello, thanks for reporting this!

I did a bit of googling and found this:

http://stackoverflow.com/questions/33239805/libopencv-calib3d-undefined-reference-to-std-throw-out-of-range-fmtchar-co

so it seems like we are using a feature of C++ that is newer than what your
operating system supports.  Could you report what version of g++ you have
('g++ -v') and also list out your libc++ version (I don't know how to do
that on Linux mint!)

best,
--titus

**Comment by dgg32** [comment]
Thank you Titus for your really fast reply.

1): g++ -v

Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/5/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 5.4.0-6ubuntu1~16.04.4' --with-bugurl=file:///usr/share/doc/gcc-5/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-5 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-5-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-5-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-5-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) 


2) for libc++, I have run `/sbin/ldconfig -p | grep stdc++`

and get

	libstdc++.so.6 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libstdc++.so.6
	libstdc++.so.6 (libc6) => /usr/lib/i386-linux-gnu/libstdc++.so.6
	libstdc++.so.5 (libc6) => /usr/lib/i386-linux-gnu/libstdc++.so.5


Aside from these, from your answer, should I update g++ or something please? Thank you!

**Comment by ctb** [comment]
I have to admit I have no idea from this and would have to check around ;).
@luizirber are you up to date this?

I should say that (to the best of my knowledge) we're not using any esoteric
or particularly new bits of C++, so I'm frustrated that this is happening!

**Comment by dgg32** [comment]
Hi Titus. Thank you.

On another machine with Redhat 4.8.5, sourmash runs. With the following g++ version

```
g++ --version
g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-11)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

So it appears it has even an older version of g++ and still works.

Thank you!

**Comment by ctb** [comment]
oooh a good check. thank you.

**Comment by ctb** [comment]
one other thought -- is there an update for your python install?  it is
possible there is a mismatch between the version of g++/glibc that your
python is compiled against vs the version you are compiling with now.

just casting about in the dark here :)

best,
--titus

**Comment by dgg32** [comment]
I have anaconda python 3.5. With the following info

```
Python 3.5.2 |Anaconda 4.2.0 (64-bit)| (default, Jul  2 2016, 17:53:06) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
```

But my colleague also has anaconda 3.5, on a Kbuntu however, his works for him.

Completely puzzled.

Thanks!

**Comment by ctSkennerton** [comment]
Just ran into the exact same thing. Seems to be a problem with gcc-4.9 specifically. Using anaconda3 with gcc-4.8 works. Tested out on fresh VMs from google cloud running debian 8.

**Comment by ctb** [comment]
Closing for now.
