### ISSUE TITLE
Update author list for 4.0

### ISSUE THREAD

**Issue by ctb** [dib-lab/sourmash#622]
`git shortlog --summary --numbered` reports:

```
   746  C. Titus Brown
    94  Luiz Irber
    34  Laurent Gautier
    17  Tim Head
     7  Connor Tiffany
     5  Olga Botvinnik
     4  Taylor Reiter
     3  brooksph
     3  S. Joshua Swamidass
     2  Titus Brown
     2  Harriet Alexander
     1  swamidass
     1  Arfon Smith
     1  Connor T. Skennerton
     1  Daniel Standage
     1  Katrin Leinweber
     1  Phillip Brooks
     1  Tessa Pierce
     1  ljcohen
     1  pyup.io bot
     1  Andreas Sjödin
```

I suspect @luizirber numbers are low because of squash and merge :)

I will assume that @halexand @betatim @olgabot @taylorreiter @brooksph @standage @bluegenes and @ljcohen have no problem being co-authors. (Please let me know here or privately if you don't want to be listed on the JOSS paper!)

Arfon I will exclude because his commit e15e197981f5 was only to update the publication record  :).

pyup.io is a bot... :)

That leaves:

* Laurent Gautier - many contributions!
* Connor Tiffany - revamped documentation (RST -> Markdown), #356 
* S. Joshua Swamidass - updated some tests and code #138
* Connor Skennerton - commit 41ad6b9a added code checking on file existence
* Katrin Leinweber - commit d2e2e3fd5, updating documentation.
* Andreas Sjodin - commit a5c60c7, updating documentation.

**Comment by ctb** [comment]
hi @katrinleinweber I can't find an e-mail address for you - so I'm pinging you here :). Please drop me a note here or at titus@idyll.org if we can list you as a co-author on our submission of sourmash 2.0.0 to JOSS. Thank you!

**Comment by ctb** [comment]
@ctSkennerton is in!

**Comment by katrinleinweber** [comment]
Oh, thank you! Also to JOSS for [including non-code contributions](https://joss.readthedocs.io/en/latest/submitting.html#authorship). Please find my details at the bottom of https://www.tib.eu/en/research-development/non-textual-materials/focus-of-work/scientific-software/ :-)

**Comment by ctb** [comment]
@swamidass, @katrinleinweber, and @lgautier are all in! Still need to ping Connor Tiffany, and haven't (yet) heard back from Andreas.

Next step is going to be to collect ORCIDs.

**Comment by betatim** [comment]
I am https://orcid.org/0000-0003-0931-3698

**Comment by ctSkennerton** [comment]
My orcid is 0000-0003-1320-4873

**Comment by bluegenes** [comment]
my ORCID: 0000-0002-2942-5331

thx!

**Comment by halexand** [comment]
Thank you! My orcid is : https://orcid.org/0000-0003-1308-8008

**Comment by standage** [comment]
My ORCID is 0000-0003-0342-8531.

**Comment by ljcohen** [comment]
Mine is 0000-0002-3600-7218, thank you!

**Comment by ctb** [comment]
now a blog post: http://ivory.idyll.org/blog/2019-authorship-revisiting.html

**Comment by swamidass** [comment]
Mine is 0000-0003-2191-0778. 

I hope we consider adding in support for these two algorithms:
https://pubs.acs.org/doi/abs/10.1021/ci600526a
https://pubmed.ncbi.nlm.nih.gov/25714898/

**Comment by ctb** [comment]
> I hope we consider adding in support for these two algorithms:
> https://pubs.acs.org/doi/abs/10.1021/ci600526a
> https://pubmed.ncbi.nlm.nih.gov/25714898/

being discussed here: https://github.com/dib-lab/sourmash/issues/1230
