### ISSUE TITLE
update changelog / release notes for 2.0

### ISSUE THREAD

**Issue by ctb** [dib-lab/sourmash#623]
hey @luizirber I don't actually see that we have release notes or a changelog. ...shall we start the tradition at 2.0.0 and simply say "lots of things changed from 1.0 to 2.0", or do you think I should do a high level summary, or what?

here's what we do for khmer: https://khmer.readthedocs.io/en/v2.1.1/release-notes/release-2.1.html

**Comment by luizirber** [comment]
I think we can follow the khmer model. Even a list of PRs like https://github.com/dib-lab/sourmash/releases/tag/v2.0.0a11 already helps...

**Comment by ctb** [comment]
OK, I've put in a first try [here](https://github.com/dib-lab/sourmash/blob/add/release_notes/doc/release-notes/sourmash-2.0.md), in #630. Comments welcome.

(I did a reasonably thorough first pass review of all of the PRs since v1.0.)
