### ISSUE TITLE
Whether a genome is in a metagenome, gather or containment?

### ISSUE THREAD

**Issue by dgg32** [dib-lab/sourmash#636]
Hello, dear community.

I have a user case here that I would like to know whether a genome is in a metagenome. I have gone through the tutorial and realize that both gather and "search --containment" can conceptually work. But I wonder which option do you think is the better one? Thank you!

**Comment by ctb** [comment]
hello!

if you have a specific genome in mind, 'sourmash search --containment <genome>
<metagenome>' will work just fine and will report how much of the genome is in
the metagenome.

but 'sourmash gather <metagenome> <genome>' will do the same thing and also
report an extra bit of information (how much of the metagenome is covered by
the genome).

underneath they use the same code so you are good either way :)

you might also try our exciting new command (only available in github at
the moment), 'sourmash signature overlap <genome> <metagenome>'.

best,
--titus

**Comment by dgg32** [comment]
Thank you!
