### ISSUE TITLE
Unable to build a sourmas protein lca database

### ISSUE THREAD

**Issue by SilasK** [dib-lab/sourmash#639]
I would like to build a lca database with protein accessions. 

I followed the steps [here](https://github.com/dib-lab/2018-ncbi-lineages)
but I end up with the following obscure error:
`ERROR: no hash values found - are there any signatures?`

I use sourmash from bioconda 2.0.0a11

I build a signature with 
```
sourmash compute --input-is-protein -k 21 --scaled=100000 -o 1089550_0.sig 1089550_0.fs -f --name-from-first
```
and tried to build the lca index with:

```
sourmash lca index lineages.csv lca.json *.sig -C 3
```
output:
```
examining spreadsheet headers...
** assuming column 'accession' is identifiers in spreadsheet
1 distinct identities in spreadsheet out of 1 rows.
1 distinct lineages in spreadsheet out of 1 rows.
ERROR: no hash values found - are there any signatures?
````
working example:
[Archive.zip](https://github.com/dib-lab/sourmash/files/2790891/Archive.zip)

**Comment by ctb** [comment]
hi! try lowering the scaled value to 100 or so! most protein sequences are much smaller than 10kb.

**Comment by ctb** [comment]
Closing until further updates.
