### ISSUE TITLE
Approximate SNPs

### ISSUE THREAD

**Issue by moorembioinfo** [dib-lab/sourmash#644]
Hi! 

Is it possible to get approximate number of SNPs from sourmash? When using sourmash search finding the approximate SNP number or distance for the top results?

Thanks, 

Matt

**Comment by ctb** [comment]
Hi! In the mash paper, https://genomebiology.biomedcentral.com/articles/10.1186/s13059-016-0997-x, they infer a relationship between Jaccard similarity and Average Nucleotide Identity, which is what I think you want.

best,
--titus

On Wed, Feb 20, 2019 at 12:44:23AM -0800, moorembioinfo wrote:
> Hi! 
> 
> Is it possible to get approximate number of SNPs from sourmash? When using sourmash search finding the approximate SNP number or distance for the top results?
> 
> Thanks, 
> 
> Matt 
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/dib-lab/sourmash/issues/644
-- 
C. Titus Brown, ctbrown@ucdavis.edu

**Comment by ctb** [comment]
let us know if you need more info!

best,
--titus

**Comment by moorembioinfo** [comment]
Hi Titus, 

Thanks for your response! Following up on this is it possible to get the distance measure to more than 3 decimal places?

Best, 

Matt

**Comment by ctb** [comment]
yep -- the CSV output file (`--csv`) has high precision output!
