### ISSUE TITLE
genbank-d2 database is too big...

### ISSUE THREAD

**Issue by ctb** [dib-lab/sourmash#646]
I'm working on revamping the tutorials, and the genbank-d2 database doesn't fit in ~15 GB when unpacked, which makes it impossible to run on a default Jetstream m1.medium machine. Sigh.

What are our options for making a db that's smaller when unpacked, @luizirber?

**Comment by ctb** [comment]
now that I think of it, one simple solution is to use the LCA database, since `sourmash gather` works on that in the same way and it's much smaller. What do you think of that as a stopgap measure?

**Comment by ctb** [comment]
this is what I did in ff22e2f, part of #631.

It would still be good to get a rundown of what our options are for SBTs!

**Comment by luizirber** [comment]
I pulled #648 out of some other indexing refactoring I was doing in #456 . This supports loading data directly from a Zip file. It would work with `tar` too, but they don't support random access well (see #490 for more info).

**Comment by ctb** [comment]
As of #648 sourmash now supports direct search of SBTs in zip files!
