### ISSUE TITLE
in sourmash index, --traverse-directory needs to go last -- it shouldn't

### ISSUE THREAD

**Issue by phiweger** [dib-lab/sourmash#649]
Hi,

I struggled to get the `sourmash index --traverse-directory` arg working, mainly bc/ it needs to go last in the command line call, which is unintuitive given that it has a `--` prefix; or am I missing something?

```bash
# --traverse-directory like any command line arg
sourmash index --traverse-directory sigs/ -k 31 sbt_k31
loading 0 files into SBT

no signatures found to load into tree!? failing.

# --traverse-directory last
sourmash index -k 31 sbt_k31 --traverse-directory sigs/
loading 145817 files into SBT
...reading from sigs/RS_GCF_001393515.1_genomic.fna.sig (260 signatures so far)
```

Best,
Adrian

**Comment by ctb** [comment]
I verify this behavior is happening for me too.  While counterintuitive, it is because `--traverse-directory` is setting a flag, and doesn't actually take an argument. So your first command reads like this to argparse:

```
sourmash index sigs/ sbt_k31 -k 31 --traverse-directory
```

instead of

```
sourmash index sbt_k31 sigs/ -k 31 --traverse-directory
```

I've updated the help string (in #727) to be a little clearer.

**Comment by ctb** [comment]
While I don't like the `--traverse-directory` behavior particularly, it is correct as it goes. Closing this in favor of a new issue on better signature traversal, #836. :)
