### ISSUE TITLE
is Sourmash double counting

### ISSUE THREAD

**Issue by dchandran** [dib-lab/sourmash#654]
I am using the LCA summarize function to get hit counts for different taxonomic groups. It appears that if a sequence get a hit to a species, the genus for that species also gets a hit. Is this the intended behavior? It is fine; I just want to understand that this is indeed what is going on

**Comment by ctb** [comment]
yes!

On Thu, Mar 21, 2019 at 05:21:29PM +0000, Deepak Chandran wrote:
> I am using the LCA summarize function to get hit counts for different taxonomic groups. It appears that if a sequence get a hit to a species, the genus for that species also gets a hit. Is this the intended behavior? It is fine; I just want to understand that this is indeed what is going on 
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/dib-lab/sourmash/issues/654
-- 
C. Titus Brown, ctbrown@ucdavis.edu

**Comment by ctb** [comment]
On Thu, Mar 21, 2019 at 05:21:29PM +0000, Deepak Chandran wrote:
> I am using the LCA summarize function to get hit counts for different taxonomic groups. It appears that if a sequence get a hit to a species, the genus for that species also gets a hit. Is this the intended behavior? It is fine; I just want to understand that this is indeed what is going on 

(we would say "aggregating" rather than "double counting" - I believe
this matches what Kraken is doing.)
