### ISSUE TITLE
Does Sourmash have a bias for fasta files with more contigs?

### ISSUE THREAD

**Issue by dchandran** [dib-lab/sourmash#656]
I am using custom assembly files (multi-fasta files) to generate signatures and then LCA index. Then I use LCA summarize to get hit counts. However, it appears that the hit counts over-counts assemblies with more contigs. Have you seen something similar, and if so, how can I circumvent this issue?

**Comment by ctb** [comment]
Hi @dchandran apologies for long delay in answering. This should not be happening... and if it is we should fix it :) Could you provide a little more detail as to what is going on?

**Comment by ctb** [comment]
Closing for now.

**Comment by ctb** [comment]
(although one thought is that perhaps assemblies with many contigs are being more sensitive to read content/recovering more from complex assemblies, thus have more k-mer content, thus look "overrepresented")
