### ISSUE TITLE
How to cite sourmash lca?

### ISSUE THREAD

**Issue by phiweger** [dib-lab/sourmash#658]
How indeed :)

**Comment by luizirber** [comment]
great question... there is a sourmash 2.0 paper on the way, and I think it's probably the best option to cite (the JOSS paper is more for 1.0, and a lot changed).

pinging @bluegenes and @ctb for more ideas =]

**Comment by ctb** [comment]
sourmash LCA is mentioned here: https://f1000research.com/articles/8-1006
