### ISSUE TITLE
link for Salmonella enterica is broken

### ISSUE THREAD

**Issue by nerdcommander** [dib-lab/sourmash#665]
link for _Salmonella enterica_ is broken in the command-line.md tutorial.
more recent version of that genome:
ftp://ftp.ncbi.nlm.nih.gov/genomes/refseq/bacteria/Salmonella_enterica/reference/GCF_000006945.2_ASM694v2

**Comment by dsouzadaniel** [comment]
I'd to work on this issue! :)

**Comment by dsouzadaniel** [comment]
@nerdcommander I tried to curl the link you provided. Didn't work. Also checked NCBI for an updated link, but filesize says O Bytes? :/
