### ISSUE TITLE
Question: Output all search results even if very low

### ISSUE THREAD

**Issue by jolespin** [dib-lab/sourmash#671]
Is it possible to output all of the query searches from sourmash search even if the values are extremely low ~0?  What is the default threshold to show up in the output csv?

**Comment by ctb** [comment]
Hi Josh, have you tried using --threshold=0?

I'll track down the default threshold in a bit.

**Comment by ctb** [comment]
The default threshold is 0.08 currently. The `-h` / `--help` text doesn't display that because we aren't using argparse properly (#706).
