### ISSUE TITLE
sourmash compute --scaled ... question on usage

### ISSUE THREAD

**Issue by phiweger** [dib-lab/sourmash#684]
hi,

when we use `sourmash compute --scaled 10000 reads.fq.gz` -- does that mean that 1 out of every 10k k-mers in the read set is sampled? 

if so, I would subsequently run `sourmash gather` on this signature -- are there any problems with this? like is this an intended use case?

thanks a lot!

**Comment by ctb** [comment]
yes, and yes! I believe that the database has to be at an equal or  higher
scaled, however - there should be a clear error output if so.

**Comment by phiweger** [comment]
thanks for the quick reply!
