### ISSUE TITLE
Can we apply sourmash straightforward to explore the similarity between proteomes?

### ISSUE THREAD

**Issue by GuilleChapin** [dib-lab/sourmash#691]
I would like to evaluate the pairwise similarity between proteomes or 2 protein sets using the Jaccard index. It is possible to calculate k-mers straightforward for protein alphabet?
Thanks!

**Comment by ctb** [comment]
yes, you can use 'sourmash compute --protein' to compute
protein signatures and then everything else _should_ work as normal.

**Comment by GuilleChapin** [comment]
Great!! Thanks!

**Comment by GuilleChapin** [comment]
What k-mer size you recommend for proteins (no genomes)?

**Comment by ctb** [comment]
I'm afraid I don't have any experience here! But something in the 10-15 range
should work.

On Wed, Jul 03, 2019 at 07:05:06AM -0700, GuilleChapin wrote:
> What k-mer size you recommend for proteins (no genomes)?
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/dib-lab/sourmash/issues/691#issuecomment-508107560
-- 
C. Titus Brown, ctbrown@ucdavis.edu

**Comment by GuilleChapin** [comment]
Thanks for the advice!! I will give you some feedback
