### ISSUE TITLE
Can prepared sourmash search databases be used without decompression?

### ISSUE THREAD

**Issue by jolespin** [dib-lab/sourmash#699]
For example, this database:
https://s3-us-west-2.amazonaws.com/sourmash-databases/2018-03-29/genbank-d2-k51.tar.gz

If I used `sourmash search`, would I have to decompress this first?

**Comment by taylorreiter** [comment]
Not currently. At the moment the only database that can be used in its compressed format is for `sourmash lca` database, which is available here: https://sourmash.readthedocs.io/en/latest/databases.html
