### ISSUE TITLE
Cannot open file 'genbank-k31.lca.json.gz'

### ISSUE THREAD

**Issue by ZeweiSong** [dib-lab/sourmash#708]
I tried to run the example command

    sourmash gather -k 31 ecoli-genome.sig genbank-k31.lca.json.gz\

But I got this:

    Error in parsing signature; quitting.
    Exception:

    Cannot open file 'genbank-k31.lca.json.gz'

After reading other issues, I think this could be caused by absolute path. Is there a quick way to fix this without compute it again?

Thanks!

**Comment by ctb** [comment]
Hi Zewei,

I suspect you are using an incompatible version of sourmash - what does
'sourmash info' report?

best,
--titus

On Mon, Aug 05, 2019 at 02:40:34AM -0700, Zewei Song wrote:
> I tried to run the example command
> 
>     sourmash gather -k 31 ecoli-genome.sig genbank-k31.lca.json.gz\
> 
> But I got this:
> 
>     Error in parsing signature; quitting.
>     Exception:
> 
>     Cannot open file 'genbank-k31.lca.json.gz'
> 
> After reading other issues, I think this could be caused by absolute path. Is there a quick way to fix this without compute it again?
> 
> Thanks!
> 
> 
> 
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/dib-lab/sourmash/issues/708
-- 
C. Titus Brown, ctbrown@ucdavis.edu

**Comment by ZeweiSong** [comment]
Hi, Titus

I tried to install the latest version using

    pip install sourmash

But this is what I got:

```
Requirement already satisfied: sourmash in /ldfssz1/ST_META/share/flow/anaconda3/lib/python3.6/site-packages (2.0.0a6)
Requirement already satisfied: screed>=0.9 in /ldfssz1/ST_META/share/flow/anaconda3/lib/python3.6/site-packages (from sourmash) (1.0)
Requirement already satisfied: ijson in /ldfssz1/ST_META/share/flow/anaconda3/lib/python3.6/site-packages (from sourmash) (2.3)
Requirement already satisfied: khmer>=2.1<3.0 in /ldfssz1/ST_META/share/flow/anaconda3/lib/python3.6/site-packages (from sourmash) (2.1.2)
Requirement already satisfied: bz2file in /ldfssz1/ST_META/share/flow/anaconda3/lib/python3.6/site-packages (from screed>=0.9->sourmash) (0.98)
Requirement already satisfied: Cython>=0.25.2 in /ldfssz1/ST_META/share/flow/anaconda3/lib/python3.6/site-packages (from khmer>=2.1<3.0->sourmash) (0.29.10)
```

I also tried to install from the wheel, but still got this:

    sourmash-2.0.1-cp37-cp37m-manylinux1_x86_64.whl is not a supported wheel on this platform.

I am using CentOS on a cluster.

Thanks!

**Comment by ZeweiSong** [comment]
Also, I can install the latest version on my laptop with the Windows 10 WSL Ubuntu, so I think it may be some system compatible issue. Not quite sure.

**Comment by ctb** [comment]
Hi zewei,

yep, looks like an older (incompatible) version is installed. Maybe try

pip install -U sourmash

?

best,
--titus

**Comment by ZeweiSong** [comment]
Thanks, just fixed this with our admin.

Zewei

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________
