### ISSUE TITLE
Pig missing from euk_rna_k31

### ISSUE THREAD

**Issue by Joiry** [dib-lab/sourmash#712]
For Taylor, Sus scrofa looks to be missing from euk_rna db.

**Comment by taylorreiter** [comment]
Thanks @Joiry! To build this database, we used ncbi-genome-download (https://github.com/kblin/ncbi-genome-download) to download all eukaryotic RNA files that ended with `_rna_from_genomic.fna.gz`. Looking on genbank at the pig accessions, none have files that end in `_rna_from_genomic.fna.gz`, so this species would not be captured by our database method.

ftp://ftp.ncbi.nlm.nih.gov/genomes/genbank/vertebrate_mammalian/Sus_scrofa/latest_assembly_versions/:
```
GCA_000003025.6_Sscrofa11.1
		9/16/19 	12:56:00 AM PDT
GCA_000325925.2_minipig_v1.0
		9/15/19 	11:12:00 PM PDT
GCA_000331475.1_SscrofaMinipig
		9/15/19 	11:03:00 PM PDT
GCA_000472085.2_Tibetan_Pig_v2
		9/16/19 	12:57:00 AM PDT
GCA_001292865.1_ss10.2_mar2013
		9/15/19 	11:17:00 PM PDT
GCA_001700135.1_Large_White_v1
		9/16/19 	12:56:00 AM PDT
GCA_001700155.1_Rongchang_pig_v1
		9/16/19 	12:56:00 AM PDT
GCA_001700165.1_Hampshire_pig_v1
		9/16/19 	12:56:00 AM PDT
GCA_001700195.1_Meishan_pig_v1
		9/16/19 	12:56:00 AM PDT
GCA_001700215.1_Landrace_pig_v1
		9/16/19 	12:56:00 AM PDT
GCA_001700235.1_Bamei_pig_v1
		9/16/19 	12:56:00 AM PDT
GCA_001700255.1_Pietrain_pig_v1
		9/16/19 	12:56:00 AM PDT
GCA_001700295.1_Jinhua_pig_v1
		9/16/19 	12:56:00 AM PDT
GCA_001700575.1_Berkshire_pig_v1
		9/16/19 	12:56:00 AM PDT
GCA_002844635.1_USMARCv1.0
		9/15/19 	11:25:00 PM PDT
GCA_006511355.1_NSME_pig_1
		9/16/19 	12:04:00 AM PDT
GCA_007644095.1_ASM764409v1
		9/16/19 	12:28:00 AM PDT
GCA_900119615.2_WTSI_X_Y_pig_V2
		9/16/19 	12:35:00 AM PDT
```

We've tinkered around with building a eukaryotic sbt with masked genomes, but we haven't finished this project yet. (https://github.com/dib-lab/2018-euk-SBTs)

As a patch for any species that is not in the database, one can create a signature from their species of interest and tack it on to the end of the gather command as another "database"
