### ISSUE TITLE
Investigating various k-mer sizes with sourmash lca summarize and/or classify

### ISSUE THREAD

**Issue by lindsayrutter** [dib-lab/sourmash#735]
Thank you for the helpful software. I am using sourmash to determine the taxonomic identify of paired-end read samples using all the GeneBank microbial genomes. I followed the helpful instructions located at: https://sourmash.readthedocs.io/en/latest/tutorials-lca.html and used the following procedure:

1) I first made GeneBank LCA databases for K=7, 9, and 11:

```
curl -L -o genbank-k7.lca.json.gz https://osf.io/4f8n3/download
curl -L -o genbank-k9.lca.json.gz https://osf.io/4f8n3/download
curl -L -o genbank-k11.lca.json.gz https://osf.io/4f8n3/download
```

2) Then I computed signatures for my sample:

`sourmash compute --scaled 1000 -k 7,9,11 sample1_R1.fastq sample1_R2.fastq`

3) Then I tried to classify and/or summarize the k-7 signature (at least of Read 1):

`sourmash lca summarize --db genbank-k7.lca.json.gz --query sample1_R1.fastq.sig`

and

`sourmash lca classify --db genbank-k7.lca.json.gz --query sample1_R1.fastq.sig`

However, I noticed that both of these steps seemed to use ksize of 31, as part of their output statements included: "loaded 1 LCA databases. ksize=31, scaled=10000”)"

4) So, I went back to step (2) and tried to compute signatures only for k-7:

`sourmash compute --scaled 1000 -k 7 sample1_R1.fastq sample1_R2.fastq`

The output files were named sample1_R1.fastq.sig and sample1_R2.fastq.sig, and I renamed them as sample1_R1_k7.fastq.sig and sample1_R2_k7.fastq.sig to keep the files clear.

5) Then I tried to classify and/or summarize the k-7 signature (at least of Read 1) again:

`sourmash lca summarize --db genbank-k7.lca.json.gz --query sample1_R1_k7.fastq.sig`

and 

`sourmash lca classify --db genbank-k7.lca.json.gz --query sample1_R1_k7.fastq.sig`

However, both of these steps still seemed to use ksize of 31, as part of their output statements included: "loaded 1 LCA databases. ksize=31, scaled=10000”)"

6) In case this problem (inconsistency in k-mer values) was due to paired-end inputs, I reran step (2) only now using just k-7 and just Read 1:

`sourmash compute --scaled 1000 -k 7 sample1_R1.fastq `

The output files was named sample1_R1.fastq.sig, and I renamed it as sample1_R1_k7.fastq.sig to keep the file name clear.

7) Then I tried to classify and/or summarize the k-7 signature (of Read 1) again:

`sourmash lca summarize --db genbank-k7.lca.json.gz --query sample1_R1_k7.fastq.sig`

and

`sourmash lca classify --db genbank-k7.lca.json.gz --query sample1_R1_k7.fastq.sig`

However, both of these steps still seemed to use ksize of 31, as part of their output statements included: "loaded 1 LCA databases. ksize=31, scaled=10000”)"

I wanted to ask if it is possible for me to use the sourmash lca summarize and/or classify functions on various k-mer sizes (besides its default value of 31). I tried specifying options but was unsuccessful. Any advice would be greatly appreciated.

**Comment by ctb** [comment]
On Tue, Sep 17, 2019 at 03:51:18AM -0700, Lindsay Rutter wrote:
> Thank you for the helpful software. I am using sourmash to determine the taxonomic identify of paired-end read samples using all the GeneBank microbial genomes. I followed the helpful instructions located at: https://sourmash.readthedocs.io/en/latest/tutorials-lca.html and used the following procedure:
> 
> 1) I first made GeneBank LCA databases for K=7, 9, and 11:
> 
> ```
> curl -L -o genbank-k7.lca.json.gz https://osf.io/4f8n3/download
> curl -L -o genbank-k9.lca.json.gz https://osf.io/4f8n3/download
> curl -L -o genbank-k11.lca.json.gz https://osf.io/4f8n3/download

Hi, I think this is the root of the problem - this doesn't build a 
database with a different ksize, it just downloads the k=31 database
under three different names. You'd need to rebuild the genbank
database with k=7, k=9, and k=11 signatures, which would be a pretty
big endeavor (it would take several days and you'd need all the
genbank genomes!)

best,
--titus
-- 
C. Titus Brown, ctbrown@ucdavis.edu

**Comment by lindsayrutter** [comment]
Hello Titus:

That definitely makes sense and clears up my problem. Thanks for the informative response. 

Lindsay

**Comment by ctb** [comment]
welcome & best of luck!
