### ISSUE TITLE
ijson breaking change in 2.5

### ISSUE THREAD

**Issue by luizirber** [dib-lab/sourmash#737]
FYI: `ijson 2.5` breaks our tests ([master](https://travis-ci.com/dib-lab/sourmash/jobs/238408896) is currently broken).

I'm pinning it in https://github.com/dib-lab/sourmash/pull/736/commits/2d0e2970da5f0d0d80f96f037ab1953254ba01c0, but need to investigate a more permanent fix (or drop `ijson` and do the parsing in Rust, [*wink wink*](#532)).

Relevant issue: https://github.com/ICRAR/ijson/issues/13

**Comment by ctb** [comment]
so, we're not actually using ijson anywhere any more. But it's in the docs... 
```
% git grep ijson
README.md:requirements are screed and ijson, together with a Rust environment (for the
doc/developer.md:requirements are screed and ijson, together with a Rust environment (for the
doc/release.md:python -m pip install screed pytest numpy matplotlib scipy khmer ijson bam2fasta deprecation cffi
tests/test_deprecated.py:    # ijson requires a file in binary mode or bytes,
```

**Comment by ctb** [comment]
removing from docs in #1140, but in any case this issue is no longer relevant :)
