### ISSUE TITLE
heisenbug in test_do_sourmash_compute_10x

### ISSUE THREAD

**Issue by luizirber** [dib-lab/sourmash#738]
Builds are failing in Travis, and restarting then works (sometimes).

I tried to reproduce locally, but stopping the debugger before the assertion makes the problem disappear :roll_eyes:

Example: https://travis-ci.com/dib-lab/sourmash/jobs/238710266#L795
This also happened on py36 on a previous commit in #734

**Comment by ctb** [comment]
status @luizirber ?

**Comment by luizirber** [comment]
it's fixed
