### ISSUE TITLE
Implement intersection of an abundance-tracked signature with a list of hashes

### ISSUE THREAD

**Issue by taylorreiter** [dib-lab/sourmash#743]
`sourmash compute` allows abundance tracking of k-mers. The abundance information is sometimes dropped by downstream processes, e.g. when running `sourmash gather` the unassigned hashes do not have abundance info. I have hashes of interest for which I would like abundance information, and I think the simplest way to extract it would be to intersect the full signature with abundance information with a list of my hashes of interest (recorded in a text file, one per line). Would it be possible to intersect a signature with a list of hashes and optionally retain the abundance information recorded in the signature?

**Comment by ctb** [comment]
(Note, #726 fixed the issue where unassigned hashes from sourmash gather do not have abundance info.)

**Comment by ctb** [comment]
I broke this down into two issues:

first, `sourmash signature intersect` now supports preserving abundances; this functionality is implemented in #747.

second, hashvals can be loaded into a signature using the script `utils/hashvals-to-signature.py` in #724. (Eventually this functionality will be implemented in `sourmash signature import`, but not today.)

**Comment by ctb** [comment]
Implemented and I think @taylorreiter has used it? So closing, reopen if something's still broken!
