### ISSUE TITLE
Where is the version displayed?

### ISSUE THREAD

**Issue by johnsolk** [dib-lab/sourmash#754]
Where is the version of sourmash displayed? 

I'm working with some old .sig data generated with sourmash (conda install) back in Jan 2019. I cannot find where the sourmash version is displayed, either in the data files or with the program. I still have the old conda environment where sourmash was installed. Upon running "sourmash" or "sourmash compute" or "sourmash -h", I could not seem to find the version displayed there either. Am I missing something?

**Comment by ctb** [comment]
sourmash info

**Comment by johnsolk** [comment]
This worked, thanks!
```
[ljcohen@login006 ~]$ sourmash info
sourmash version 2.0.0a10
- loaded from path: /pylon5/bi5fpmp/ljcohen/miniconda3/envs/sourmash_conda/lib/python3.6/site-packages/sourmash

```

**Comment by ctb** [comment]
excellent!
