### ISSUE TITLE
Cant open binary files?

### ISSUE THREAD

**Issue by foamy1881** [dib-lab/sourmash#779]
How can you view the binary file created after distance matrix calculation. It does not have any extension at all and upon checking it is categorize as binary octet-stream file??

**Comment by ctb** [comment]
hi @foamy1881 see https://sourmash.readthedocs.io/en/latest/command-line.html#sourmash-compare - it's a numpy matrix file, which is mostly useful from with Python. You can specify `--csv` to output a text file that can be loaded by R, and we have some example code for that here: https://sourmash.readthedocs.io/en/latest/other-languages.html

Let us know if you have any more questions!
