### ISSUE TITLE
No --help for subcommands

### ISSUE THREAD

**Issue by standage** [dib-lab/sourmash#783]
A colleague was experimenting with sourmash 2.2.0 and was surprised that `sourmash compute --help` didn't provide a usage statement. I have to admit I was surprised too. I've seen intermittent updates on [this PR](https://github.com/dib-lab/sourmash/pull/245) for \**checks notes*\* 2.5 years now. 😀 I know that supporting a consistent CLI and API isn't trivial, but in the mean time would it be difficult to support `-h|--help` for subcommands?

**Comment by standage** [comment]
Looks like this is a duplicate of #706.

**Comment by ctb** [comment]
...pull requests are always welcome!

:) :)

It's a lot of tedious work to do, which is part of the problem.  It'd
probably only take me a few hours tho.

**Comment by standage** [comment]
The approach I originally came up with for kevlar (https://github.com/dib-lab/sourmash/pull/245#issuecomment-302905439) has served me well in several projects since (including [this](https://github.com/bioforensics/MicroHapDB) and [this](https://github.com/bioforensics/MicroHapulator)). I'd be happy to get a PR started and implement the CLI part, although updating the tests will likely be the tedious part.

**Comment by standage** [comment]
Dewd. Subcommands nested 3 levels deep? O_o

Un-signup! :-)
