### ISSUE TITLE
Update developer.md with a brief discussion of layout and packages

### ISSUE THREAD

**Issue by ctb** [dib-lab/sourmash#831]
per #812, there is now some complex relationship with rust packages that I don't understand :). It would be good to drop a few sentences about what goes where in sourmash, and what the rust packages are, into [developer.md](https://github.com/dib-lab/sourmash/blob/master/doc/developer.md). I'd write it if I understood it... but I don't. @luizirber ?

**Comment by luizirber** [comment]
Does #832 seems like a good start for this?

**Comment by ctb** [comment]
will look, thx
