### ISSUE TITLE
How should sourmash sig functions behave when operating on collections?

### ISSUE THREAD

**Issue by ctb** [dib-lab/sourmash#857]
OK, question for the peanut gallery (@taylorreiter @bluegenes) - how should `sourmash sig` functions like `downsample` and `filter` behave when operating on collections of signatures?

1. always output _only_ the signatures that they operated on (i.e. that match -k and molecule type selectors)
2. always output _all_ the signatures they're given as input, only changing signatures that match selectors
3. do (1) when operating with explicit `--output` arguments, and (2) when operating with `--inplace` options

Right now we seem to be really inconsistent - for example, `downsample`, `filter`, and `flatten` do a mix of (1) and (2), mainly because the `load_signatures` function takes ksize and moltype selectors and only loads those.

I'm tempted to say the right behavior is (3), but this starts to add lots of ugly logic and might be hard for users to predict. (2) would be consistent... (1) might result in data loss. I dunno. Thoughts?

ref #855

**Comment by ctb** [comment]
Some scenarios --

## directory downsampling

I have a directory full of signature files, and I want to downsample all of the k=31 ones.

`sourmash sig downsample -k 31 --scaled=10000 --inplace *.sig`

trashing all of the sigs that aren't k=31 seems like a bad idea. but, frankly, so does changing them all inplace without any backup. Hmm.

## directory filtering

I have a directory full of signature files, and I want to eliminate all but the k=31 ones.

`sourmash sig select -k 31 --inplace *.sig`

here, eliminating the k != 31 ones is fine.

(note `select` doesn't exist but maybe it should :)

but this is a bit contrived, anyway. or maybe it's not?

## other thoughts

we could use a selector framework inside sourmash signature handling.

the way we support having multiple signatures in files is kind of inconsistent.

**Comment by taylorreiter** [comment]
I like option 3! I can think of use cases for 1 and 2, so I like having the option. I think we would need to document `--output`, `--inplace` and their relationship very well though.

**Comment by ctb** [comment]
after more work on the sourmash sig module, and the addition of `cat` and `split`, I think I am overthinking this and things like `--inplace` would be hard to implement and prone to bugginess :). I'm going to close this in favor of a more ...evolutionary approach, or at least until there are more use cases that I can't easily solve with the current tools.
