### ISSUE TITLE
add tests to confirm that MinHash objects are correctly created post-pickle

### ISSUE THREAD

**Issue by ctb** [dib-lab/sourmash#87]
`test_estimators.py::test_pickle` only checks the values on the Estimator object, and does not confirm that the new `Estimator.mh` object behaves properly; we should check all the behavior, including n, k, dna, protein, track_abundance, and (assuming #83) max_hash.

An alternative and better approach might be to have accessors for all the internal MinHash foo, which I believe is being added in #79.

**Comment by lgautier** [comment]
#79 is doing four things:
- make the default seed an explicitly readable value from Python
- specifying the seed an (optional) parameter for all C-level functions / class / methods
- refactor the C code to allow the use of C-level getters and setters, so I could have the seed as an attribute
- fixed the `tp_name` to the full class path. I suspect that unpickling might not work well without this.

That latest point makes it possible/easy to add attributes for anything else (may be `get_mins()` could become `mins` - see #82 )

```C
* Getters and setters for MinHash */
static PyGetSetDef MinHash_getseters[] = {
  {"seed", 
   (getter)minhash_get_seed,
   NULL,
   minhash_get_seed_doc,
   NULL},
  {NULL}          /* sentinel */
};
```

Having that said, if #79 is to be merged, the earlier the better as the refactoring will almost create the need for manual conflict resolution if the C-level codebase is evolving in the meantime.
