### ISSUE TITLE
lexical error: invalid char in json text.

### ISSUE THREAD

**Issue by Somebodyatthdoor** [dib-lab/sourmash#878]
Hi,

I am currently trying to run sourmash as part of the MAGpy pipeline (https://github.com/WatsonLab/MAGpy). I have been getting the following error:

^M^[[Kloaded query: mags/mag_PRJNA417359_jejunum_m... (k=31, DNA)
^M^[[KError in parsing signature; quitting.
^M^[[KException: lexical error: invalid char in json text.
                                      [                     (right here) ------^

^M^[[KError in parsing signature; quitting.
^M^[[KException:
^M^[[K
Cannot open file '../sourmash/genbank-d2-k31.sbt.json'

The MAGpy pipeline developer has suggested that this may be because the format of the signatures has changed between sourmash versions. I have been trying to use the latest version of the Genbank k=31, 2018.03.29 database. MAGpy uses sourmash version 2.0.0a9. Is there a specific version of the downloadable signature databases which works with this version of sourmash? Or do you think this error is likely to have a different cause? 

Thank you for your help.

**Comment by ctb** [comment]
hi, thanks for e-mailing!j

yes, this is at least partly a sourmash version thing; there should be an older
version available, see links here,

https://github.com/dib-lab/sourmash/commit/c176cd27f349cfda9e5d2061b100b483804ef4a8#diff-37f26e34d641a735587d9b2f0e20e40eR23

it looks like this is the one you want:

https://s3-us-west-1.amazonaws.com/spacegraphcats.ucdavis.edu/microbe-genbank-sbt-k31-2017.05.09.tar.gz

or may be this one:

https://s3-us-west-1.amazonaws.com/spacegraphcats.ucdavis.edu/microbe-refseq-sbt-k31-2017.05.09.tar.gz

the error itself, "invalid char", looks weird to me, but I'll address that
separately :)

--titus

On Thu, Jan 30, 2020 at 07:27:47AM -0800, Somebodyatthdoor wrote:
> Hi,
> 
> I am currently trying to run sourmash as part of the MAGpy pipeline (https://github.com/WatsonLab/MAGpy). I have been getting the following error:
> 
> ^M^[[Kloaded query: mags/mag_PRJNA417359_jejunum_m... (k=31, DNA)
> ^M^[[KError in parsing signature; quitting.
> ^M^[[KException: lexical error: invalid char in json text.
>                                       [                     (right here) ------^
> 
> ^M^[[KError in parsing signature; quitting.
> ^M^[[KException:
> ^M^[[K
> Cannot open file '../sourmash/genbank-d2-k31.sbt.json'
> 
> The MAGpy pipeline developer has suggested that this may be because the format of the signatures has changed between sourmash versions. I have been trying to use the latest version of the Genbank k=31, 2018.03.29 database. MAGpy uses sourmash version 2.0.0a9. Is there a specific version of the downloadable signature databases which works with this version of sourmash? Or do you think this error is likely to have a different cause? 
> 
> Thank you for your help.
> 
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/dib-lab/sourmash/issues/878
-- 
C. Titus Brown, ctbrown@ucdavis.edu

**Comment by Somebodyatthdoor** [comment]
Hi,

I have tried using the https://s3-us-west-1.amazonaws.com/spacegraphcats.ucdavis.edu/microbe-genbank-sbt-k31-2017.05.09.tar.gz file but unfortunately I am still getting the same error.

**Comment by ctb** [comment]
OK, could you post the results of 

head -c 500 <database file>

pls?

thanks!

(hmm, note that for the .tar.gz file you will need to run 'tar xzf <filename>' in order to unpack the database. maybe try that first?)

On Fri, Jan 31, 2020 at 12:42:31AM -0800, Somebodyatthdoor wrote:
> Hi,
> 
> I have tried using the https://s3-us-west-1.amazonaws.com/spacegraphcats.ucdavis.edu/microbe-genbank-sbt-k31-2017.05.09.tar.gz file but unfortunately I am still getting the same error. 
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/dib-lab/sourmash/issues/878#issuecomment-580640002
-- 
C. Titus Brown, ctbrown@ucdavis.edu

**Comment by Somebodyatthdoor** [comment]
I had unpacked the database with the command:
gunzip < microbe-genbank-sbt-k31-2017.05.09.tar.gz | tar xvf 

I've attached the result from running the command:
head -c 500 genbank-k31.sbt.json

[json_head_output.txt](https://github.com/dib-lab/sourmash/files/4147039/json_head_output.txt)

**Comment by ctb** [comment]
hi @Somebodyatthdoor that all looks good to me. I have no idea what's going on! But it's happening with two different files, which is also odd. I have to look into the source code...

If you have time, could you give us the exact shell commands you used, from installation onwards?

thanks, & apologies.

**Comment by Somebodyatthdoor** [comment]
Hi,
I ran it as part of the MAGpy pipeline, following the installation instructions described in step 6 here: https://github.com/WatsonLab/MAGpy/blob/master/install.md.

MAGpy is a snakemake pipeline, the snakemake rule for sourmash gather is:

rule sourmash_gather:
        input: 'sourmash/{id}.sig'
        output:
                csv='sourmash/{id}.csv',
                out='sourmash/{id}.sm'
        params:
                gb=config["sourmash_gbk"]
        conda: "envs/sourmash.yaml"
        shell: "sourmash gather -k 31 {input} {params.gb} -o {output.csv} > {output.out}"

{params.gb} points to the genbank-k31.sbt.json file. 

If you would like I can send you all of the snakemake files?

**Comment by ctb** [comment]
nope, this should be sufficient - I'll take a look -- thx!

On Tue, Feb 04, 2020 at 06:57:44AM -0800, Somebodyatthdoor wrote:
> Hi,
> I ran it as part of the MAGpy pipeline, following the installation instructions described in step 6 here: https://github.com/WatsonLab/MAGpy/blob/master/install.md.
> 
> MAGpy is a snakemake pipeline, the snakemake rule for sourmash gather is:
> 
> rule sourmash_gather:
>         input: 'sourmash/{id}.sig'
>         output:
>                 csv='sourmash/{id}.csv',
>                 out='sourmash/{id}.sm'
>         params:
>                 gb=config["sourmash_gbk"]
>         conda: "envs/sourmash.yaml"
>         shell: "sourmash gather -k 31 {input} {params.gb} -o {output.csv} > {output.out}"
> 
> {params.gb} points to the genbank-k31.sbt.json file. 
> 
> If you would like I can send you all of the snakemake files? 
> 
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/dib-lab/sourmash/issues/878#issuecomment-581949066
-- 
C. Titus Brown, ctbrown@ucdavis.edu

**Comment by ctb** [comment]
hi, I went through the install and tested the database search. All seems to have worked for me.

```
3225  git clone https://github.com/WatsonLab/MAGpy.git
 3226  conda env create -f MAGpy/envs/install.yaml
 3227  conda activate magpy_install
 3228  mkdir magpy
 3229  cd magpy
 3230  wget -q https://s3-us-west-2.amazonaws.com/sourmash-databases/2018-03-29/genbank-d2-k31.tar.gz
 3231  ls -l
 3232  tar xzvf genbank-d2-k31.tar.gz 
 3233  ls
 3239  cat ../MAGpy/envs//sourmash.yaml
 3240  conda install -y sourmash=2.0.0a9
 3241  sourmash search 1.fa.sig genbank-d2-k31.sbt.json 
```

so, two requests --

* can you send me your MAG .sig file (mags/mag_PRJNA417359_jejunum_m*.sig :) at titus@idyll.org?
* can you do an 'ls -l' of the directory in which your .sbt.json is located and send that to me as well?

thanks for bearing with. Still puzzled but starting to rule things out!

**Comment by ctb** [comment]
ok - looks like the query signature is fine, and the SBT directory looks basically ok. do you think you could run the following python code as a script, passing the sbt.json file in as a path?
```
import sys
import sourmash
sbt = sourmash.load_sbt_index(sys.argv[1])
print(next(iter(sbt.leaves())))
```

I posted the code [here](https://gist.github.com/ctb/e204e4540a61e56dd172af0fa3c5a875), and you should be able to do:
```
wget https://gist.github.com/ctb/e204e4540a61e56dd172af0fa3c5a875/raw/fab72b8342515a1134b02735e03e1a992ee9f7d1/check-sbt.py
python check-sbt.py ../sourmash/genbank-d2-k31.sbt.json
```

**Comment by Somebodyatthdoor** [comment]
Sorry for the delay. I ran this from within the conda environment which I use to run sourmash and got the following:

Traceback (most recent call last):
  File "check-sbt.py", line 3, in <module>
    sbt = sourmash.load_sbt_index(sys.argv[1])
  File "/exports/software/myanaconda/MAGpy-3.5/lib/python3.5/site-packages/sourmash/sbtmh.py", line 12, in load_sbt_index
    return SBT.load(filename, leaf_loader=SigLeaf.load)
  File "/exports/software/myanaconda/MAGpy-3.5/lib/python3.5/site-packages/sourmash/sbt.py", line 424, in load
    return loaders[version](jnodes, leaf_loader, dirname, storage)
KeyError: 4

**Comment by ctb** [comment]
hi @Somebodyatthdoor I'm sorry for ignoring this for so long! You seem to be running into some kind of corruption error in the database, perhaps related to download or unpacking.

If you are still interested, let me know. In the most recent releases we've updated the databases so that you can download and use them in the same (compressed) zip format, and that might make things work!

I'll close this for now and we can reopen if you get back to us and want to pursue :) - thanks!
