### ISSUE TITLE
do we need __getstate__/__setstate__ *and* __reduce__ on MinHash objects?

### ISSUE THREAD

**Issue by ctb** [dib-lab/sourmash#895]
https://docs.python.org/3/library/pickle.html seems to imply we only need one or the other. if we need both, we should document why.

when removing `__reduce__`, all the tests still pass.

**Comment by luizirber** [comment]
Are you running the `10x` tests too? I remember some sort of issue with `pathos.multiprocessing` (for signatures).

But even better if we keep just one of them =]

**Comment by ctb** [comment]
per 564f89d319e899 it looks like `__reduce__` is a python 2.7 compatibility hack.
