### ISSUE TITLE
should MinHash objects support list or dict interface?

### ISSUE THREAD

**Issue by ctb** [dib-lab/sourmash#896]
We could support iteration and/or indexing. e.g.

```
for hash in mh_object:
   ...
```

and

```
for hash in mh_object:
    abund = mh_object[hash]
```

**Comment by luizirber** [comment]
I think it is similar to element access in NumPy arrays: it is more intuitive at first sight, but almost impossible to optimize without something like Numba...

So, mixed feelings. But in case we go ahead with the idea, I would prefer a `dict` interface (with key iteration by default, but also provide `.keys()` -> `.hashes()`, `.values()` -> `.abundances()` and `.items()` equivalents).

**Comment by ctb** [comment]
https://github.com/dib-lab/sourmash/issues/82 is relevant.

**Comment by ctb** [comment]
What about providing a view attribute or property that supports a dict interface?

```
mh = MinHash(...)
for hash in mh.hashes:
   ...

for hash, abund in mh.hashes.items():
   ...
```

**Comment by ctb** [comment]
In #1128, I try out `MinHash.hashes` as a property that returns a dictionary, with keys as hashes and abunds as values. For non-`track_abundance` `MinHash` objects, values are always 1.

I like this change; it makes the code clearer, and the code is also simpler (everywhere but the tests).
