### ISSUE TITLE
Should we have read-only minhashes?

### ISSUE THREAD

**Issue by ctb** [dib-lab/sourmash#90]
Right now the primary use case(s) for sourmash revolve around this workflow:

* calculate minhashes, save to disk;
* then, load from disk to search, query, index, whatnot.

however our save/load code and our basic MinHash code assume that you might want to update MinHashes at any time.

do things simplify if we force an explicit difference between searching/comparing a loaded MinHash and updating a loaded MinHash?

a secondary use case that I'm exploring in some other projects is to do more with merging and otherwise manipulating minhashes, but that's easily done by creating a new `MinHash` object and then updating as appropriate with the result of `get_mins()`.

**Comment by lgautier** [comment]
I am coming to making a difference between building a MinHash and using a MinHash purely from a design+performance standpoint: to make the building more efficient I require an accessory data structure, but that added space entails a higher memory usage (which has an impact on the number of sketches that can concurrently stay in memory).

**Comment by ctb** [comment]
At least at the moment, I haven't found a strong reason to split the internal MinHash object API; and, there's no reason that any compute functionality in any package (including sourmash) has to pay attention to our internal MinHash object API. So at least for the nonce I will close this.
