### ISSUE TITLE
Should I expect identical result after rescale? 

### ISSUE THREAD

**Issue by metajinomics** [dib-lab/sourmash#908]
Hi, Can I ask a question? I use Sourmash to find what is in my metagenome(shotgun sequencing). I built a custom DB with a scaled value of 2000. Then (accidentally) I run Sourmash compute with scaled value 5000 but gather command with DB that was scaled with 2000. I realized you mentioned that I should use an identical scaled value in your recent publication. So, I re-build DB with a scaled value of 5000. I compared one of the metagenome(shotgun sequencing), but the result looks slightly different. For example, 7th results are NZ_KZ269759.1 and NZ_OGPI02000075.1 in 2000-scaled-DB and 5000-scaled-DB, respectively. Both are E. coli but different strain. I think Sourmash auto-rescale. So, should I expect an identical result in both cases? 

Here is the detailed command:
CASE1:
sourmash compute --scaled 5000 -k 51 SRR1765620.fastq.gz -o SRR1765620.scaled5000.sig
sourmash gather -k 51 customDB.scaled2000 SRR1765620.scaled5000.sig
result: SRR1765620_2000.txt

CASE2:
sourmash compute --scaled 5000 -k 51 SRR1765620.fastq.gz -o SRR1765620.scaled5000.sig
sourmash gather -k 51 customDB.scaled5000 SRR1765620.scaled5000.sig
result: SRR1765620_5000.txt

I attached two TXT files, which are CSV files.
[SRR1765620_2000.txt](https://github.com/dib-lab/sourmash/files/4220686/SRR1765620_2000.txt)
[SRR1765620_5000.txt](https://github.com/dib-lab/sourmash/files/4220687/SRR1765620_5000.txt)

**Comment by ctb** [comment]
hi! sorry for taking so long to reply, been busy with teaching and now isolation!

some variation in results is expected at this level. Basically, as scaled increases in size you lose resolution to detect minor differences in strain membership. We generally suggest using sourmash as a first pass filter, and then following up with other approaches, e.g. assembly or direct read alignment, if you need finer-grained details!

**Comment by ctb** [comment]
please let us know if you have more questions on this issue! closing for now.
