### ISSUE TITLE
multiple sequenced genomes and paired-end reads

### ISSUE THREAD

**Issue by FerJmnzCc** [dib-lab/sourmash#913]
Hi, I am new to this world. And trying to apply the guide and also the tutorial I have some problems. Probably of misunderstanding.

I have 31 sequenced bacterial isolates (treated as different samples);
-sample1_forward.fasq.gz & sample1_reverse.fasq.gz
-.... .....
-sample31_forward.fasq.gz & sample31_reverse.fasq.gz

When I tried to run the 'suormash compute' I understand I had to run it for all the samples and merged them (31 genomes x 2 PE fastq files) and use the --merge to join then in a unique 'sig file'. 
In the folder with all the fasq files (31x2);

**>sourmash compute --scaled 1000 -k 21,31,51 reads*.fq.abundtrim --merge SOMENAME -o SOMENAME-reads.sig**

I get nothing to do with the result when I run the sourmash compare (only a vertical line XD)

1) Do I have to do a loop for run 'compute' for each couple of paired end genome and get a unique .sig file for each genome? 

2) So, is the 'merge' function only usable for merge both paired ends fastq files to generate a unique '.sig file'?

3) Do I have to pre-process in some way the fastq files? (I used trim-low-abund script to trim them in a loop by pairs of same genome). 

4) Should I add the --track-abundance for each pair of fastq files?

Sorry for the naive questions! 
And thank you for your help!
Regards!

**Comment by ctb** [comment]
thanks for your questions!

Yep, you need generate the .sig file for each pair of read files explicitly.

If you used trim-low-abund, that's all you need by way of trimming!

You can use track-abundance without fear, as you can always discard the abundances later if you don't want to use them. But, what question(s) are you asking? If you mostly want to cluster the genomes by similarity, and these are isolates, I would not bother with --track-abundance as it is more useful for RNAseq and metagenomes, where there is differential abundance between the various molecules in the sample.

Hope that helps, please ask more questions as you have them!

**Comment by FerJmnzCc** [comment]
Thank you Titus! It helped! :)

Now, after running sourmash compute, y run surmash compare with all the sig files, and I got this, although the program give me a pretty pdf with the clustering tree;

> 

== Please cite Brown and Irber (2016), doi:10.21105/joss.00027. ==

Error in parsing signature; quitting.
Exception: expected value at line 1 column 1

warning: no signatures loaded at given ksize/molecule type from bacteria_cmp
Error in parsing signature; quitting.
Exception: expected value at line 1 column 1

warning: no signatures loaded at given ksize/molecule type from bacteria_cmp.dendro.pdf
Error in parsing signature; quitting.
Exception: expected value at line 1 column 1

warning: no signatures loaded at given ksize/molecule type from bacteria_cmp.hist.pdf
Error in parsing signature; quitting.
Exception: invalid type: integer `12`, expected a sequence at line 1 column 3

warning: no signatures loaded at given ksize/molecule type from bacteria_cmp.labels.txt
Error in parsing signature; quitting.
Exception: expected value at line 1 column 1

warning: no signatures loaded at given ksize/molecule type from bacteria_cmp.matrix.pdf
Error in parsing signature; quitting.
Exception: expected value at line 1 column 1

warning: no signatures loaded at given ksize/molecule type from sourmash_compare.sh
loaded 27 signatures total. 

> 

What these error messages mean? 
Thank you a lot!
Fer

**Comment by ctb** [comment]
Hi, it looks like your wildcard for sourmash compare included many non-.sig
files, such as 'bacteria_cmp', 'bacteria_cmp.dendro.pdf', etc. What was
your command line?

best,
--titus

**Comment by FerJmnzCc** [comment]
ok, I run it twice and it read the previous generated files, that's it :) 
I just put <sourmash compare -k 51 -p 8 * -o klebsiella_imibic_cmp> because I forgot to add the .sig in the output name of sourmash compute, so all the sig files have no extension suffix
I will learn at the end XD
Fer

**Comment by ctb** [comment]
great! and no worries, please keep asking questions as you have them!

On Mon, Mar 09, 2020 at 09:59:19AM -0700, FerJmnzCc wrote:
> ok, I run it twice and it read the previous generated files, that's it :) 
> I just put <sourmash compare -k 51 -p 8 * -o klebsiella_imibic_cmp> because I forgot to add the .sig in the output name of sourmash compute, so all the sig files have no extension suffix
> I will learn at the end XD
> Fer
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/dib-lab/sourmash/issues/913#issuecomment-596652204
-- 
C. Titus Brown, ctbrown@ucdavis.edu
