### ISSUE TITLE
Document and streamline/refactor signature loading and saving

### ISSUE THREAD

**Issue by ctb** [dib-lab/sourmash#919]
I think this shows up in some other issues too, especially the loading, but from slack:

@taylorreiter 
>I’ve tried about 1 million and 1 combinations of things, and even read the code in unit tests, and can’t figure out how to write out a sourmash sig in the python api.

@olgabot:
> Maybe worth writing some wrappers that take a list of signatures and a file*name* to save? Or a list of paths and returns all signatures?

**Comment by taylorreiter** [comment]
I think just adding:
```
with open(out_sig, 'wt') as fp:
```
so it reads:
```
with open(out_sig, 'wt') as fp:
      signature.save_signatures([sig], fp)
```
would be really helpful!

**Comment by ctb** [comment]
OK!

I found [this](https://sourmash.readthedocs.io/en/latest/api-example.html#saving-and-loading-signature-files) -- and [this](https://sourmash.readthedocs.io/en/latest/_modules/sourmash/signature.html#save_signatures). I think the latter is probably what are referring to above, in terms of adding `with ...`.

**Comment by ctb** [comment]
See #921.

**Comment by ctb** [comment]
ref https://github.com/dib-lab/sourmash/issues/875

**Comment by ctb** [comment]
also see #934.

**Comment by ctb** [comment]
per https://github.com/dib-lab/sourmash/issues/875#issuecomment-650904856, 
>I think `sourmash_args.load_database` and `sourmash_args.load_file_as_signatures` should become the recommended public API for loading signatures; see #1059
