### ISSUE TITLE
Notes from following release process for 3.2.3rc1

### ISSUE THREAD

**Issue by ctb** [dib-lab/sourmash#955]
Oddly enough, readthedocs seems to not have rendered https://sourmash.readthedocs.io/en/latest/release.html properly? But the other pages look fine. And it builds OK locally.

I needed to use conda environments on both farm (Linux) and my laptop (Mac OS X) in order to get the right build etc. environment. I ran into some problems with a python 3.8 environment -- apparently htslib and/or pysam don't yet build properly via pip install? - so I ended up using the following conda incantation:
```
conda create -y -n sourmash-rc2 python=3.7 pip cxx-compiler make htslib pysam
```
which worked for both architectures.

**Comment by luizirber** [comment]
> Oddly enough, readthedocs seems to not have rendered https://sourmash.readthedocs.io/en/latest/release.html properly? But the other pages look fine. And it builds OK locally.

weird... seems like it's missing `recommonmark`? markdown pages all seem borked...

> I needed to use conda environments on both farm (Linux) and my laptop (Mac OS X) in order to get the right build etc. environment. I ran into some problems with a python 3.8 environment -- apparently htslib and/or pysam don't yet build properly via pip install? - so I ended up using the following conda incantation:
> 
> ```
> conda create -y -n sourmash-rc2 python=3.7 pip cxx-compiler make htslib pysam
> ```
> 
> which worked for both architectures.

According to https://github.com/czbiohub/bam2fasta/pull/12, the `pysam` release compatible with 3.8 has issues being installed in `3.5` and `3.6`.

**Comment by ctb** [comment]
the readthedocs issue seems to be b/c sphinx v3.0.2 doesn't work properly with recommonmark. at least, by upgrading from sphinx 2.3.1 to sphinx 3.x, I get the same problems locally!

**Comment by ctb** [comment]
fixed in #956, I believe.

**Comment by ctb** [comment]
Also, twine needs to be installed again before the final release upload (step 2 of "how to make a final release")

**Comment by ctb** [comment]
on github, the various tags cause various automatic things to happen. When you delete the tag for the release candidates in git and push it to github, it still leaves the release candidate in the release list on github, but without any name or release message.

so you need to delete the draft there, I guess.

also, can't get the hub stuff to work. not sure why.

**Comment by ctb** [comment]
I note on https://pypi.org/project/sourmash/3.2.3/ that the first line of the README shows up, `<meta charset="utf-8"/>`. Should we fix/remove?

**Comment by ctb** [comment]
commands I used to upload wheels:
```
twine upload sourmash-3.2.3-py2.py3-none-macosx_10_11_intel.whl
twine upload sourmash-3.2.3-py2.py3-none-manylinux1_x86_64.whl
twine upload sourmash-3.2.3-py2.py3-none-manylinux2010_x86_64.whl
```
- twine automagically figured out version names etc., and they all appear on [the sourmash pypi page](https://pypi.org/manage/project/sourmash/release/3.2.3/)!

**Comment by ctb** [comment]
Adding notes from v3.3.0 process -

* change `git push --tags git@github.com:dib-lab/sourmash.git` to `git push --tags origin`

**Comment by ctb** [comment]
remaining issues migrated to #1109
