### ISSUE TITLE
error: fewer than 20% of lineages have species-level resolution!?

### ISSUE THREAD

**Issue by rec3141** [dib-lab/sourmash#958]
Hi, I'm trying to run the tutorial at https://sourmash.readthedocs.io/en/latest/tutorials-lca.html on Building Your Own LCA database and am running into the following error.

PS the file at https://github.com/ctb/2017-sourmash-lca/raw/master/tara-delmont-SuppTable3.csv has DOS line breaks. I did `sed -i '/\r/\n/g' tara-delmont-SuppTable3.csv` before running the command below to make sure that wasn't the issue.

[/home/jovyan/topic-metagenomics/data]$ `sourmash lca index tara-delmont-SuppTable3.csv delmont.lca.json delmont-subsample-sigs/*.sig`

== This is sourmash version 3.2.3. ==
== Please cite Brown and Irber (2016), doi:10.21105/joss.00027. ==

examining spreadsheet headers...
** assuming column 'MAGs' is identifiers in spreadsheet
** assuming column 'Domain' is superkingdom in spreadsheet
Traceback (most recent call last):
  File "/srv/conda/envs/notebook/bin/sourmash", line 11, in <module>
    sys.exit(main())
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/sourmash/__main__.py", line 14, in main
    return mainmethod(args)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/sourmash/cli/lca/index.py", line 58, in main
    return sourmash.lca.command_index.index(args)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/sourmash/lca/command_index.py", line 154, in index
    force=args.force)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/sourmash/lca/command_index.py", line 102, in load_taxonomy_assignments
    raise Exception("error: fewer than 20% of lineages have species-level resolution!? ({} total found)".format(n_species))
Exception: error: fewer than 20% of lineages have species-level resolution!? (8 total found)

**Comment by ctb** [comment]
hah! my own double-check breaks a tutorial! thanks for reporting this -- will fix! For now, you should be able to add `-f` to the command line to get past this.

best,
--titus

**Comment by ctb** [comment]
thanks for finding this!! will be fixed in #963

**Comment by ctb** [comment]
(DOS EOL in spreadsheets are just fine, BTW! But good check :)
