### ISSUE TITLE
Redefine `Index.gather` interface to return a single (the best) result?

### ISSUE THREAD

**Issue by ctb** [dib-lab/sourmash#964]
See #962

**Comment by ctb** [comment]
also see #844

**Comment by luizirber** [comment]
hmm. Putting the `gather` algorithm in the index has advantages (for LCA it is one operation that can be cached and results `yield`ed as needed), but I think a `Index.best_match` method can be useful (and fit what you're describing here?).

**Comment by ctb** [comment]
see https://github.com/dib-lab/sourmash/issues/930 re caching and yield. Tricky but possible, not sure how generalizable the API will be.

yes, `gather` is `best_match` for containment, which is sort of the same as `search(..., best_match=True, containment=True)`.  I do like the word `gather` because it ties to a valuable operation at the highest level of sourmash and permits particular optimizations.

**Comment by ctb** [comment]
I'm going to close this for now; it doesn't bring me joy.
