### ISSUE TITLE
Access LCA hashes

### ISSUE THREAD

**Issue by phiweger** [dib-lab/sourmash#965]
Hi,

How would you access the LCA hashes that are specific to a set of genomes (like some species) from the LCA index, i.e. those hashes, that are ONLY present in those genomes, and not in any other genomes in the database?

Kindest regards,
Adrian

**Comment by ctb** [comment]
Here's a draft notebook - [Using the LCA_Database API](https://github.com/dib-lab/sourmash/blob/doc_lca_db_api/doc/using-LCA-database-API.ipynb). Please ask questions as you have them!

While writing this I found a redundant attribute and then a bug, so ...thanks for motivating :).

**Comment by ctb** [comment]
OK, and now that I re-read your question, you would do something like this to get hashes that are _only_ in that one query genome.

```
query_idx = 2
hashval_set = set()
for hashval, idx_set in db.hashval_to_idx.items():
    if query_idx in idx_set and len(idx_set) == 1: # this idx and only this idx
        hashval_set.add(hashval)
```

**Comment by phiweger** [comment]
thx for the quick reply @ctb !

I am after "private" hashes of a set of genomes (say all k-mer hashes unique to genomes A, B and C) -- is the approach the same (because you refer to "one query genome")?

**Comment by ctb** [comment]
On Mon, Apr 27, 2020 at 01:57:55AM -0700, Adrian Viehweger wrote:
> thx for the quick reply @ctb !
> 
> I am after "private" hashes of a set of genomes (say all k-mer hashes unique to genomes A, B and C) -- is the approach the same (because you refer to "one query genome")?

should be! you could do it in two ways --

iterate over query idxes

look for all hashval_to_idx values that have exactly length one.

The latter should be faster :)

**Comment by phiweger** [comment]
@ctb the link [above](https://github.com/dib-lab/sourmash/blob/doc_lca_db_api/doc/using-LCA-database-API.ipynb) is a dead end ... :(

**Comment by ctb** [comment]
Now in the docs at https://sourmash.readthedocs.io/en/latest/using-LCA-database-API.html

**Comment by ctb** [comment]
I'll close this issue for now - reopen and ask more questions as you have them!
