### ISSUE TITLE
API load_one_signature Error

### ISSUE THREAD

**Issue by ZeweiSong** [dib-lab/sourmash#967]
I was using load_one_signature() to readin the sig file, but got this error unable to solve:

```
>>> sig1 = load_one_signature('sourmash_signatures/GCA_000002515.1_ASM251v1.sig', ksize=31)
Error in parsing signature; quitting.
Exception: Unexpected symbol 'sourmash' at 0
Traceback (most recent call last):
  File "/home/zewei/.local/lib/python3.7/site-packages/sourmash/signature.py", line 244, in load_one_signature
    first_sig = next(sigiter)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/zewei/.local/lib/python3.7/site-packages/sourmash/signature.py", line 246, in load_one_signature
    raise ValueError("no signatures to load")
ValueError: no signatures to load
```

The signature is calculated under commandline, and I can open it normally.

You can find the sig file here: https://c-t.work/s/d43faf9d780647

Thanks!

Zewei

**Comment by ctb** [comment]
Hi Zewei,

what does `sourmash sig describe` report when you run it on the filename?

thanks,
--titus

On Tue, Apr 28, 2020 at 01:42:12AM -0700, Zewei Song wrote:
> I was using load_one_signature() to readin the sig file, but got this error unable to solve:
> 
> ```
> >>> sig1 = load_one_signature('sourmash_signatures/GCA_000002515.1_ASM251v1.sig', ksize=31)
> Error in parsing signature; quitting.
> Exception: Unexpected symbol 'sourmash' at 0
> Traceback (most recent call last):
>   File "/home/zewei/.local/lib/python3.7/site-packages/sourmash/signature.py", line 244, in load_one_signature
>     first_sig = next(sigiter)
> StopIteration
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/zewei/.local/lib/python3.7/site-packages/sourmash/signature.py", line 246, in load_one_signature
>     raise ValueError("no signatures to 
> ```load")
> ValueError: no signatures to load
> 
> The signature is calculated under commandline, and I can open it normally.
> 
> Thanks!
> 
> Zewei
> 
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/dib-lab/sourmash/issues/967
-- 
C. Titus Brown, ctbrown@ucdavis.edu

**Comment by ZeweiSong** [comment]
Thanks! I was using an older version of sourmash.
