### ISSUE TITLE
document new SBT zip file output.

### ISSUE THREAD

**Issue by ctb** [dib-lab/sourmash#973]
per #648, if you ask `sourmash index` to produce a file with suffix `.sbt.zip`, it will put the SBT in a zip file. until 4.0, this won't be the default output, but it is _extremely_ useful :)

A few details that might be worth mentioning -

* you can speed up access by unzipping the SBT
* it's not clear if the unzipped version takes up a lot more space, b/c the nodes (internal and signatures both) should all be compressed too, I think?
* we should try to summarize the performance characteristics (detailed in #648) in terms of space, time, and memory tradeoffs, vs the old SBT.

Anything else?

**Comment by luizirber** [comment]
> you can speed up access by unzipping the SBT

Need to measure it better, but doesn't seem to make much difference for now.

>     * it's not clear if the unzipped version takes up a lot more space, b/c the nodes (internal and signatures both) should all be compressed too, I think?

Yup, should take about the same space.

> we should try to summarize the performance characteristics (detailed in #648) in terms of space, time, and memory tradeoffs, vs the old SBT.

from https://github.com/dib-lab/sourmash/pull/648#issuecomment-620979094

Level | Size | Time
--- | --- | ---
0 | 407 MB | 16s
1 | 252 MB | 21s
5 | 250 MB | 39s
9 | 246 MB | 1m48s


> Anything else?

- Related to #970 , update docs and tutorials to use the new zipped prepared SBTs (when they are published)

**Comment by ctb** [comment]
see #975.

turns out our `index` documentation in the docs is ...terrible. We should have a whole section on database types, I guess.

**Comment by ctb** [comment]
(by terrible I mean nonexistent :)
