### ISSUE TITLE
Convert to/from Mash sketch format

### ISSUE THREAD

**Issue by lskatz** [dib-lab/sourmash#99]
Hi @ctb, I was wondering if you could make a Sourmash subcommand to convert back and forth between YAML and the format used for Mash sketches.  This would help increase compatibility between Mash and Sourmash.

**Comment by ctb** [comment]
Hi Lee, the code is already there!  Sort of. See the 'import_csv' command
of sourmash.

Also see:

https://github.com/marbl/Mash/issues/27#issuecomment-270796699

Disclaimer: this has been back burnered, but the code should still work.

You might also be interested in 

https://github.com/dib-lab/sourmash/blob/dd18fdd89d4a061b8fca2ee7e529b0064066704b/utils/compute-dna-mh-another-way.py

which shows you how to construct a JSON (we switched recently :) signature
from any collection of hashes.

**Comment by lskatz** [comment]
Ok.  So to import a mash sketch to Sourmash, I would use the `mash info -d` command to make a dump and then `sourmash import_csv`?

**Comment by ctb** [comment]
On Mon, Jan 09, 2017 at 08:24:10AM -0800, Lee Katz wrote:
> Ok.  So to import a mash sketch to Sourmash, I would use the `mash info -d` command to make a dump and then `sourmash import_csv`?

Yes, I think.

I'm not sure where the mash support for this stands, but the sourmash side
of things is in our tests so that code should work!  If you run into mash
trouble let me know and I'll see what I can do.

**Comment by lskatz** [comment]
Thanks!

**Comment by ctb** [comment]
(and if it works and you get a chance to report back, that'd be nice too :)

**Comment by ctb** [comment]
I've hacked together a script, `utils/mash-to-sourmash-sig.py`, that reads the output of 'mash info -d' and outputs it to a sourmash signature.  See #121.  It's hacky for the moment but seems to basically work - I'll improve it before #121 is committed, and add some tests.

Ref https://github.com/marbl/Mash/issues/27 #99 https://github.com/marbl/Mash/issues/35

**Comment by ctb** [comment]
Yes! Please see sourmash signature import and export!!

--
Titus Brown, ctbrown@ucdavis.edu<mailto:ctbrown@ucdavis.edu>

On Jan 15, 2019, at 11:27 AM, Lee Katz <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @ctb<https://github.com/ctb> , is there a new version of this command line script for converting JSON<=>MSH? I don't see this script in the latest version but I would like to use it again.

**Comment by lskatz** [comment]
Oh that's great!  However, I got an error `Unrecognized command` for `sig`, `import`, and `signature`

```[gzu2@monolith4 TTR_out.rep1]$ sourmash sig
Unrecognized command

sourmash <command> [<args>]

** Commands include:

compute <filenames>         Compute MinHash signatures for sequences in files.
compare <filenames.sig>     Compute similarity matrix for multiple signatures.
search <query> <against>    Search a signature against a list of signatures.
plot <matrix>               Plot a distance matrix made by 'compare'.
gather                      Search a metagenome signature for multiple
                                 non-overlapping matches.

** Taxonomic classification utilities:

   Run 'sourmash lca' for the taxonomic classification routines.

** Sequence Bloom Tree (SBT) utilities:

index                   Index a collection of signatures for fast searching.
sbt_combine             Combine multiple SBTs into a new one.
categorize              Identify best matches for many signatures using an SBT.
watch                   Classify a stream of sequences.

** Other information:

info                        Sourmash version and other information.

Use '-h' to get subcommand-specific help, e.g.

sourmash compute -h

** Documentation is available at https://sourmash.readthedocs.io/
```

**Comment by lskatz** [comment]
```[gzu2@monolith4 TTR_out.rep1]$ sourmash info
sourmash version 2.0.0a11
- loaded from path: /scicomp/home/gzu2/bin/anaconda2/lib/python2.7/site-packages/sourmash
```

**Comment by ctb** [comment]
Ahh, sorry, the very latest isn’t released yet on conda or pypi, I guess! You can still use the script from an earlier version just fine. We will release 2.0 very soon.

--
Titus Brown, ctbrown@ucdavis.edu<mailto:ctbrown@ucdavis.edu>

On Jan 15, 2019, at 11:37 AM, Lee Katz <notifications@github.com<mailto:notifications@github.com>> wrote:


sourmash version 2.0.0a11
- loaded from path: /scicomp/home/gzu2/bin/anaconda2/lib/python2.7/site-packages/sourmash
