### ISSUE TITLE
Question: sourmash with chromatin data

### ISSUE THREAD

**Issue by biobenkj** [dib-lab/sourmash#990]
Hi @luizirber and @ctb! sourmash rulez. I'm working on a project inferring chromatin structure from single cells and everyone enjoys being able to look at cell (sub) types from their single cell data. I was trying to think through whether sketching single cell signatures with sourmash from inferred chromatin structure (read scHiC data or something) when we are scaling to large numbers of cells. In principle, cells of a similar state/fate will have similar chromatin structure and maybe similar cell type sketches. Do you think something like this is feasible with sourmash? And perhaps more importantly, does it make sense or is it way off in left field? Thanks!

**Comment by ctb** [comment]
On Thu, May 14, 2020 at 08:25:55AM -0700, Ben Johnson wrote:
> Hi @luizirber and @ctb! sourmash rulez. I'm working on a project inferring chromatin structure from single cells and everyone enjoys being able to look at cell (sub) types from their single cell data. I was trying to think through whether sketching single cell signatures with sourmash from inferred chromatin structure (read scHiC data or something) when we are scaling to large numbers of cells. In principle, cells of a similar state/fate will have similar chromatin structure and maybe similar cell type sketches. Do you think something like this is feasible with sourmash?

hi Ben!

Two key questions --

first, is some kind of k-mer based comparison (Jaccard similarity or
containment, or angular distance/cosine similarity) relevant? I can't
immediately think of how you'd use this with HiC data but I don't work
with it much :)

second, are you comparing 100s of thousands of distinct k-mers, or more?
If less, than no need to use sketching. If more, we can help :)

What I'd honestly suggest doing tho is just running a sourmash compute,
compare, and plot with some real data. It's pretty fast :)

**Comment by ctb** [comment]
closing for now. let us know!
